/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-google-api/apis/logging/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeProjectSinks implements ProjectSinkInterface
type FakeProjectSinks struct {
	Fake *FakeLoggingV1alpha1
	ns   string
}

var projectsinksResource = schema.GroupVersionResource{Group: "logging.google.kubeform.com", Version: "v1alpha1", Resource: "projectsinks"}

var projectsinksKind = schema.GroupVersionKind{Group: "logging.google.kubeform.com", Version: "v1alpha1", Kind: "ProjectSink"}

// Get takes name of the projectSink, and returns the corresponding projectSink object, and an error if there is any.
func (c *FakeProjectSinks) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ProjectSink, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(projectsinksResource, c.ns, name), &v1alpha1.ProjectSink{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectSink), err
}

// List takes label and field selectors, and returns the list of ProjectSinks that match those selectors.
func (c *FakeProjectSinks) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ProjectSinkList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(projectsinksResource, projectsinksKind, c.ns, opts), &v1alpha1.ProjectSinkList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ProjectSinkList{ListMeta: obj.(*v1alpha1.ProjectSinkList).ListMeta}
	for _, item := range obj.(*v1alpha1.ProjectSinkList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested projectSinks.
func (c *FakeProjectSinks) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(projectsinksResource, c.ns, opts))

}

// Create takes the representation of a projectSink and creates it.  Returns the server's representation of the projectSink, and an error, if there is any.
func (c *FakeProjectSinks) Create(ctx context.Context, projectSink *v1alpha1.ProjectSink, opts v1.CreateOptions) (result *v1alpha1.ProjectSink, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(projectsinksResource, c.ns, projectSink), &v1alpha1.ProjectSink{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectSink), err
}

// Update takes the representation of a projectSink and updates it. Returns the server's representation of the projectSink, and an error, if there is any.
func (c *FakeProjectSinks) Update(ctx context.Context, projectSink *v1alpha1.ProjectSink, opts v1.UpdateOptions) (result *v1alpha1.ProjectSink, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(projectsinksResource, c.ns, projectSink), &v1alpha1.ProjectSink{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectSink), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeProjectSinks) UpdateStatus(ctx context.Context, projectSink *v1alpha1.ProjectSink, opts v1.UpdateOptions) (*v1alpha1.ProjectSink, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(projectsinksResource, "status", c.ns, projectSink), &v1alpha1.ProjectSink{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectSink), err
}

// Delete takes name of the projectSink and deletes it. Returns an error if one occurs.
func (c *FakeProjectSinks) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(projectsinksResource, c.ns, name), &v1alpha1.ProjectSink{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeProjectSinks) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(projectsinksResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ProjectSinkList{})
	return err
}

// Patch applies the patch and returns the patched projectSink.
func (c *FakeProjectSinks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ProjectSink, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(projectsinksResource, c.ns, name, pt, data, subresources...), &v1alpha1.ProjectSink{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectSink), err
}
