/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubeform.dev/provider-google-api/apis/logging/v1alpha1"
)

// FakeProjectBucketConfigs implements ProjectBucketConfigInterface
type FakeProjectBucketConfigs struct {
	Fake *FakeLoggingV1alpha1
	ns   string
}

var projectbucketconfigsResource = schema.GroupVersionResource{Group: "logging.google.kubeform.com", Version: "v1alpha1", Resource: "projectbucketconfigs"}

var projectbucketconfigsKind = schema.GroupVersionKind{Group: "logging.google.kubeform.com", Version: "v1alpha1", Kind: "ProjectBucketConfig"}

// Get takes name of the projectBucketConfig, and returns the corresponding projectBucketConfig object, and an error if there is any.
func (c *FakeProjectBucketConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ProjectBucketConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(projectbucketconfigsResource, c.ns, name), &v1alpha1.ProjectBucketConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectBucketConfig), err
}

// List takes label and field selectors, and returns the list of ProjectBucketConfigs that match those selectors.
func (c *FakeProjectBucketConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ProjectBucketConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(projectbucketconfigsResource, projectbucketconfigsKind, c.ns, opts), &v1alpha1.ProjectBucketConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ProjectBucketConfigList{ListMeta: obj.(*v1alpha1.ProjectBucketConfigList).ListMeta}
	for _, item := range obj.(*v1alpha1.ProjectBucketConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested projectBucketConfigs.
func (c *FakeProjectBucketConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(projectbucketconfigsResource, c.ns, opts))

}

// Create takes the representation of a projectBucketConfig and creates it.  Returns the server's representation of the projectBucketConfig, and an error, if there is any.
func (c *FakeProjectBucketConfigs) Create(ctx context.Context, projectBucketConfig *v1alpha1.ProjectBucketConfig, opts v1.CreateOptions) (result *v1alpha1.ProjectBucketConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(projectbucketconfigsResource, c.ns, projectBucketConfig), &v1alpha1.ProjectBucketConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectBucketConfig), err
}

// Update takes the representation of a projectBucketConfig and updates it. Returns the server's representation of the projectBucketConfig, and an error, if there is any.
func (c *FakeProjectBucketConfigs) Update(ctx context.Context, projectBucketConfig *v1alpha1.ProjectBucketConfig, opts v1.UpdateOptions) (result *v1alpha1.ProjectBucketConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(projectbucketconfigsResource, c.ns, projectBucketConfig), &v1alpha1.ProjectBucketConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectBucketConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeProjectBucketConfigs) UpdateStatus(ctx context.Context, projectBucketConfig *v1alpha1.ProjectBucketConfig, opts v1.UpdateOptions) (*v1alpha1.ProjectBucketConfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(projectbucketconfigsResource, "status", c.ns, projectBucketConfig), &v1alpha1.ProjectBucketConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectBucketConfig), err
}

// Delete takes name of the projectBucketConfig and deletes it. Returns an error if one occurs.
func (c *FakeProjectBucketConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(projectbucketconfigsResource, c.ns, name), &v1alpha1.ProjectBucketConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeProjectBucketConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(projectbucketconfigsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ProjectBucketConfigList{})
	return err
}

// Patch applies the patch and returns the patched projectBucketConfig.
func (c *FakeProjectBucketConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ProjectBucketConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(projectbucketconfigsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ProjectBucketConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectBucketConfig), err
}
