/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-google-api/apis/game/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeServicesGameServerClusters implements ServicesGameServerClusterInterface
type FakeServicesGameServerClusters struct {
	Fake *FakeGameV1alpha1
	ns   string
}

var servicesgameserverclustersResource = schema.GroupVersionResource{Group: "game.google.kubeform.com", Version: "v1alpha1", Resource: "servicesgameserverclusters"}

var servicesgameserverclustersKind = schema.GroupVersionKind{Group: "game.google.kubeform.com", Version: "v1alpha1", Kind: "ServicesGameServerCluster"}

// Get takes name of the servicesGameServerCluster, and returns the corresponding servicesGameServerCluster object, and an error if there is any.
func (c *FakeServicesGameServerClusters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ServicesGameServerCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(servicesgameserverclustersResource, c.ns, name), &v1alpha1.ServicesGameServerCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServicesGameServerCluster), err
}

// List takes label and field selectors, and returns the list of ServicesGameServerClusters that match those selectors.
func (c *FakeServicesGameServerClusters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ServicesGameServerClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(servicesgameserverclustersResource, servicesgameserverclustersKind, c.ns, opts), &v1alpha1.ServicesGameServerClusterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ServicesGameServerClusterList{ListMeta: obj.(*v1alpha1.ServicesGameServerClusterList).ListMeta}
	for _, item := range obj.(*v1alpha1.ServicesGameServerClusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested servicesGameServerClusters.
func (c *FakeServicesGameServerClusters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(servicesgameserverclustersResource, c.ns, opts))

}

// Create takes the representation of a servicesGameServerCluster and creates it.  Returns the server's representation of the servicesGameServerCluster, and an error, if there is any.
func (c *FakeServicesGameServerClusters) Create(ctx context.Context, servicesGameServerCluster *v1alpha1.ServicesGameServerCluster, opts v1.CreateOptions) (result *v1alpha1.ServicesGameServerCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(servicesgameserverclustersResource, c.ns, servicesGameServerCluster), &v1alpha1.ServicesGameServerCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServicesGameServerCluster), err
}

// Update takes the representation of a servicesGameServerCluster and updates it. Returns the server's representation of the servicesGameServerCluster, and an error, if there is any.
func (c *FakeServicesGameServerClusters) Update(ctx context.Context, servicesGameServerCluster *v1alpha1.ServicesGameServerCluster, opts v1.UpdateOptions) (result *v1alpha1.ServicesGameServerCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(servicesgameserverclustersResource, c.ns, servicesGameServerCluster), &v1alpha1.ServicesGameServerCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServicesGameServerCluster), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeServicesGameServerClusters) UpdateStatus(ctx context.Context, servicesGameServerCluster *v1alpha1.ServicesGameServerCluster, opts v1.UpdateOptions) (*v1alpha1.ServicesGameServerCluster, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(servicesgameserverclustersResource, "status", c.ns, servicesGameServerCluster), &v1alpha1.ServicesGameServerCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServicesGameServerCluster), err
}

// Delete takes name of the servicesGameServerCluster and deletes it. Returns an error if one occurs.
func (c *FakeServicesGameServerClusters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(servicesgameserverclustersResource, c.ns, name), &v1alpha1.ServicesGameServerCluster{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeServicesGameServerClusters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(servicesgameserverclustersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ServicesGameServerClusterList{})
	return err
}

// Patch applies the patch and returns the patched servicesGameServerCluster.
func (c *FakeServicesGameServerClusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ServicesGameServerCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(servicesgameserverclustersResource, c.ns, name, pt, data, subresources...), &v1alpha1.ServicesGameServerCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServicesGameServerCluster), err
}
