/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-google-api/apis/accesscontext/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeManagerGcpUserAccessBindings implements ManagerGcpUserAccessBindingInterface
type FakeManagerGcpUserAccessBindings struct {
	Fake *FakeAccesscontextV1alpha1
	ns   string
}

var managergcpuseraccessbindingsResource = schema.GroupVersionResource{Group: "accesscontext.google.kubeform.com", Version: "v1alpha1", Resource: "managergcpuseraccessbindings"}

var managergcpuseraccessbindingsKind = schema.GroupVersionKind{Group: "accesscontext.google.kubeform.com", Version: "v1alpha1", Kind: "ManagerGcpUserAccessBinding"}

// Get takes name of the managerGcpUserAccessBinding, and returns the corresponding managerGcpUserAccessBinding object, and an error if there is any.
func (c *FakeManagerGcpUserAccessBindings) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ManagerGcpUserAccessBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(managergcpuseraccessbindingsResource, c.ns, name), &v1alpha1.ManagerGcpUserAccessBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagerGcpUserAccessBinding), err
}

// List takes label and field selectors, and returns the list of ManagerGcpUserAccessBindings that match those selectors.
func (c *FakeManagerGcpUserAccessBindings) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ManagerGcpUserAccessBindingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(managergcpuseraccessbindingsResource, managergcpuseraccessbindingsKind, c.ns, opts), &v1alpha1.ManagerGcpUserAccessBindingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ManagerGcpUserAccessBindingList{ListMeta: obj.(*v1alpha1.ManagerGcpUserAccessBindingList).ListMeta}
	for _, item := range obj.(*v1alpha1.ManagerGcpUserAccessBindingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested managerGcpUserAccessBindings.
func (c *FakeManagerGcpUserAccessBindings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(managergcpuseraccessbindingsResource, c.ns, opts))

}

// Create takes the representation of a managerGcpUserAccessBinding and creates it.  Returns the server's representation of the managerGcpUserAccessBinding, and an error, if there is any.
func (c *FakeManagerGcpUserAccessBindings) Create(ctx context.Context, managerGcpUserAccessBinding *v1alpha1.ManagerGcpUserAccessBinding, opts v1.CreateOptions) (result *v1alpha1.ManagerGcpUserAccessBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(managergcpuseraccessbindingsResource, c.ns, managerGcpUserAccessBinding), &v1alpha1.ManagerGcpUserAccessBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagerGcpUserAccessBinding), err
}

// Update takes the representation of a managerGcpUserAccessBinding and updates it. Returns the server's representation of the managerGcpUserAccessBinding, and an error, if there is any.
func (c *FakeManagerGcpUserAccessBindings) Update(ctx context.Context, managerGcpUserAccessBinding *v1alpha1.ManagerGcpUserAccessBinding, opts v1.UpdateOptions) (result *v1alpha1.ManagerGcpUserAccessBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(managergcpuseraccessbindingsResource, c.ns, managerGcpUserAccessBinding), &v1alpha1.ManagerGcpUserAccessBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagerGcpUserAccessBinding), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeManagerGcpUserAccessBindings) UpdateStatus(ctx context.Context, managerGcpUserAccessBinding *v1alpha1.ManagerGcpUserAccessBinding, opts v1.UpdateOptions) (*v1alpha1.ManagerGcpUserAccessBinding, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(managergcpuseraccessbindingsResource, "status", c.ns, managerGcpUserAccessBinding), &v1alpha1.ManagerGcpUserAccessBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagerGcpUserAccessBinding), err
}

// Delete takes name of the managerGcpUserAccessBinding and deletes it. Returns an error if one occurs.
func (c *FakeManagerGcpUserAccessBindings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(managergcpuseraccessbindingsResource, c.ns, name), &v1alpha1.ManagerGcpUserAccessBinding{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeManagerGcpUserAccessBindings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(managergcpuseraccessbindingsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ManagerGcpUserAccessBindingList{})
	return err
}

// Patch applies the patch and returns the patched managerGcpUserAccessBinding.
func (c *FakeManagerGcpUserAccessBindings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ManagerGcpUserAccessBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(managergcpuseraccessbindingsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ManagerGcpUserAccessBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagerGcpUserAccessBinding), err
}
