/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-google-api/apis/data/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCatalogEntryGroupIamPolicies implements CatalogEntryGroupIamPolicyInterface
type FakeCatalogEntryGroupIamPolicies struct {
	Fake *FakeDataV1alpha1
	ns   string
}

var catalogentrygroupiampoliciesResource = schema.GroupVersionResource{Group: "data.google.kubeform.com", Version: "v1alpha1", Resource: "catalogentrygroupiampolicies"}

var catalogentrygroupiampoliciesKind = schema.GroupVersionKind{Group: "data.google.kubeform.com", Version: "v1alpha1", Kind: "CatalogEntryGroupIamPolicy"}

// Get takes name of the catalogEntryGroupIamPolicy, and returns the corresponding catalogEntryGroupIamPolicy object, and an error if there is any.
func (c *FakeCatalogEntryGroupIamPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CatalogEntryGroupIamPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(catalogentrygroupiampoliciesResource, c.ns, name), &v1alpha1.CatalogEntryGroupIamPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CatalogEntryGroupIamPolicy), err
}

// List takes label and field selectors, and returns the list of CatalogEntryGroupIamPolicies that match those selectors.
func (c *FakeCatalogEntryGroupIamPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CatalogEntryGroupIamPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(catalogentrygroupiampoliciesResource, catalogentrygroupiampoliciesKind, c.ns, opts), &v1alpha1.CatalogEntryGroupIamPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CatalogEntryGroupIamPolicyList{ListMeta: obj.(*v1alpha1.CatalogEntryGroupIamPolicyList).ListMeta}
	for _, item := range obj.(*v1alpha1.CatalogEntryGroupIamPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested catalogEntryGroupIamPolicies.
func (c *FakeCatalogEntryGroupIamPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(catalogentrygroupiampoliciesResource, c.ns, opts))

}

// Create takes the representation of a catalogEntryGroupIamPolicy and creates it.  Returns the server's representation of the catalogEntryGroupIamPolicy, and an error, if there is any.
func (c *FakeCatalogEntryGroupIamPolicies) Create(ctx context.Context, catalogEntryGroupIamPolicy *v1alpha1.CatalogEntryGroupIamPolicy, opts v1.CreateOptions) (result *v1alpha1.CatalogEntryGroupIamPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(catalogentrygroupiampoliciesResource, c.ns, catalogEntryGroupIamPolicy), &v1alpha1.CatalogEntryGroupIamPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CatalogEntryGroupIamPolicy), err
}

// Update takes the representation of a catalogEntryGroupIamPolicy and updates it. Returns the server's representation of the catalogEntryGroupIamPolicy, and an error, if there is any.
func (c *FakeCatalogEntryGroupIamPolicies) Update(ctx context.Context, catalogEntryGroupIamPolicy *v1alpha1.CatalogEntryGroupIamPolicy, opts v1.UpdateOptions) (result *v1alpha1.CatalogEntryGroupIamPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(catalogentrygroupiampoliciesResource, c.ns, catalogEntryGroupIamPolicy), &v1alpha1.CatalogEntryGroupIamPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CatalogEntryGroupIamPolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCatalogEntryGroupIamPolicies) UpdateStatus(ctx context.Context, catalogEntryGroupIamPolicy *v1alpha1.CatalogEntryGroupIamPolicy, opts v1.UpdateOptions) (*v1alpha1.CatalogEntryGroupIamPolicy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(catalogentrygroupiampoliciesResource, "status", c.ns, catalogEntryGroupIamPolicy), &v1alpha1.CatalogEntryGroupIamPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CatalogEntryGroupIamPolicy), err
}

// Delete takes name of the catalogEntryGroupIamPolicy and deletes it. Returns an error if one occurs.
func (c *FakeCatalogEntryGroupIamPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(catalogentrygroupiampoliciesResource, c.ns, name), &v1alpha1.CatalogEntryGroupIamPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCatalogEntryGroupIamPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(catalogentrygroupiampoliciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CatalogEntryGroupIamPolicyList{})
	return err
}

// Patch applies the patch and returns the patched catalogEntryGroupIamPolicy.
func (c *FakeCatalogEntryGroupIamPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CatalogEntryGroupIamPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(catalogentrygroupiampoliciesResource, c.ns, name, pt, data, subresources...), &v1alpha1.CatalogEntryGroupIamPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CatalogEntryGroupIamPolicy), err
}
