/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AssetFolderFeedListerExpansion allows custom methods to be added to
// AssetFolderFeedLister.
type AssetFolderFeedListerExpansion interface{}

// AssetFolderFeedNamespaceListerExpansion allows custom methods to be added to
// AssetFolderFeedNamespaceLister.
type AssetFolderFeedNamespaceListerExpansion interface{}

// AssetOrganizationFeedListerExpansion allows custom methods to be added to
// AssetOrganizationFeedLister.
type AssetOrganizationFeedListerExpansion interface{}

// AssetOrganizationFeedNamespaceListerExpansion allows custom methods to be added to
// AssetOrganizationFeedNamespaceLister.
type AssetOrganizationFeedNamespaceListerExpansion interface{}

// AssetProjectFeedListerExpansion allows custom methods to be added to
// AssetProjectFeedLister.
type AssetProjectFeedListerExpansion interface{}

// AssetProjectFeedNamespaceListerExpansion allows custom methods to be added to
// AssetProjectFeedNamespaceLister.
type AssetProjectFeedNamespaceListerExpansion interface{}

// IdentityGroupListerExpansion allows custom methods to be added to
// IdentityGroupLister.
type IdentityGroupListerExpansion interface{}

// IdentityGroupNamespaceListerExpansion allows custom methods to be added to
// IdentityGroupNamespaceLister.
type IdentityGroupNamespaceListerExpansion interface{}

// IdentityGroupMembershipListerExpansion allows custom methods to be added to
// IdentityGroupMembershipLister.
type IdentityGroupMembershipListerExpansion interface{}

// IdentityGroupMembershipNamespaceListerExpansion allows custom methods to be added to
// IdentityGroupMembershipNamespaceLister.
type IdentityGroupMembershipNamespaceListerExpansion interface{}

// RunDomainMappingListerExpansion allows custom methods to be added to
// RunDomainMappingLister.
type RunDomainMappingListerExpansion interface{}

// RunDomainMappingNamespaceListerExpansion allows custom methods to be added to
// RunDomainMappingNamespaceLister.
type RunDomainMappingNamespaceListerExpansion interface{}

// RunServiceListerExpansion allows custom methods to be added to
// RunServiceLister.
type RunServiceListerExpansion interface{}

// RunServiceNamespaceListerExpansion allows custom methods to be added to
// RunServiceNamespaceLister.
type RunServiceNamespaceListerExpansion interface{}

// RunServiceIamBindingListerExpansion allows custom methods to be added to
// RunServiceIamBindingLister.
type RunServiceIamBindingListerExpansion interface{}

// RunServiceIamBindingNamespaceListerExpansion allows custom methods to be added to
// RunServiceIamBindingNamespaceLister.
type RunServiceIamBindingNamespaceListerExpansion interface{}

// RunServiceIamMemberListerExpansion allows custom methods to be added to
// RunServiceIamMemberLister.
type RunServiceIamMemberListerExpansion interface{}

// RunServiceIamMemberNamespaceListerExpansion allows custom methods to be added to
// RunServiceIamMemberNamespaceLister.
type RunServiceIamMemberNamespaceListerExpansion interface{}

// RunServiceIamPolicyListerExpansion allows custom methods to be added to
// RunServiceIamPolicyLister.
type RunServiceIamPolicyListerExpansion interface{}

// RunServiceIamPolicyNamespaceListerExpansion allows custom methods to be added to
// RunServiceIamPolicyNamespaceLister.
type RunServiceIamPolicyNamespaceListerExpansion interface{}

// SchedulerJobListerExpansion allows custom methods to be added to
// SchedulerJobLister.
type SchedulerJobListerExpansion interface{}

// SchedulerJobNamespaceListerExpansion allows custom methods to be added to
// SchedulerJobNamespaceLister.
type SchedulerJobNamespaceListerExpansion interface{}

// TasksQueueListerExpansion allows custom methods to be added to
// TasksQueueLister.
type TasksQueueListerExpansion interface{}

// TasksQueueNamespaceListerExpansion allows custom methods to be added to
// TasksQueueNamespaceLister.
type TasksQueueNamespaceListerExpansion interface{}
