/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-google-api/apis/notebooks/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRuntimeIamBindings implements RuntimeIamBindingInterface
type FakeRuntimeIamBindings struct {
	Fake *FakeNotebooksV1alpha1
	ns   string
}

var runtimeiambindingsResource = schema.GroupVersionResource{Group: "notebooks.google.kubeform.com", Version: "v1alpha1", Resource: "runtimeiambindings"}

var runtimeiambindingsKind = schema.GroupVersionKind{Group: "notebooks.google.kubeform.com", Version: "v1alpha1", Kind: "RuntimeIamBinding"}

// Get takes name of the runtimeIamBinding, and returns the corresponding runtimeIamBinding object, and an error if there is any.
func (c *FakeRuntimeIamBindings) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.RuntimeIamBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(runtimeiambindingsResource, c.ns, name), &v1alpha1.RuntimeIamBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RuntimeIamBinding), err
}

// List takes label and field selectors, and returns the list of RuntimeIamBindings that match those selectors.
func (c *FakeRuntimeIamBindings) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RuntimeIamBindingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(runtimeiambindingsResource, runtimeiambindingsKind, c.ns, opts), &v1alpha1.RuntimeIamBindingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RuntimeIamBindingList{ListMeta: obj.(*v1alpha1.RuntimeIamBindingList).ListMeta}
	for _, item := range obj.(*v1alpha1.RuntimeIamBindingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested runtimeIamBindings.
func (c *FakeRuntimeIamBindings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(runtimeiambindingsResource, c.ns, opts))

}

// Create takes the representation of a runtimeIamBinding and creates it.  Returns the server's representation of the runtimeIamBinding, and an error, if there is any.
func (c *FakeRuntimeIamBindings) Create(ctx context.Context, runtimeIamBinding *v1alpha1.RuntimeIamBinding, opts v1.CreateOptions) (result *v1alpha1.RuntimeIamBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(runtimeiambindingsResource, c.ns, runtimeIamBinding), &v1alpha1.RuntimeIamBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RuntimeIamBinding), err
}

// Update takes the representation of a runtimeIamBinding and updates it. Returns the server's representation of the runtimeIamBinding, and an error, if there is any.
func (c *FakeRuntimeIamBindings) Update(ctx context.Context, runtimeIamBinding *v1alpha1.RuntimeIamBinding, opts v1.UpdateOptions) (result *v1alpha1.RuntimeIamBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(runtimeiambindingsResource, c.ns, runtimeIamBinding), &v1alpha1.RuntimeIamBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RuntimeIamBinding), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRuntimeIamBindings) UpdateStatus(ctx context.Context, runtimeIamBinding *v1alpha1.RuntimeIamBinding, opts v1.UpdateOptions) (*v1alpha1.RuntimeIamBinding, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(runtimeiambindingsResource, "status", c.ns, runtimeIamBinding), &v1alpha1.RuntimeIamBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RuntimeIamBinding), err
}

// Delete takes name of the runtimeIamBinding and deletes it. Returns an error if one occurs.
func (c *FakeRuntimeIamBindings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(runtimeiambindingsResource, c.ns, name), &v1alpha1.RuntimeIamBinding{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRuntimeIamBindings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(runtimeiambindingsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.RuntimeIamBindingList{})
	return err
}

// Patch applies the patch and returns the patched runtimeIamBinding.
func (c *FakeRuntimeIamBindings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RuntimeIamBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(runtimeiambindingsResource, c.ns, name, pt, data, subresources...), &v1alpha1.RuntimeIamBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RuntimeIamBinding), err
}
