/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubeform.dev/provider-google-api/apis/compute/v1alpha1"
)

// FakeGlobalNetworkEndpointGroups implements GlobalNetworkEndpointGroupInterface
type FakeGlobalNetworkEndpointGroups struct {
	Fake *FakeComputeV1alpha1
	ns   string
}

var globalnetworkendpointgroupsResource = schema.GroupVersionResource{Group: "compute.google.kubeform.com", Version: "v1alpha1", Resource: "globalnetworkendpointgroups"}

var globalnetworkendpointgroupsKind = schema.GroupVersionKind{Group: "compute.google.kubeform.com", Version: "v1alpha1", Kind: "GlobalNetworkEndpointGroup"}

// Get takes name of the globalNetworkEndpointGroup, and returns the corresponding globalNetworkEndpointGroup object, and an error if there is any.
func (c *FakeGlobalNetworkEndpointGroups) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GlobalNetworkEndpointGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(globalnetworkendpointgroupsResource, c.ns, name), &v1alpha1.GlobalNetworkEndpointGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GlobalNetworkEndpointGroup), err
}

// List takes label and field selectors, and returns the list of GlobalNetworkEndpointGroups that match those selectors.
func (c *FakeGlobalNetworkEndpointGroups) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GlobalNetworkEndpointGroupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(globalnetworkendpointgroupsResource, globalnetworkendpointgroupsKind, c.ns, opts), &v1alpha1.GlobalNetworkEndpointGroupList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.GlobalNetworkEndpointGroupList{ListMeta: obj.(*v1alpha1.GlobalNetworkEndpointGroupList).ListMeta}
	for _, item := range obj.(*v1alpha1.GlobalNetworkEndpointGroupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested globalNetworkEndpointGroups.
func (c *FakeGlobalNetworkEndpointGroups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(globalnetworkendpointgroupsResource, c.ns, opts))

}

// Create takes the representation of a globalNetworkEndpointGroup and creates it.  Returns the server's representation of the globalNetworkEndpointGroup, and an error, if there is any.
func (c *FakeGlobalNetworkEndpointGroups) Create(ctx context.Context, globalNetworkEndpointGroup *v1alpha1.GlobalNetworkEndpointGroup, opts v1.CreateOptions) (result *v1alpha1.GlobalNetworkEndpointGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(globalnetworkendpointgroupsResource, c.ns, globalNetworkEndpointGroup), &v1alpha1.GlobalNetworkEndpointGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GlobalNetworkEndpointGroup), err
}

// Update takes the representation of a globalNetworkEndpointGroup and updates it. Returns the server's representation of the globalNetworkEndpointGroup, and an error, if there is any.
func (c *FakeGlobalNetworkEndpointGroups) Update(ctx context.Context, globalNetworkEndpointGroup *v1alpha1.GlobalNetworkEndpointGroup, opts v1.UpdateOptions) (result *v1alpha1.GlobalNetworkEndpointGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(globalnetworkendpointgroupsResource, c.ns, globalNetworkEndpointGroup), &v1alpha1.GlobalNetworkEndpointGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GlobalNetworkEndpointGroup), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeGlobalNetworkEndpointGroups) UpdateStatus(ctx context.Context, globalNetworkEndpointGroup *v1alpha1.GlobalNetworkEndpointGroup, opts v1.UpdateOptions) (*v1alpha1.GlobalNetworkEndpointGroup, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(globalnetworkendpointgroupsResource, "status", c.ns, globalNetworkEndpointGroup), &v1alpha1.GlobalNetworkEndpointGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GlobalNetworkEndpointGroup), err
}

// Delete takes name of the globalNetworkEndpointGroup and deletes it. Returns an error if one occurs.
func (c *FakeGlobalNetworkEndpointGroups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(globalnetworkendpointgroupsResource, c.ns, name), &v1alpha1.GlobalNetworkEndpointGroup{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGlobalNetworkEndpointGroups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(globalnetworkendpointgroupsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.GlobalNetworkEndpointGroupList{})
	return err
}

// Patch applies the patch and returns the patched globalNetworkEndpointGroup.
func (c *FakeGlobalNetworkEndpointGroups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GlobalNetworkEndpointGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(globalnetworkendpointgroupsResource, c.ns, name, pt, data, subresources...), &v1alpha1.GlobalNetworkEndpointGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GlobalNetworkEndpointGroup), err
}
