/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubeform.dev/provider-google-api/apis/compute/v1alpha1"
)

// FakeRegionDiskIamBindings implements RegionDiskIamBindingInterface
type FakeRegionDiskIamBindings struct {
	Fake *FakeComputeV1alpha1
	ns   string
}

var regiondiskiambindingsResource = schema.GroupVersionResource{Group: "compute.google.kubeform.com", Version: "v1alpha1", Resource: "regiondiskiambindings"}

var regiondiskiambindingsKind = schema.GroupVersionKind{Group: "compute.google.kubeform.com", Version: "v1alpha1", Kind: "RegionDiskIamBinding"}

// Get takes name of the regionDiskIamBinding, and returns the corresponding regionDiskIamBinding object, and an error if there is any.
func (c *FakeRegionDiskIamBindings) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.RegionDiskIamBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(regiondiskiambindingsResource, c.ns, name), &v1alpha1.RegionDiskIamBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RegionDiskIamBinding), err
}

// List takes label and field selectors, and returns the list of RegionDiskIamBindings that match those selectors.
func (c *FakeRegionDiskIamBindings) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RegionDiskIamBindingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(regiondiskiambindingsResource, regiondiskiambindingsKind, c.ns, opts), &v1alpha1.RegionDiskIamBindingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RegionDiskIamBindingList{ListMeta: obj.(*v1alpha1.RegionDiskIamBindingList).ListMeta}
	for _, item := range obj.(*v1alpha1.RegionDiskIamBindingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested regionDiskIamBindings.
func (c *FakeRegionDiskIamBindings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(regiondiskiambindingsResource, c.ns, opts))

}

// Create takes the representation of a regionDiskIamBinding and creates it.  Returns the server's representation of the regionDiskIamBinding, and an error, if there is any.
func (c *FakeRegionDiskIamBindings) Create(ctx context.Context, regionDiskIamBinding *v1alpha1.RegionDiskIamBinding, opts v1.CreateOptions) (result *v1alpha1.RegionDiskIamBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(regiondiskiambindingsResource, c.ns, regionDiskIamBinding), &v1alpha1.RegionDiskIamBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RegionDiskIamBinding), err
}

// Update takes the representation of a regionDiskIamBinding and updates it. Returns the server's representation of the regionDiskIamBinding, and an error, if there is any.
func (c *FakeRegionDiskIamBindings) Update(ctx context.Context, regionDiskIamBinding *v1alpha1.RegionDiskIamBinding, opts v1.UpdateOptions) (result *v1alpha1.RegionDiskIamBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(regiondiskiambindingsResource, c.ns, regionDiskIamBinding), &v1alpha1.RegionDiskIamBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RegionDiskIamBinding), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRegionDiskIamBindings) UpdateStatus(ctx context.Context, regionDiskIamBinding *v1alpha1.RegionDiskIamBinding, opts v1.UpdateOptions) (*v1alpha1.RegionDiskIamBinding, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(regiondiskiambindingsResource, "status", c.ns, regionDiskIamBinding), &v1alpha1.RegionDiskIamBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RegionDiskIamBinding), err
}

// Delete takes name of the regionDiskIamBinding and deletes it. Returns an error if one occurs.
func (c *FakeRegionDiskIamBindings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(regiondiskiambindingsResource, c.ns, name), &v1alpha1.RegionDiskIamBinding{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRegionDiskIamBindings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(regiondiskiambindingsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.RegionDiskIamBindingList{})
	return err
}

// Patch applies the patch and returns the patched regionDiskIamBinding.
func (c *FakeRegionDiskIamBindings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RegionDiskIamBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(regiondiskiambindingsResource, c.ns, name, pt, data, subresources...), &v1alpha1.RegionDiskIamBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RegionDiskIamBinding), err
}
