/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubeform.dev/provider-google-api/apis/compute/v1alpha1"
)

// FakeProjectDefaultNetworkTiers implements ProjectDefaultNetworkTierInterface
type FakeProjectDefaultNetworkTiers struct {
	Fake *FakeComputeV1alpha1
	ns   string
}

var projectdefaultnetworktiersResource = schema.GroupVersionResource{Group: "compute.google.kubeform.com", Version: "v1alpha1", Resource: "projectdefaultnetworktiers"}

var projectdefaultnetworktiersKind = schema.GroupVersionKind{Group: "compute.google.kubeform.com", Version: "v1alpha1", Kind: "ProjectDefaultNetworkTier"}

// Get takes name of the projectDefaultNetworkTier, and returns the corresponding projectDefaultNetworkTier object, and an error if there is any.
func (c *FakeProjectDefaultNetworkTiers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ProjectDefaultNetworkTier, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(projectdefaultnetworktiersResource, c.ns, name), &v1alpha1.ProjectDefaultNetworkTier{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectDefaultNetworkTier), err
}

// List takes label and field selectors, and returns the list of ProjectDefaultNetworkTiers that match those selectors.
func (c *FakeProjectDefaultNetworkTiers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ProjectDefaultNetworkTierList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(projectdefaultnetworktiersResource, projectdefaultnetworktiersKind, c.ns, opts), &v1alpha1.ProjectDefaultNetworkTierList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ProjectDefaultNetworkTierList{ListMeta: obj.(*v1alpha1.ProjectDefaultNetworkTierList).ListMeta}
	for _, item := range obj.(*v1alpha1.ProjectDefaultNetworkTierList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested projectDefaultNetworkTiers.
func (c *FakeProjectDefaultNetworkTiers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(projectdefaultnetworktiersResource, c.ns, opts))

}

// Create takes the representation of a projectDefaultNetworkTier and creates it.  Returns the server's representation of the projectDefaultNetworkTier, and an error, if there is any.
func (c *FakeProjectDefaultNetworkTiers) Create(ctx context.Context, projectDefaultNetworkTier *v1alpha1.ProjectDefaultNetworkTier, opts v1.CreateOptions) (result *v1alpha1.ProjectDefaultNetworkTier, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(projectdefaultnetworktiersResource, c.ns, projectDefaultNetworkTier), &v1alpha1.ProjectDefaultNetworkTier{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectDefaultNetworkTier), err
}

// Update takes the representation of a projectDefaultNetworkTier and updates it. Returns the server's representation of the projectDefaultNetworkTier, and an error, if there is any.
func (c *FakeProjectDefaultNetworkTiers) Update(ctx context.Context, projectDefaultNetworkTier *v1alpha1.ProjectDefaultNetworkTier, opts v1.UpdateOptions) (result *v1alpha1.ProjectDefaultNetworkTier, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(projectdefaultnetworktiersResource, c.ns, projectDefaultNetworkTier), &v1alpha1.ProjectDefaultNetworkTier{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectDefaultNetworkTier), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeProjectDefaultNetworkTiers) UpdateStatus(ctx context.Context, projectDefaultNetworkTier *v1alpha1.ProjectDefaultNetworkTier, opts v1.UpdateOptions) (*v1alpha1.ProjectDefaultNetworkTier, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(projectdefaultnetworktiersResource, "status", c.ns, projectDefaultNetworkTier), &v1alpha1.ProjectDefaultNetworkTier{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectDefaultNetworkTier), err
}

// Delete takes name of the projectDefaultNetworkTier and deletes it. Returns an error if one occurs.
func (c *FakeProjectDefaultNetworkTiers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(projectdefaultnetworktiersResource, c.ns, name), &v1alpha1.ProjectDefaultNetworkTier{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeProjectDefaultNetworkTiers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(projectdefaultnetworktiersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ProjectDefaultNetworkTierList{})
	return err
}

// Patch applies the patch and returns the patched projectDefaultNetworkTier.
func (c *FakeProjectDefaultNetworkTiers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ProjectDefaultNetworkTier, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(projectdefaultnetworktiersResource, c.ns, name, pt, data, subresources...), &v1alpha1.ProjectDefaultNetworkTier{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectDefaultNetworkTier), err
}
