/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-google-api/apis/compute/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRegionInstanceGroupManagers implements RegionInstanceGroupManagerInterface
type FakeRegionInstanceGroupManagers struct {
	Fake *FakeComputeV1alpha1
	ns   string
}

var regioninstancegroupmanagersResource = schema.GroupVersionResource{Group: "compute.google.kubeform.com", Version: "v1alpha1", Resource: "regioninstancegroupmanagers"}

var regioninstancegroupmanagersKind = schema.GroupVersionKind{Group: "compute.google.kubeform.com", Version: "v1alpha1", Kind: "RegionInstanceGroupManager"}

// Get takes name of the regionInstanceGroupManager, and returns the corresponding regionInstanceGroupManager object, and an error if there is any.
func (c *FakeRegionInstanceGroupManagers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.RegionInstanceGroupManager, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(regioninstancegroupmanagersResource, c.ns, name), &v1alpha1.RegionInstanceGroupManager{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RegionInstanceGroupManager), err
}

// List takes label and field selectors, and returns the list of RegionInstanceGroupManagers that match those selectors.
func (c *FakeRegionInstanceGroupManagers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RegionInstanceGroupManagerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(regioninstancegroupmanagersResource, regioninstancegroupmanagersKind, c.ns, opts), &v1alpha1.RegionInstanceGroupManagerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RegionInstanceGroupManagerList{ListMeta: obj.(*v1alpha1.RegionInstanceGroupManagerList).ListMeta}
	for _, item := range obj.(*v1alpha1.RegionInstanceGroupManagerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested regionInstanceGroupManagers.
func (c *FakeRegionInstanceGroupManagers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(regioninstancegroupmanagersResource, c.ns, opts))

}

// Create takes the representation of a regionInstanceGroupManager and creates it.  Returns the server's representation of the regionInstanceGroupManager, and an error, if there is any.
func (c *FakeRegionInstanceGroupManagers) Create(ctx context.Context, regionInstanceGroupManager *v1alpha1.RegionInstanceGroupManager, opts v1.CreateOptions) (result *v1alpha1.RegionInstanceGroupManager, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(regioninstancegroupmanagersResource, c.ns, regionInstanceGroupManager), &v1alpha1.RegionInstanceGroupManager{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RegionInstanceGroupManager), err
}

// Update takes the representation of a regionInstanceGroupManager and updates it. Returns the server's representation of the regionInstanceGroupManager, and an error, if there is any.
func (c *FakeRegionInstanceGroupManagers) Update(ctx context.Context, regionInstanceGroupManager *v1alpha1.RegionInstanceGroupManager, opts v1.UpdateOptions) (result *v1alpha1.RegionInstanceGroupManager, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(regioninstancegroupmanagersResource, c.ns, regionInstanceGroupManager), &v1alpha1.RegionInstanceGroupManager{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RegionInstanceGroupManager), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRegionInstanceGroupManagers) UpdateStatus(ctx context.Context, regionInstanceGroupManager *v1alpha1.RegionInstanceGroupManager, opts v1.UpdateOptions) (*v1alpha1.RegionInstanceGroupManager, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(regioninstancegroupmanagersResource, "status", c.ns, regionInstanceGroupManager), &v1alpha1.RegionInstanceGroupManager{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RegionInstanceGroupManager), err
}

// Delete takes name of the regionInstanceGroupManager and deletes it. Returns an error if one occurs.
func (c *FakeRegionInstanceGroupManagers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(regioninstancegroupmanagersResource, c.ns, name), &v1alpha1.RegionInstanceGroupManager{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRegionInstanceGroupManagers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(regioninstancegroupmanagersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.RegionInstanceGroupManagerList{})
	return err
}

// Patch applies the patch and returns the patched regionInstanceGroupManager.
func (c *FakeRegionInstanceGroupManagers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RegionInstanceGroupManager, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(regioninstancegroupmanagersResource, c.ns, name, pt, data, subresources...), &v1alpha1.RegionInstanceGroupManager{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RegionInstanceGroupManager), err
}
