/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubeform.dev/provider-google-api/apis/compute/v1alpha1"
)

// FakeSharedVpcServiceProjects implements SharedVpcServiceProjectInterface
type FakeSharedVpcServiceProjects struct {
	Fake *FakeComputeV1alpha1
	ns   string
}

var sharedvpcserviceprojectsResource = schema.GroupVersionResource{Group: "compute.google.kubeform.com", Version: "v1alpha1", Resource: "sharedvpcserviceprojects"}

var sharedvpcserviceprojectsKind = schema.GroupVersionKind{Group: "compute.google.kubeform.com", Version: "v1alpha1", Kind: "SharedVpcServiceProject"}

// Get takes name of the sharedVpcServiceProject, and returns the corresponding sharedVpcServiceProject object, and an error if there is any.
func (c *FakeSharedVpcServiceProjects) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SharedVpcServiceProject, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(sharedvpcserviceprojectsResource, c.ns, name), &v1alpha1.SharedVpcServiceProject{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SharedVpcServiceProject), err
}

// List takes label and field selectors, and returns the list of SharedVpcServiceProjects that match those selectors.
func (c *FakeSharedVpcServiceProjects) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SharedVpcServiceProjectList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(sharedvpcserviceprojectsResource, sharedvpcserviceprojectsKind, c.ns, opts), &v1alpha1.SharedVpcServiceProjectList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SharedVpcServiceProjectList{ListMeta: obj.(*v1alpha1.SharedVpcServiceProjectList).ListMeta}
	for _, item := range obj.(*v1alpha1.SharedVpcServiceProjectList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sharedVpcServiceProjects.
func (c *FakeSharedVpcServiceProjects) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(sharedvpcserviceprojectsResource, c.ns, opts))

}

// Create takes the representation of a sharedVpcServiceProject and creates it.  Returns the server's representation of the sharedVpcServiceProject, and an error, if there is any.
func (c *FakeSharedVpcServiceProjects) Create(ctx context.Context, sharedVpcServiceProject *v1alpha1.SharedVpcServiceProject, opts v1.CreateOptions) (result *v1alpha1.SharedVpcServiceProject, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(sharedvpcserviceprojectsResource, c.ns, sharedVpcServiceProject), &v1alpha1.SharedVpcServiceProject{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SharedVpcServiceProject), err
}

// Update takes the representation of a sharedVpcServiceProject and updates it. Returns the server's representation of the sharedVpcServiceProject, and an error, if there is any.
func (c *FakeSharedVpcServiceProjects) Update(ctx context.Context, sharedVpcServiceProject *v1alpha1.SharedVpcServiceProject, opts v1.UpdateOptions) (result *v1alpha1.SharedVpcServiceProject, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(sharedvpcserviceprojectsResource, c.ns, sharedVpcServiceProject), &v1alpha1.SharedVpcServiceProject{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SharedVpcServiceProject), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSharedVpcServiceProjects) UpdateStatus(ctx context.Context, sharedVpcServiceProject *v1alpha1.SharedVpcServiceProject, opts v1.UpdateOptions) (*v1alpha1.SharedVpcServiceProject, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(sharedvpcserviceprojectsResource, "status", c.ns, sharedVpcServiceProject), &v1alpha1.SharedVpcServiceProject{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SharedVpcServiceProject), err
}

// Delete takes name of the sharedVpcServiceProject and deletes it. Returns an error if one occurs.
func (c *FakeSharedVpcServiceProjects) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(sharedvpcserviceprojectsResource, c.ns, name), &v1alpha1.SharedVpcServiceProject{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSharedVpcServiceProjects) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(sharedvpcserviceprojectsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.SharedVpcServiceProjectList{})
	return err
}

// Patch applies the patch and returns the patched sharedVpcServiceProject.
func (c *FakeSharedVpcServiceProjects) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SharedVpcServiceProject, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(sharedvpcserviceprojectsResource, c.ns, name, pt, data, subresources...), &v1alpha1.SharedVpcServiceProject{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SharedVpcServiceProject), err
}
