/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "kubeform.dev/provider-google-api/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// ConsentStores returns a ConsentStoreInformer.
	ConsentStores() ConsentStoreInformer
	// ConsentStoreIamBindings returns a ConsentStoreIamBindingInformer.
	ConsentStoreIamBindings() ConsentStoreIamBindingInformer
	// ConsentStoreIamMembers returns a ConsentStoreIamMemberInformer.
	ConsentStoreIamMembers() ConsentStoreIamMemberInformer
	// ConsentStoreIamPolicies returns a ConsentStoreIamPolicyInformer.
	ConsentStoreIamPolicies() ConsentStoreIamPolicyInformer
	// Datasets returns a DatasetInformer.
	Datasets() DatasetInformer
	// DatasetIamBindings returns a DatasetIamBindingInformer.
	DatasetIamBindings() DatasetIamBindingInformer
	// DatasetIamMembers returns a DatasetIamMemberInformer.
	DatasetIamMembers() DatasetIamMemberInformer
	// DatasetIamPolicies returns a DatasetIamPolicyInformer.
	DatasetIamPolicies() DatasetIamPolicyInformer
	// DicomStores returns a DicomStoreInformer.
	DicomStores() DicomStoreInformer
	// DicomStoreIamBindings returns a DicomStoreIamBindingInformer.
	DicomStoreIamBindings() DicomStoreIamBindingInformer
	// DicomStoreIamMembers returns a DicomStoreIamMemberInformer.
	DicomStoreIamMembers() DicomStoreIamMemberInformer
	// DicomStoreIamPolicies returns a DicomStoreIamPolicyInformer.
	DicomStoreIamPolicies() DicomStoreIamPolicyInformer
	// FhirStores returns a FhirStoreInformer.
	FhirStores() FhirStoreInformer
	// FhirStoreIamBindings returns a FhirStoreIamBindingInformer.
	FhirStoreIamBindings() FhirStoreIamBindingInformer
	// FhirStoreIamMembers returns a FhirStoreIamMemberInformer.
	FhirStoreIamMembers() FhirStoreIamMemberInformer
	// FhirStoreIamPolicies returns a FhirStoreIamPolicyInformer.
	FhirStoreIamPolicies() FhirStoreIamPolicyInformer
	// Hl7V2Stores returns a Hl7V2StoreInformer.
	Hl7V2Stores() Hl7V2StoreInformer
	// Hl7V2StoreIamBindings returns a Hl7V2StoreIamBindingInformer.
	Hl7V2StoreIamBindings() Hl7V2StoreIamBindingInformer
	// Hl7V2StoreIamMembers returns a Hl7V2StoreIamMemberInformer.
	Hl7V2StoreIamMembers() Hl7V2StoreIamMemberInformer
	// Hl7V2StoreIamPolicies returns a Hl7V2StoreIamPolicyInformer.
	Hl7V2StoreIamPolicies() Hl7V2StoreIamPolicyInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// ConsentStores returns a ConsentStoreInformer.
func (v *version) ConsentStores() ConsentStoreInformer {
	return &consentStoreInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ConsentStoreIamBindings returns a ConsentStoreIamBindingInformer.
func (v *version) ConsentStoreIamBindings() ConsentStoreIamBindingInformer {
	return &consentStoreIamBindingInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ConsentStoreIamMembers returns a ConsentStoreIamMemberInformer.
func (v *version) ConsentStoreIamMembers() ConsentStoreIamMemberInformer {
	return &consentStoreIamMemberInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ConsentStoreIamPolicies returns a ConsentStoreIamPolicyInformer.
func (v *version) ConsentStoreIamPolicies() ConsentStoreIamPolicyInformer {
	return &consentStoreIamPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Datasets returns a DatasetInformer.
func (v *version) Datasets() DatasetInformer {
	return &datasetInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// DatasetIamBindings returns a DatasetIamBindingInformer.
func (v *version) DatasetIamBindings() DatasetIamBindingInformer {
	return &datasetIamBindingInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// DatasetIamMembers returns a DatasetIamMemberInformer.
func (v *version) DatasetIamMembers() DatasetIamMemberInformer {
	return &datasetIamMemberInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// DatasetIamPolicies returns a DatasetIamPolicyInformer.
func (v *version) DatasetIamPolicies() DatasetIamPolicyInformer {
	return &datasetIamPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// DicomStores returns a DicomStoreInformer.
func (v *version) DicomStores() DicomStoreInformer {
	return &dicomStoreInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// DicomStoreIamBindings returns a DicomStoreIamBindingInformer.
func (v *version) DicomStoreIamBindings() DicomStoreIamBindingInformer {
	return &dicomStoreIamBindingInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// DicomStoreIamMembers returns a DicomStoreIamMemberInformer.
func (v *version) DicomStoreIamMembers() DicomStoreIamMemberInformer {
	return &dicomStoreIamMemberInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// DicomStoreIamPolicies returns a DicomStoreIamPolicyInformer.
func (v *version) DicomStoreIamPolicies() DicomStoreIamPolicyInformer {
	return &dicomStoreIamPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// FhirStores returns a FhirStoreInformer.
func (v *version) FhirStores() FhirStoreInformer {
	return &fhirStoreInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// FhirStoreIamBindings returns a FhirStoreIamBindingInformer.
func (v *version) FhirStoreIamBindings() FhirStoreIamBindingInformer {
	return &fhirStoreIamBindingInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// FhirStoreIamMembers returns a FhirStoreIamMemberInformer.
func (v *version) FhirStoreIamMembers() FhirStoreIamMemberInformer {
	return &fhirStoreIamMemberInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// FhirStoreIamPolicies returns a FhirStoreIamPolicyInformer.
func (v *version) FhirStoreIamPolicies() FhirStoreIamPolicyInformer {
	return &fhirStoreIamPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Hl7V2Stores returns a Hl7V2StoreInformer.
func (v *version) Hl7V2Stores() Hl7V2StoreInformer {
	return &hl7V2StoreInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Hl7V2StoreIamBindings returns a Hl7V2StoreIamBindingInformer.
func (v *version) Hl7V2StoreIamBindings() Hl7V2StoreIamBindingInformer {
	return &hl7V2StoreIamBindingInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Hl7V2StoreIamMembers returns a Hl7V2StoreIamMemberInformer.
func (v *version) Hl7V2StoreIamMembers() Hl7V2StoreIamMemberInformer {
	return &hl7V2StoreIamMemberInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Hl7V2StoreIamPolicies returns a Hl7V2StoreIamPolicyInformer.
func (v *version) Hl7V2StoreIamPolicies() Hl7V2StoreIamPolicyInformer {
	return &hl7V2StoreIamPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
