/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AlertPolicyListerExpansion allows custom methods to be added to
// AlertPolicyLister.
type AlertPolicyListerExpansion interface{}

// AlertPolicyNamespaceListerExpansion allows custom methods to be added to
// AlertPolicyNamespaceLister.
type AlertPolicyNamespaceListerExpansion interface{}

// CustomServiceListerExpansion allows custom methods to be added to
// CustomServiceLister.
type CustomServiceListerExpansion interface{}

// CustomServiceNamespaceListerExpansion allows custom methods to be added to
// CustomServiceNamespaceLister.
type CustomServiceNamespaceListerExpansion interface{}

// DashboardListerExpansion allows custom methods to be added to
// DashboardLister.
type DashboardListerExpansion interface{}

// DashboardNamespaceListerExpansion allows custom methods to be added to
// DashboardNamespaceLister.
type DashboardNamespaceListerExpansion interface{}

// GroupListerExpansion allows custom methods to be added to
// GroupLister.
type GroupListerExpansion interface{}

// GroupNamespaceListerExpansion allows custom methods to be added to
// GroupNamespaceLister.
type GroupNamespaceListerExpansion interface{}

// MetricDescriptorListerExpansion allows custom methods to be added to
// MetricDescriptorLister.
type MetricDescriptorListerExpansion interface{}

// MetricDescriptorNamespaceListerExpansion allows custom methods to be added to
// MetricDescriptorNamespaceLister.
type MetricDescriptorNamespaceListerExpansion interface{}

// NotificationChannelListerExpansion allows custom methods to be added to
// NotificationChannelLister.
type NotificationChannelListerExpansion interface{}

// NotificationChannelNamespaceListerExpansion allows custom methods to be added to
// NotificationChannelNamespaceLister.
type NotificationChannelNamespaceListerExpansion interface{}

// SloListerExpansion allows custom methods to be added to
// SloLister.
type SloListerExpansion interface{}

// SloNamespaceListerExpansion allows custom methods to be added to
// SloNamespaceLister.
type SloNamespaceListerExpansion interface{}

// UptimeCheckConfigListerExpansion allows custom methods to be added to
// UptimeCheckConfigLister.
type UptimeCheckConfigListerExpansion interface{}

// UptimeCheckConfigNamespaceListerExpansion allows custom methods to be added to
// UptimeCheckConfigNamespaceLister.
type UptimeCheckConfigNamespaceListerExpansion interface{}
