/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	projectv1alpha1 "kubeform.dev/provider-google-api/apis/project/v1alpha1"
	versioned "kubeform.dev/provider-google-api/client/clientset/versioned"
	internalinterfaces "kubeform.dev/provider-google-api/client/informers/externalversions/internalinterfaces"
	v1alpha1 "kubeform.dev/provider-google-api/client/listers/project/v1alpha1"
)

// IamAuditConfigInformer provides access to a shared informer and lister for
// IamAuditConfigs.
type IamAuditConfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.IamAuditConfigLister
}

type iamAuditConfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewIamAuditConfigInformer constructs a new informer for IamAuditConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewIamAuditConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredIamAuditConfigInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredIamAuditConfigInformer constructs a new informer for IamAuditConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredIamAuditConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ProjectV1alpha1().IamAuditConfigs(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ProjectV1alpha1().IamAuditConfigs(namespace).Watch(context.TODO(), options)
			},
		},
		&projectv1alpha1.IamAuditConfig{},
		resyncPeriod,
		indexers,
	)
}

func (f *iamAuditConfigInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredIamAuditConfigInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *iamAuditConfigInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&projectv1alpha1.IamAuditConfig{}, f.defaultInformer)
}

func (f *iamAuditConfigInformer) Lister() v1alpha1.IamAuditConfigLister {
	return v1alpha1.NewIamAuditConfigLister(f.Informer().GetIndexer())
}
