/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-google-api/apis/healthcare/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeConsentStoreIamMembers implements ConsentStoreIamMemberInterface
type FakeConsentStoreIamMembers struct {
	Fake *FakeHealthcareV1alpha1
	ns   string
}

var consentstoreiammembersResource = schema.GroupVersionResource{Group: "healthcare.google.kubeform.com", Version: "v1alpha1", Resource: "consentstoreiammembers"}

var consentstoreiammembersKind = schema.GroupVersionKind{Group: "healthcare.google.kubeform.com", Version: "v1alpha1", Kind: "ConsentStoreIamMember"}

// Get takes name of the consentStoreIamMember, and returns the corresponding consentStoreIamMember object, and an error if there is any.
func (c *FakeConsentStoreIamMembers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ConsentStoreIamMember, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(consentstoreiammembersResource, c.ns, name), &v1alpha1.ConsentStoreIamMember{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConsentStoreIamMember), err
}

// List takes label and field selectors, and returns the list of ConsentStoreIamMembers that match those selectors.
func (c *FakeConsentStoreIamMembers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ConsentStoreIamMemberList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(consentstoreiammembersResource, consentstoreiammembersKind, c.ns, opts), &v1alpha1.ConsentStoreIamMemberList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ConsentStoreIamMemberList{ListMeta: obj.(*v1alpha1.ConsentStoreIamMemberList).ListMeta}
	for _, item := range obj.(*v1alpha1.ConsentStoreIamMemberList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested consentStoreIamMembers.
func (c *FakeConsentStoreIamMembers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(consentstoreiammembersResource, c.ns, opts))

}

// Create takes the representation of a consentStoreIamMember and creates it.  Returns the server's representation of the consentStoreIamMember, and an error, if there is any.
func (c *FakeConsentStoreIamMembers) Create(ctx context.Context, consentStoreIamMember *v1alpha1.ConsentStoreIamMember, opts v1.CreateOptions) (result *v1alpha1.ConsentStoreIamMember, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(consentstoreiammembersResource, c.ns, consentStoreIamMember), &v1alpha1.ConsentStoreIamMember{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConsentStoreIamMember), err
}

// Update takes the representation of a consentStoreIamMember and updates it. Returns the server's representation of the consentStoreIamMember, and an error, if there is any.
func (c *FakeConsentStoreIamMembers) Update(ctx context.Context, consentStoreIamMember *v1alpha1.ConsentStoreIamMember, opts v1.UpdateOptions) (result *v1alpha1.ConsentStoreIamMember, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(consentstoreiammembersResource, c.ns, consentStoreIamMember), &v1alpha1.ConsentStoreIamMember{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConsentStoreIamMember), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeConsentStoreIamMembers) UpdateStatus(ctx context.Context, consentStoreIamMember *v1alpha1.ConsentStoreIamMember, opts v1.UpdateOptions) (*v1alpha1.ConsentStoreIamMember, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(consentstoreiammembersResource, "status", c.ns, consentStoreIamMember), &v1alpha1.ConsentStoreIamMember{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConsentStoreIamMember), err
}

// Delete takes name of the consentStoreIamMember and deletes it. Returns an error if one occurs.
func (c *FakeConsentStoreIamMembers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(consentstoreiammembersResource, c.ns, name), &v1alpha1.ConsentStoreIamMember{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeConsentStoreIamMembers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(consentstoreiammembersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ConsentStoreIamMemberList{})
	return err
}

// Patch applies the patch and returns the patched consentStoreIamMember.
func (c *FakeConsentStoreIamMembers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ConsentStoreIamMember, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(consentstoreiammembersResource, c.ns, name, pt, data, subresources...), &v1alpha1.ConsentStoreIamMember{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConsentStoreIamMember), err
}
