/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	kmsv1alpha1 "kubeform.dev/provider-google-api/apis/kms/v1alpha1"
	versioned "kubeform.dev/provider-google-api/client/clientset/versioned"
	internalinterfaces "kubeform.dev/provider-google-api/client/informers/externalversions/internalinterfaces"
	v1alpha1 "kubeform.dev/provider-google-api/client/listers/kms/v1alpha1"
)

// CryptoKeyIamMemberInformer provides access to a shared informer and lister for
// CryptoKeyIamMembers.
type CryptoKeyIamMemberInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.CryptoKeyIamMemberLister
}

type cryptoKeyIamMemberInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCryptoKeyIamMemberInformer constructs a new informer for CryptoKeyIamMember type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCryptoKeyIamMemberInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCryptoKeyIamMemberInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCryptoKeyIamMemberInformer constructs a new informer for CryptoKeyIamMember type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCryptoKeyIamMemberInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KmsV1alpha1().CryptoKeyIamMembers(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KmsV1alpha1().CryptoKeyIamMembers(namespace).Watch(context.TODO(), options)
			},
		},
		&kmsv1alpha1.CryptoKeyIamMember{},
		resyncPeriod,
		indexers,
	)
}

func (f *cryptoKeyIamMemberInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCryptoKeyIamMemberInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *cryptoKeyIamMemberInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&kmsv1alpha1.CryptoKeyIamMember{}, f.defaultInformer)
}

func (f *cryptoKeyIamMemberInformer) Lister() v1alpha1.CryptoKeyIamMemberLister {
	return v1alpha1.NewCryptoKeyIamMemberLister(f.Informer().GetIndexer())
}
