/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-google-api/apis/service/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAccountIamBindings implements AccountIamBindingInterface
type FakeAccountIamBindings struct {
	Fake *FakeServiceV1alpha1
	ns   string
}

var accountiambindingsResource = schema.GroupVersionResource{Group: "service.google.kubeform.com", Version: "v1alpha1", Resource: "accountiambindings"}

var accountiambindingsKind = schema.GroupVersionKind{Group: "service.google.kubeform.com", Version: "v1alpha1", Kind: "AccountIamBinding"}

// Get takes name of the accountIamBinding, and returns the corresponding accountIamBinding object, and an error if there is any.
func (c *FakeAccountIamBindings) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AccountIamBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(accountiambindingsResource, c.ns, name), &v1alpha1.AccountIamBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AccountIamBinding), err
}

// List takes label and field selectors, and returns the list of AccountIamBindings that match those selectors.
func (c *FakeAccountIamBindings) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AccountIamBindingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(accountiambindingsResource, accountiambindingsKind, c.ns, opts), &v1alpha1.AccountIamBindingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AccountIamBindingList{ListMeta: obj.(*v1alpha1.AccountIamBindingList).ListMeta}
	for _, item := range obj.(*v1alpha1.AccountIamBindingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested accountIamBindings.
func (c *FakeAccountIamBindings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(accountiambindingsResource, c.ns, opts))

}

// Create takes the representation of a accountIamBinding and creates it.  Returns the server's representation of the accountIamBinding, and an error, if there is any.
func (c *FakeAccountIamBindings) Create(ctx context.Context, accountIamBinding *v1alpha1.AccountIamBinding, opts v1.CreateOptions) (result *v1alpha1.AccountIamBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(accountiambindingsResource, c.ns, accountIamBinding), &v1alpha1.AccountIamBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AccountIamBinding), err
}

// Update takes the representation of a accountIamBinding and updates it. Returns the server's representation of the accountIamBinding, and an error, if there is any.
func (c *FakeAccountIamBindings) Update(ctx context.Context, accountIamBinding *v1alpha1.AccountIamBinding, opts v1.UpdateOptions) (result *v1alpha1.AccountIamBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(accountiambindingsResource, c.ns, accountIamBinding), &v1alpha1.AccountIamBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AccountIamBinding), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAccountIamBindings) UpdateStatus(ctx context.Context, accountIamBinding *v1alpha1.AccountIamBinding, opts v1.UpdateOptions) (*v1alpha1.AccountIamBinding, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(accountiambindingsResource, "status", c.ns, accountIamBinding), &v1alpha1.AccountIamBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AccountIamBinding), err
}

// Delete takes name of the accountIamBinding and deletes it. Returns an error if one occurs.
func (c *FakeAccountIamBindings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(accountiambindingsResource, c.ns, name), &v1alpha1.AccountIamBinding{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAccountIamBindings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(accountiambindingsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.AccountIamBindingList{})
	return err
}

// Patch applies the patch and returns the patched accountIamBinding.
func (c *FakeAccountIamBindings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AccountIamBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(accountiambindingsResource, c.ns, name, pt, data, subresources...), &v1alpha1.AccountIamBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AccountIamBinding), err
}
