/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-google-api/apis/dialogflow/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCxFlows implements CxFlowInterface
type FakeCxFlows struct {
	Fake *FakeDialogflowV1alpha1
	ns   string
}

var cxflowsResource = schema.GroupVersionResource{Group: "dialogflow.google.kubeform.com", Version: "v1alpha1", Resource: "cxflows"}

var cxflowsKind = schema.GroupVersionKind{Group: "dialogflow.google.kubeform.com", Version: "v1alpha1", Kind: "CxFlow"}

// Get takes name of the cxFlow, and returns the corresponding cxFlow object, and an error if there is any.
func (c *FakeCxFlows) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CxFlow, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(cxflowsResource, c.ns, name), &v1alpha1.CxFlow{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CxFlow), err
}

// List takes label and field selectors, and returns the list of CxFlows that match those selectors.
func (c *FakeCxFlows) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CxFlowList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(cxflowsResource, cxflowsKind, c.ns, opts), &v1alpha1.CxFlowList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CxFlowList{ListMeta: obj.(*v1alpha1.CxFlowList).ListMeta}
	for _, item := range obj.(*v1alpha1.CxFlowList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cxFlows.
func (c *FakeCxFlows) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(cxflowsResource, c.ns, opts))

}

// Create takes the representation of a cxFlow and creates it.  Returns the server's representation of the cxFlow, and an error, if there is any.
func (c *FakeCxFlows) Create(ctx context.Context, cxFlow *v1alpha1.CxFlow, opts v1.CreateOptions) (result *v1alpha1.CxFlow, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(cxflowsResource, c.ns, cxFlow), &v1alpha1.CxFlow{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CxFlow), err
}

// Update takes the representation of a cxFlow and updates it. Returns the server's representation of the cxFlow, and an error, if there is any.
func (c *FakeCxFlows) Update(ctx context.Context, cxFlow *v1alpha1.CxFlow, opts v1.UpdateOptions) (result *v1alpha1.CxFlow, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(cxflowsResource, c.ns, cxFlow), &v1alpha1.CxFlow{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CxFlow), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCxFlows) UpdateStatus(ctx context.Context, cxFlow *v1alpha1.CxFlow, opts v1.UpdateOptions) (*v1alpha1.CxFlow, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(cxflowsResource, "status", c.ns, cxFlow), &v1alpha1.CxFlow{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CxFlow), err
}

// Delete takes name of the cxFlow and deletes it. Returns an error if one occurs.
func (c *FakeCxFlows) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(cxflowsResource, c.ns, name), &v1alpha1.CxFlow{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCxFlows) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(cxflowsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CxFlowList{})
	return err
}

// Patch applies the patch and returns the patched cxFlow.
func (c *FakeCxFlows) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CxFlow, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(cxflowsResource, c.ns, name, pt, data, subresources...), &v1alpha1.CxFlow{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CxFlow), err
}
