/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubeform.dev/provider-google-api/apis/iap/v1alpha1"
)

// FakeWebTypeComputeIamPolicies implements WebTypeComputeIamPolicyInterface
type FakeWebTypeComputeIamPolicies struct {
	Fake *FakeIapV1alpha1
	ns   string
}

var webtypecomputeiampoliciesResource = schema.GroupVersionResource{Group: "iap.google.kubeform.com", Version: "v1alpha1", Resource: "webtypecomputeiampolicies"}

var webtypecomputeiampoliciesKind = schema.GroupVersionKind{Group: "iap.google.kubeform.com", Version: "v1alpha1", Kind: "WebTypeComputeIamPolicy"}

// Get takes name of the webTypeComputeIamPolicy, and returns the corresponding webTypeComputeIamPolicy object, and an error if there is any.
func (c *FakeWebTypeComputeIamPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.WebTypeComputeIamPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(webtypecomputeiampoliciesResource, c.ns, name), &v1alpha1.WebTypeComputeIamPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WebTypeComputeIamPolicy), err
}

// List takes label and field selectors, and returns the list of WebTypeComputeIamPolicies that match those selectors.
func (c *FakeWebTypeComputeIamPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.WebTypeComputeIamPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(webtypecomputeiampoliciesResource, webtypecomputeiampoliciesKind, c.ns, opts), &v1alpha1.WebTypeComputeIamPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.WebTypeComputeIamPolicyList{ListMeta: obj.(*v1alpha1.WebTypeComputeIamPolicyList).ListMeta}
	for _, item := range obj.(*v1alpha1.WebTypeComputeIamPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested webTypeComputeIamPolicies.
func (c *FakeWebTypeComputeIamPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(webtypecomputeiampoliciesResource, c.ns, opts))

}

// Create takes the representation of a webTypeComputeIamPolicy and creates it.  Returns the server's representation of the webTypeComputeIamPolicy, and an error, if there is any.
func (c *FakeWebTypeComputeIamPolicies) Create(ctx context.Context, webTypeComputeIamPolicy *v1alpha1.WebTypeComputeIamPolicy, opts v1.CreateOptions) (result *v1alpha1.WebTypeComputeIamPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(webtypecomputeiampoliciesResource, c.ns, webTypeComputeIamPolicy), &v1alpha1.WebTypeComputeIamPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WebTypeComputeIamPolicy), err
}

// Update takes the representation of a webTypeComputeIamPolicy and updates it. Returns the server's representation of the webTypeComputeIamPolicy, and an error, if there is any.
func (c *FakeWebTypeComputeIamPolicies) Update(ctx context.Context, webTypeComputeIamPolicy *v1alpha1.WebTypeComputeIamPolicy, opts v1.UpdateOptions) (result *v1alpha1.WebTypeComputeIamPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(webtypecomputeiampoliciesResource, c.ns, webTypeComputeIamPolicy), &v1alpha1.WebTypeComputeIamPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WebTypeComputeIamPolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeWebTypeComputeIamPolicies) UpdateStatus(ctx context.Context, webTypeComputeIamPolicy *v1alpha1.WebTypeComputeIamPolicy, opts v1.UpdateOptions) (*v1alpha1.WebTypeComputeIamPolicy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(webtypecomputeiampoliciesResource, "status", c.ns, webTypeComputeIamPolicy), &v1alpha1.WebTypeComputeIamPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WebTypeComputeIamPolicy), err
}

// Delete takes name of the webTypeComputeIamPolicy and deletes it. Returns an error if one occurs.
func (c *FakeWebTypeComputeIamPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(webtypecomputeiampoliciesResource, c.ns, name), &v1alpha1.WebTypeComputeIamPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeWebTypeComputeIamPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(webtypecomputeiampoliciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.WebTypeComputeIamPolicyList{})
	return err
}

// Patch applies the patch and returns the patched webTypeComputeIamPolicy.
func (c *FakeWebTypeComputeIamPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.WebTypeComputeIamPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(webtypecomputeiampoliciesResource, c.ns, name, pt, data, subresources...), &v1alpha1.WebTypeComputeIamPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WebTypeComputeIamPolicy), err
}
