/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-google-api/apis/dataproc/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeJobIamBindings implements JobIamBindingInterface
type FakeJobIamBindings struct {
	Fake *FakeDataprocV1alpha1
	ns   string
}

var jobiambindingsResource = schema.GroupVersionResource{Group: "dataproc.google.kubeform.com", Version: "v1alpha1", Resource: "jobiambindings"}

var jobiambindingsKind = schema.GroupVersionKind{Group: "dataproc.google.kubeform.com", Version: "v1alpha1", Kind: "JobIamBinding"}

// Get takes name of the jobIamBinding, and returns the corresponding jobIamBinding object, and an error if there is any.
func (c *FakeJobIamBindings) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.JobIamBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(jobiambindingsResource, c.ns, name), &v1alpha1.JobIamBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JobIamBinding), err
}

// List takes label and field selectors, and returns the list of JobIamBindings that match those selectors.
func (c *FakeJobIamBindings) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.JobIamBindingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(jobiambindingsResource, jobiambindingsKind, c.ns, opts), &v1alpha1.JobIamBindingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.JobIamBindingList{ListMeta: obj.(*v1alpha1.JobIamBindingList).ListMeta}
	for _, item := range obj.(*v1alpha1.JobIamBindingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested jobIamBindings.
func (c *FakeJobIamBindings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(jobiambindingsResource, c.ns, opts))

}

// Create takes the representation of a jobIamBinding and creates it.  Returns the server's representation of the jobIamBinding, and an error, if there is any.
func (c *FakeJobIamBindings) Create(ctx context.Context, jobIamBinding *v1alpha1.JobIamBinding, opts v1.CreateOptions) (result *v1alpha1.JobIamBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(jobiambindingsResource, c.ns, jobIamBinding), &v1alpha1.JobIamBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JobIamBinding), err
}

// Update takes the representation of a jobIamBinding and updates it. Returns the server's representation of the jobIamBinding, and an error, if there is any.
func (c *FakeJobIamBindings) Update(ctx context.Context, jobIamBinding *v1alpha1.JobIamBinding, opts v1.UpdateOptions) (result *v1alpha1.JobIamBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(jobiambindingsResource, c.ns, jobIamBinding), &v1alpha1.JobIamBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JobIamBinding), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeJobIamBindings) UpdateStatus(ctx context.Context, jobIamBinding *v1alpha1.JobIamBinding, opts v1.UpdateOptions) (*v1alpha1.JobIamBinding, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(jobiambindingsResource, "status", c.ns, jobIamBinding), &v1alpha1.JobIamBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JobIamBinding), err
}

// Delete takes name of the jobIamBinding and deletes it. Returns an error if one occurs.
func (c *FakeJobIamBindings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(jobiambindingsResource, c.ns, name), &v1alpha1.JobIamBinding{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeJobIamBindings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(jobiambindingsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.JobIamBindingList{})
	return err
}

// Patch applies the patch and returns the patched jobIamBinding.
func (c *FakeJobIamBindings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.JobIamBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(jobiambindingsResource, c.ns, name, pt, data, subresources...), &v1alpha1.JobIamBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JobIamBinding), err
}
