/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ConfigListerExpansion allows custom methods to be added to
// ConfigLister.
type ConfigListerExpansion interface{}

// ConfigNamespaceListerExpansion allows custom methods to be added to
// ConfigNamespaceLister.
type ConfigNamespaceListerExpansion interface{}

// ConfigIamBindingListerExpansion allows custom methods to be added to
// ConfigIamBindingLister.
type ConfigIamBindingListerExpansion interface{}

// ConfigIamBindingNamespaceListerExpansion allows custom methods to be added to
// ConfigIamBindingNamespaceLister.
type ConfigIamBindingNamespaceListerExpansion interface{}

// ConfigIamMemberListerExpansion allows custom methods to be added to
// ConfigIamMemberLister.
type ConfigIamMemberListerExpansion interface{}

// ConfigIamMemberNamespaceListerExpansion allows custom methods to be added to
// ConfigIamMemberNamespaceLister.
type ConfigIamMemberNamespaceListerExpansion interface{}

// ConfigIamPolicyListerExpansion allows custom methods to be added to
// ConfigIamPolicyLister.
type ConfigIamPolicyListerExpansion interface{}

// ConfigIamPolicyNamespaceListerExpansion allows custom methods to be added to
// ConfigIamPolicyNamespaceLister.
type ConfigIamPolicyNamespaceListerExpansion interface{}

// VariableListerExpansion allows custom methods to be added to
// VariableLister.
type VariableListerExpansion interface{}

// VariableNamespaceListerExpansion allows custom methods to be added to
// VariableNamespaceLister.
type VariableNamespaceListerExpansion interface{}
