apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: google.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: organizations.apigee.google.kubeform.com
spec:
  group: apigee.google.kubeform.com
  names:
    kind: Organization
    listKind: OrganizationList
    plural: organizations
    singular: organization
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  analyticsRegion:
                    description: Primary GCP region for analytics data storage. For
                      valid values, see [Create an Apigee organization](https://cloud.google.com/apigee/docs/api-platform/get-started/create-org).
                    type: string
                  authorizedNetwork:
                    description: 'Compute Engine network used for Service Networking
                      to be peered with Apigee runtime instances. See [Getting started
                      with the Service Networking API](https://cloud.google.com/service-infrastructure/docs/service-networking/getting-started).
                      Valid only when ''RuntimeType'' is set to CLOUD. The value can
                      be updated only when there are no runtime instances. For example:
                      "default".'
                    type: string
                  caCertificate:
                    description: Output only. Base64-encoded public certificate for
                      the root CA of the Apigee organization. Valid only when 'RuntimeType'
                      is CLOUD. A base64-encoded string.
                    type: string
                  description:
                    description: Description of the Apigee organization.
                    type: string
                  displayName:
                    description: The display name of the Apigee organization.
                    type: string
                  id:
                    type: string
                  name:
                    description: Output only. Name of the Apigee organization.
                    type: string
                  projectID:
                    description: The project ID associated with the Apigee organization.
                    type: string
                  runtimeDatabaseEncryptionKeyName:
                    description: 'Cloud KMS key name used for encrypting the data
                      that is stored and replicated across runtime instances. Update
                      is not allowed after the organization is created. If not specified,
                      a Google-Managed encryption key will be used. Valid only when
                      ''RuntimeType'' is CLOUD. For example: ''projects/foo/locations/us/keyRings/bar/cryptoKeys/baz''.'
                    type: string
                  runtimeType:
                    description: 'Runtime type of the Apigee organization based on
                      the Apigee subscription purchased. Default value: "CLOUD" Possible
                      values: ["CLOUD", "HYBRID"]'
                    type: string
                  subscriptionType:
                    description: Output only. Subscription type of the Apigee organization.
                      Valid values include trial (free, limited, and for evaluation
                      purposes only) or paid (full subscription has been purchased).
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                required:
                - projectID
                type: object
              state:
                properties:
                  analyticsRegion:
                    description: Primary GCP region for analytics data storage. For
                      valid values, see [Create an Apigee organization](https://cloud.google.com/apigee/docs/api-platform/get-started/create-org).
                    type: string
                  authorizedNetwork:
                    description: 'Compute Engine network used for Service Networking
                      to be peered with Apigee runtime instances. See [Getting started
                      with the Service Networking API](https://cloud.google.com/service-infrastructure/docs/service-networking/getting-started).
                      Valid only when ''RuntimeType'' is set to CLOUD. The value can
                      be updated only when there are no runtime instances. For example:
                      "default".'
                    type: string
                  caCertificate:
                    description: Output only. Base64-encoded public certificate for
                      the root CA of the Apigee organization. Valid only when 'RuntimeType'
                      is CLOUD. A base64-encoded string.
                    type: string
                  description:
                    description: Description of the Apigee organization.
                    type: string
                  displayName:
                    description: The display name of the Apigee organization.
                    type: string
                  id:
                    type: string
                  name:
                    description: Output only. Name of the Apigee organization.
                    type: string
                  projectID:
                    description: The project ID associated with the Apigee organization.
                    type: string
                  runtimeDatabaseEncryptionKeyName:
                    description: 'Cloud KMS key name used for encrypting the data
                      that is stored and replicated across runtime instances. Update
                      is not allowed after the organization is created. If not specified,
                      a Google-Managed encryption key will be used. Valid only when
                      ''RuntimeType'' is CLOUD. For example: ''projects/foo/locations/us/keyRings/bar/cryptoKeys/baz''.'
                    type: string
                  runtimeType:
                    description: 'Runtime type of the Apigee organization based on
                      the Apigee subscription purchased. Default value: "CLOUD" Possible
                      values: ["CLOUD", "HYBRID"]'
                    type: string
                  subscriptionType:
                    description: Output only. Subscription type of the Apigee organization.
                      Valid values include trial (free, limited, and for evaluation
                      purposes only) or paid (full subscription has been purchased).
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                required:
                - projectID
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
