apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: google.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: domainmappings.appengine.google.kubeform.com
spec:
  group: appengine.google.kubeform.com
  names:
    kind: DomainMapping
    listKind: DomainMappingList
    plural: domainmappings
    singular: domainmapping
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  domainName:
                    description: 'Relative name of the domain serving the application.
                      Example: example.com.'
                    type: string
                  id:
                    type: string
                  name:
                    description: 'Full path to the DomainMapping resource in the API.
                      Example: apps/myapp/domainMapping/example.com.'
                    type: string
                  overrideStrategy:
                    description: 'Whether the domain creation should override any
                      existing mappings for this domain. By default, overrides are
                      rejected. Default value: "STRICT" Possible values: ["STRICT",
                      "OVERRIDE"]'
                    type: string
                  project:
                    type: string
                  resourceRecords:
                    description: The resource records required to configure this domain
                      mapping. These records must be added to the domain's DNS configuration
                      in order to serve the application via this domain mapping.
                    items:
                      properties:
                        name:
                          description: 'Relative name of the object affected by this
                            record. Only applicable for CNAME records. Example: ''www''.'
                          type: string
                        rrdata:
                          description: Data for this record. Values vary by record
                            type, as defined in RFC 1035 (section 5) and RFC 1034
                            (section 3.6.1).
                          type: string
                        type:
                          description: 'Resource record type. Example: ''AAAA''. Possible
                            values: ["A", "AAAA", "CNAME"]'
                          type: string
                      type: object
                    type: array
                  sslSettings:
                    description: SSL configuration for this domain. If unconfigured,
                      this domain will not serve with SSL.
                    properties:
                      certificateID:
                        description: 'ID of the AuthorizedCertificate resource configuring
                          SSL for the application. Clearing this field will remove
                          SSL support. By default, a managed certificate is automatically
                          created for every domain mapping. To omit SSL support or
                          to configure SSL manually, specify ''SslManagementType.MANUAL''
                          on a ''CREATE'' or ''UPDATE'' request. You must be authorized
                          to administer the ''AuthorizedCertificate'' resource to
                          manually map it to a DomainMapping resource. Example: 12345.'
                        type: string
                      pendingManagedCertificateID:
                        description: ID of the managed 'AuthorizedCertificate' resource
                          currently being provisioned, if applicable. Until the new
                          managed certificate has been successfully provisioned, the
                          previous SSL state will be preserved. Once the provisioning
                          process completes, the 'certificateId' field will reflect
                          the new managed certificate and this field will be left
                          empty. To remove SSL support while there is still a pending
                          managed certificate, clear the 'certificateId' field with
                          an update request.
                        type: string
                      sslManagementType:
                        description: 'SSL management type for this domain. If ''AUTOMATIC'',
                          a managed certificate is automatically provisioned. If ''MANUAL'',
                          ''certificateId'' must be manually specified in order to
                          configure SSL for this domain. Possible values: ["AUTOMATIC",
                          "MANUAL"]'
                        type: string
                    required:
                    - sslManagementType
                    type: object
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                required:
                - domainName
                type: object
              state:
                properties:
                  domainName:
                    description: 'Relative name of the domain serving the application.
                      Example: example.com.'
                    type: string
                  id:
                    type: string
                  name:
                    description: 'Full path to the DomainMapping resource in the API.
                      Example: apps/myapp/domainMapping/example.com.'
                    type: string
                  overrideStrategy:
                    description: 'Whether the domain creation should override any
                      existing mappings for this domain. By default, overrides are
                      rejected. Default value: "STRICT" Possible values: ["STRICT",
                      "OVERRIDE"]'
                    type: string
                  project:
                    type: string
                  resourceRecords:
                    description: The resource records required to configure this domain
                      mapping. These records must be added to the domain's DNS configuration
                      in order to serve the application via this domain mapping.
                    items:
                      properties:
                        name:
                          description: 'Relative name of the object affected by this
                            record. Only applicable for CNAME records. Example: ''www''.'
                          type: string
                        rrdata:
                          description: Data for this record. Values vary by record
                            type, as defined in RFC 1035 (section 5) and RFC 1034
                            (section 3.6.1).
                          type: string
                        type:
                          description: 'Resource record type. Example: ''AAAA''. Possible
                            values: ["A", "AAAA", "CNAME"]'
                          type: string
                      type: object
                    type: array
                  sslSettings:
                    description: SSL configuration for this domain. If unconfigured,
                      this domain will not serve with SSL.
                    properties:
                      certificateID:
                        description: 'ID of the AuthorizedCertificate resource configuring
                          SSL for the application. Clearing this field will remove
                          SSL support. By default, a managed certificate is automatically
                          created for every domain mapping. To omit SSL support or
                          to configure SSL manually, specify ''SslManagementType.MANUAL''
                          on a ''CREATE'' or ''UPDATE'' request. You must be authorized
                          to administer the ''AuthorizedCertificate'' resource to
                          manually map it to a DomainMapping resource. Example: 12345.'
                        type: string
                      pendingManagedCertificateID:
                        description: ID of the managed 'AuthorizedCertificate' resource
                          currently being provisioned, if applicable. Until the new
                          managed certificate has been successfully provisioned, the
                          previous SSL state will be preserved. Once the provisioning
                          process completes, the 'certificateId' field will reflect
                          the new managed certificate and this field will be left
                          empty. To remove SSL support while there is still a pending
                          managed certificate, clear the 'certificateId' field with
                          an update request.
                        type: string
                      sslManagementType:
                        description: 'SSL management type for this domain. If ''AUTOMATIC'',
                          a managed certificate is automatically provisioned. If ''MANUAL'',
                          ''certificateId'' must be manually specified in order to
                          configure SSL for this domain. Possible values: ["AUTOMATIC",
                          "MANUAL"]'
                        type: string
                    required:
                    - sslManagementType
                    type: object
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                required:
                - domainName
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
