apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: google.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: applications.appengine.google.kubeform.com
spec:
  group: appengine.google.kubeform.com
  names:
    kind: Application
    listKind: ApplicationList
    plural: applications
    singular: application
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  appID:
                    description: Identifier of the app.
                    type: string
                  authDomain:
                    description: The domain to authenticate users with when using
                      App Engine's User API.
                    type: string
                  codeBucket:
                    description: The GCS bucket code is being stored in for this app.
                    type: string
                  databaseType:
                    type: string
                  defaultBucket:
                    description: The GCS bucket content is being stored in for this
                      app.
                    type: string
                  defaultHostname:
                    description: The default hostname for this app.
                    type: string
                  featureSettings:
                    description: 'A block of optional settings to configure specific
                      App Engine features:'
                    properties:
                      splitHealthChecks:
                        type: boolean
                    required:
                    - splitHealthChecks
                    type: object
                  gcrDomain:
                    description: The GCR domain used for storing managed Docker images
                      for this app.
                    type: string
                  iap:
                    description: Settings for enabling Cloud Identity Aware Proxy
                    properties:
                      enabled:
                        description: Adapted for use with the app
                        type: boolean
                      oauth2ClientID:
                        description: OAuth2 client ID to use for the authentication
                          flow.
                        type: string
                    required:
                    - oauth2ClientID
                    type: object
                  id:
                    type: string
                  locationID:
                    description: The location to serve the app from.
                    type: string
                  name:
                    description: Unique name of the app.
                    type: string
                  project:
                    description: The project ID to create the application under.
                    type: string
                  servingStatus:
                    description: The serving status of the app.
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  urlDispatchRule:
                    description: A list of dispatch rule blocks. Each block has a
                      domain, path, and service field.
                    items:
                      properties:
                        domain:
                          type: string
                        path:
                          type: string
                        service:
                          type: string
                      type: object
                    type: array
                required:
                - locationID
                type: object
              secretRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              state:
                properties:
                  appID:
                    description: Identifier of the app.
                    type: string
                  authDomain:
                    description: The domain to authenticate users with when using
                      App Engine's User API.
                    type: string
                  codeBucket:
                    description: The GCS bucket code is being stored in for this app.
                    type: string
                  databaseType:
                    type: string
                  defaultBucket:
                    description: The GCS bucket content is being stored in for this
                      app.
                    type: string
                  defaultHostname:
                    description: The default hostname for this app.
                    type: string
                  featureSettings:
                    description: 'A block of optional settings to configure specific
                      App Engine features:'
                    properties:
                      splitHealthChecks:
                        type: boolean
                    required:
                    - splitHealthChecks
                    type: object
                  gcrDomain:
                    description: The GCR domain used for storing managed Docker images
                      for this app.
                    type: string
                  iap:
                    description: Settings for enabling Cloud Identity Aware Proxy
                    properties:
                      enabled:
                        description: Adapted for use with the app
                        type: boolean
                      oauth2ClientID:
                        description: OAuth2 client ID to use for the authentication
                          flow.
                        type: string
                    required:
                    - oauth2ClientID
                    type: object
                  id:
                    type: string
                  locationID:
                    description: The location to serve the app from.
                    type: string
                  name:
                    description: Unique name of the app.
                    type: string
                  project:
                    description: The project ID to create the application under.
                    type: string
                  servingStatus:
                    description: The serving status of the app.
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  urlDispatchRule:
                    description: A list of dispatch rule blocks. Each block has a
                      domain, path, and service field.
                    items:
                      properties:
                        domain:
                          type: string
                        path:
                          type: string
                        service:
                          type: string
                      type: object
                    type: array
                required:
                - locationID
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
