apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: google.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: datasetaccesses.bigquery.google.kubeform.com
spec:
  group: bigquery.google.kubeform.com
  names:
    kind: DatasetAccess
    listKind: DatasetAccessList
    plural: datasetaccesses
    singular: datasetaccess
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              kubeformOutput:
                properties:
                  apiUpdatedMember:
                    description: If true, represents that that the iam_member in the
                      config was translated to a different member type by the API,
                      and is stored in state as a different member type
                    type: boolean
                  datasetID:
                    description: A unique ID for this dataset, without the project
                      name. The ID must contain only letters (a-z, A-Z), numbers (0-9),
                      or underscores (_). The maximum length is 1,024 characters.
                    type: string
                  domain:
                    description: A domain to grant access to. Any users signed in
                      with the domain specified will be granted the specified access
                    type: string
                  groupByEmail:
                    description: An email address of a Google Group to grant access
                      to.
                    type: string
                  iamMember:
                    description: 'Some other type of member that appears in the IAM
                      Policy but isn''t a user, group, domain, or special group. For
                      example: ''allUsers'''
                    type: string
                  id:
                    type: string
                  project:
                    type: string
                  role:
                    description: Describes the rights granted to the user specified
                      by the other member of the access object. Basic, predefined,
                      and custom roles are supported. Predefined roles that have equivalent
                      basic roles are swapped by the API to their basic counterparts,
                      and will show a diff post-create. See [official docs](https://cloud.google.com/bigquery/docs/access-control).
                    type: string
                  specialGroup:
                    description: "A special group to grant access to. Possible values
                      include: \n * 'projectOwners': Owners of the enclosing project.
                      \n * 'projectReaders': Readers of the enclosing project. \n
                      * 'projectWriters': Writers of the enclosing project. \n * 'allAuthenticatedUsers':
                      All authenticated BigQuery users."
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  userByEmail:
                    description: 'An email address of a user to grant access to. For
                      example: fred@example.com'
                    type: string
                  view:
                    description: A view from a different dataset to grant access to.
                      Queries executed against that view will have read access to
                      tables in this dataset. The role field is not required when
                      this field is set. If that view is updated by any user, access
                      to the view needs to be granted again via an update operation.
                    properties:
                      datasetID:
                        description: The ID of the dataset containing this table.
                        type: string
                      projectID:
                        description: The ID of the project containing this table.
                        type: string
                      tableID:
                        description: The ID of the table. The ID must contain only
                          letters (a-z, A-Z), numbers (0-9), or underscores (_). The
                          maximum length is 1,024 characters.
                        type: string
                    required:
                    - datasetID
                    - projectID
                    - tableID
                    type: object
                required:
                - datasetID
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  apiUpdatedMember:
                    description: If true, represents that that the iam_member in the
                      config was translated to a different member type by the API,
                      and is stored in state as a different member type
                    type: boolean
                  datasetID:
                    description: A unique ID for this dataset, without the project
                      name. The ID must contain only letters (a-z, A-Z), numbers (0-9),
                      or underscores (_). The maximum length is 1,024 characters.
                    type: string
                  domain:
                    description: A domain to grant access to. Any users signed in
                      with the domain specified will be granted the specified access
                    type: string
                  groupByEmail:
                    description: An email address of a Google Group to grant access
                      to.
                    type: string
                  iamMember:
                    description: 'Some other type of member that appears in the IAM
                      Policy but isn''t a user, group, domain, or special group. For
                      example: ''allUsers'''
                    type: string
                  id:
                    type: string
                  project:
                    type: string
                  role:
                    description: Describes the rights granted to the user specified
                      by the other member of the access object. Basic, predefined,
                      and custom roles are supported. Predefined roles that have equivalent
                      basic roles are swapped by the API to their basic counterparts,
                      and will show a diff post-create. See [official docs](https://cloud.google.com/bigquery/docs/access-control).
                    type: string
                  specialGroup:
                    description: "A special group to grant access to. Possible values
                      include: \n * 'projectOwners': Owners of the enclosing project.
                      \n * 'projectReaders': Readers of the enclosing project. \n
                      * 'projectWriters': Writers of the enclosing project. \n * 'allAuthenticatedUsers':
                      All authenticated BigQuery users."
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  userByEmail:
                    description: 'An email address of a user to grant access to. For
                      example: fred@example.com'
                    type: string
                  view:
                    description: A view from a different dataset to grant access to.
                      Queries executed against that view will have read access to
                      tables in this dataset. The role field is not required when
                      this field is set. If that view is updated by any user, access
                      to the view needs to be granted again via an update operation.
                    properties:
                      datasetID:
                        description: The ID of the dataset containing this table.
                        type: string
                      projectID:
                        description: The ID of the project containing this table.
                        type: string
                      tableID:
                        description: The ID of the table. The ID must contain only
                          letters (a-z, A-Z), numbers (0-9), or underscores (_). The
                          maximum length is 1,024 characters.
                        type: string
                    required:
                    - datasetID
                    - projectID
                    - tableID
                    type: object
                required:
                - datasetID
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
