apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: google.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: instances.bigtable.google.kubeform.com
spec:
  group: bigtable.google.kubeform.com
  names:
    kind: Instance
    listKind: InstanceList
    plural: instances
    singular: instance
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  cluster:
                    description: A block of cluster configuration options. This can
                      be specified at least once.
                    items:
                      properties:
                        clusterID:
                          description: The ID of the Cloud Bigtable cluster.
                          type: string
                        kmsKeyName:
                          description: 'Describes the Cloud KMS encryption key that
                            will be used to protect the destination Bigtable cluster.
                            The requirements for this key are: 1) The Cloud Bigtable
                            service account associated with the project that contains
                            this cluster must be granted the cloudkms.cryptoKeyEncrypterDecrypter
                            role on the CMEK key. 2) Only regional keys can be used
                            and the region of the CMEK key must match the region of
                            the cluster. 3) All clusters within an instance must use
                            the same CMEK key. Values are of the form projects/{project}/locations/{location}/keyRings/{keyring}/cryptoKeys/{key}'
                          type: string
                        numNodes:
                          description: The number of nodes in your Cloud Bigtable
                            cluster. Required, with a minimum of 1 for a PRODUCTION
                            instance. Must be left unset for a DEVELOPMENT instance.
                          format: int64
                          type: integer
                        storageType:
                          description: The storage type to use. One of "SSD" or "HDD".
                            Defaults to "SSD".
                          type: string
                        zone:
                          description: The zone to create the Cloud Bigtable cluster
                            in. Each cluster must have a different zone in the same
                            region. Zones that support Bigtable instances are noted
                            on the Cloud Bigtable locations page.
                          type: string
                      required:
                      - clusterID
                      type: object
                    type: array
                  deletionProtection:
                    description: Whether or not to allow Terraform to destroy the
                      instance. Unless this field is set to false in Terraform state,
                      a terraform destroy or terraform apply that would delete the
                      instance will fail.
                    type: boolean
                  displayName:
                    description: The human-readable display name of the Bigtable instance.
                      Defaults to the instance name.
                    type: string
                  id:
                    type: string
                  instanceType:
                    description: The instance type to create. One of "DEVELOPMENT"
                      or "PRODUCTION". Defaults to "PRODUCTION". Deprecated
                    type: string
                  labels:
                    additionalProperties:
                      type: string
                    description: A mapping of labels to assign to the resource.
                    type: object
                  name:
                    description: The name (also called Instance Id in the Cloud Console)
                      of the Cloud Bigtable instance.
                    type: string
                  project:
                    description: The ID of the project in which the resource belongs.
                      If it is not provided, the provider project is used.
                    type: string
                required:
                - name
                type: object
              state:
                properties:
                  cluster:
                    description: A block of cluster configuration options. This can
                      be specified at least once.
                    items:
                      properties:
                        clusterID:
                          description: The ID of the Cloud Bigtable cluster.
                          type: string
                        kmsKeyName:
                          description: 'Describes the Cloud KMS encryption key that
                            will be used to protect the destination Bigtable cluster.
                            The requirements for this key are: 1) The Cloud Bigtable
                            service account associated with the project that contains
                            this cluster must be granted the cloudkms.cryptoKeyEncrypterDecrypter
                            role on the CMEK key. 2) Only regional keys can be used
                            and the region of the CMEK key must match the region of
                            the cluster. 3) All clusters within an instance must use
                            the same CMEK key. Values are of the form projects/{project}/locations/{location}/keyRings/{keyring}/cryptoKeys/{key}'
                          type: string
                        numNodes:
                          description: The number of nodes in your Cloud Bigtable
                            cluster. Required, with a minimum of 1 for a PRODUCTION
                            instance. Must be left unset for a DEVELOPMENT instance.
                          format: int64
                          type: integer
                        storageType:
                          description: The storage type to use. One of "SSD" or "HDD".
                            Defaults to "SSD".
                          type: string
                        zone:
                          description: The zone to create the Cloud Bigtable cluster
                            in. Each cluster must have a different zone in the same
                            region. Zones that support Bigtable instances are noted
                            on the Cloud Bigtable locations page.
                          type: string
                      required:
                      - clusterID
                      type: object
                    type: array
                  deletionProtection:
                    description: Whether or not to allow Terraform to destroy the
                      instance. Unless this field is set to false in Terraform state,
                      a terraform destroy or terraform apply that would delete the
                      instance will fail.
                    type: boolean
                  displayName:
                    description: The human-readable display name of the Bigtable instance.
                      Defaults to the instance name.
                    type: string
                  id:
                    type: string
                  instanceType:
                    description: The instance type to create. One of "DEVELOPMENT"
                      or "PRODUCTION". Defaults to "PRODUCTION". Deprecated
                    type: string
                  labels:
                    additionalProperties:
                      type: string
                    description: A mapping of labels to assign to the resource.
                    type: object
                  name:
                    description: The name (also called Instance Id in the Cloud Console)
                      of the Cloud Bigtable instance.
                    type: string
                  project:
                    description: The ID of the project in which the resource belongs.
                      If it is not provided, the provider project is used.
                    type: string
                required:
                - name
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
