apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: google.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: workerpools.cloudbuild.google.kubeform.com
spec:
  group: cloudbuild.google.kubeform.com
  names:
    kind: WorkerPool
    listKind: WorkerPoolList
    plural: workerpools
    singular: workerpool
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  annotations:
                    additionalProperties:
                      type: string
                    description: User specified annotations. See https://google.aip.dev/128#annotations
                      for more details such as format and size limitations.
                    type: object
                  createTime:
                    description: Output only. Time at which the request to create
                      the `WorkerPool` was received.
                    type: string
                  deleteTime:
                    description: Output only. Time at which the request to delete
                      the `WorkerPool` was received.
                    type: string
                  displayName:
                    description: A user-specified, human-readable name for the `WorkerPool`.
                      If provided, this value must be 1-63 characters.
                    type: string
                  id:
                    type: string
                  location:
                    description: The location for the resource
                    type: string
                  name:
                    description: User-defined name of the `WorkerPool`.
                    type: string
                  networkConfig:
                    description: Network configuration for the `WorkerPool`.
                    properties:
                      peeredNetwork:
                        description: Required. Immutable. The network definition that
                          the workers are peered to. If this section is left empty,
                          the workers will be peered to `WorkerPool.project_id` on
                          the service producer network. Must be in the format `projects/{project}/global/networks/{network}`,
                          where `{project}` is a project number, such as `12345`,
                          and `{network}` is the name of a VPC network in the project.
                          See [Understanding network configuration options](https://cloud.google.com/cloud-build/docs/custom-workers/set-up-custom-worker-pool-environment#understanding_the_network_configuration_options)
                        type: string
                    required:
                    - peeredNetwork
                    type: object
                  project:
                    description: The project for the resource
                    type: string
                  state:
                    description: 'Output only. `WorkerPool` state. Possible values:
                      STATE_UNSPECIFIED, PENDING, APPROVED, REJECTED, CANCELLED'
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  uid:
                    description: Output only. A unique identifier for the `WorkerPool`.
                    type: string
                  updateTime:
                    description: Output only. Time at which the request to update
                      the `WorkerPool` was received.
                    type: string
                  workerConfig:
                    description: Configuration to be used for a creating workers in
                      the `WorkerPool`.
                    properties:
                      diskSizeGb:
                        description: Size of the disk attached to the worker, in GB.
                          See [Worker pool config file](https://cloud.google.com/cloud-build/docs/custom-workers/worker-pool-config-file).
                          Specify a value of up to 1000. If `0` is specified, Cloud
                          Build will use a standard disk size.
                        format: int64
                        type: integer
                      machineType:
                        description: Machine type of a worker, such as `n1-standard-1`.
                          See [Worker pool config file](https://cloud.google.com/cloud-build/docs/custom-workers/worker-pool-config-file).
                          If left blank, Cloud Build will use `n1-standard-1`.
                        type: string
                      noExternalIP:
                        description: If true, workers are created without any public
                          address, which prevents network egress to public IPs.
                        type: boolean
                    type: object
                required:
                - location
                - name
                type: object
              state:
                properties:
                  annotations:
                    additionalProperties:
                      type: string
                    description: User specified annotations. See https://google.aip.dev/128#annotations
                      for more details such as format and size limitations.
                    type: object
                  createTime:
                    description: Output only. Time at which the request to create
                      the `WorkerPool` was received.
                    type: string
                  deleteTime:
                    description: Output only. Time at which the request to delete
                      the `WorkerPool` was received.
                    type: string
                  displayName:
                    description: A user-specified, human-readable name for the `WorkerPool`.
                      If provided, this value must be 1-63 characters.
                    type: string
                  id:
                    type: string
                  location:
                    description: The location for the resource
                    type: string
                  name:
                    description: User-defined name of the `WorkerPool`.
                    type: string
                  networkConfig:
                    description: Network configuration for the `WorkerPool`.
                    properties:
                      peeredNetwork:
                        description: Required. Immutable. The network definition that
                          the workers are peered to. If this section is left empty,
                          the workers will be peered to `WorkerPool.project_id` on
                          the service producer network. Must be in the format `projects/{project}/global/networks/{network}`,
                          where `{project}` is a project number, such as `12345`,
                          and `{network}` is the name of a VPC network in the project.
                          See [Understanding network configuration options](https://cloud.google.com/cloud-build/docs/custom-workers/set-up-custom-worker-pool-environment#understanding_the_network_configuration_options)
                        type: string
                    required:
                    - peeredNetwork
                    type: object
                  project:
                    description: The project for the resource
                    type: string
                  state:
                    description: 'Output only. `WorkerPool` state. Possible values:
                      STATE_UNSPECIFIED, PENDING, APPROVED, REJECTED, CANCELLED'
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  uid:
                    description: Output only. A unique identifier for the `WorkerPool`.
                    type: string
                  updateTime:
                    description: Output only. Time at which the request to update
                      the `WorkerPool` was received.
                    type: string
                  workerConfig:
                    description: Configuration to be used for a creating workers in
                      the `WorkerPool`.
                    properties:
                      diskSizeGb:
                        description: Size of the disk attached to the worker, in GB.
                          See [Worker pool config file](https://cloud.google.com/cloud-build/docs/custom-workers/worker-pool-config-file).
                          Specify a value of up to 1000. If `0` is specified, Cloud
                          Build will use a standard disk size.
                        format: int64
                        type: integer
                      machineType:
                        description: Machine type of a worker, such as `n1-standard-1`.
                          See [Worker pool config file](https://cloud.google.com/cloud-build/docs/custom-workers/worker-pool-config-file).
                          If left blank, Cloud Build will use `n1-standard-1`.
                        type: string
                      noExternalIP:
                        description: If true, workers are created without any public
                          address, which prevents network egress to public IPs.
                        type: boolean
                    type: object
                required:
                - location
                - name
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
