apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: google.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: identitygroups.cloud.google.kubeform.com
spec:
  group: cloud.google.kubeform.com
  names:
    kind: IdentityGroup
    listKind: IdentityGroupList
    plural: identitygroups
    singular: identitygroup
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              kubeformOutput:
                properties:
                  createTime:
                    description: The time when the Group was created.
                    type: string
                  description:
                    description: An extended description to help users determine the
                      purpose of a Group. Must not be longer than 4,096 characters.
                    type: string
                  displayName:
                    description: The display name of the Group.
                    type: string
                  groupKey:
                    description: EntityKey of the Group.
                    properties:
                      ID:
                        description: "The ID of the entity. \n For Google-managed
                          entities, the id must be the email address of an existing
                          group or user. \n For external-identity-mapped entities,
                          the id must be a string conforming to the Identity Source's
                          requirements. \n Must be unique within a namespace."
                        type: string
                      namespace:
                        description: "The namespace in which the entity exists. \n
                          If not specified, the EntityKey represents a Google-managed
                          entity such as a Google user or a Google Group. \n If specified,
                          the EntityKey represents an external-identity-mapped group.
                          The namespace must correspond to an identity source created
                          in Admin Console and must be in the form of 'identitysources/{identity_source_id}'."
                        type: string
                    required:
                    - ID
                    type: object
                  id:
                    type: string
                  initialGroupConfig:
                    description: "The initial configuration options for creating a
                      Group. \n See the [API reference](https://cloud.google.com/identity/docs/reference/rest/v1beta1/groups/create#initialgroupconfig)
                      for possible values. Default value: \"EMPTY\" Possible values:
                      [\"INITIAL_GROUP_CONFIG_UNSPECIFIED\", \"WITH_INITIAL_OWNER\",
                      \"EMPTY\"]"
                    type: string
                  labels:
                    additionalProperties:
                      type: string
                    description: "The labels that apply to the Group. \n Must not
                      contain more than one entry. Must contain the entry 'cloudidentity.googleapis.com/groups.discussion_forum':
                      '' if the Group is a Google Group or 'system/groups/external':
                      '' if the Group is an external-identity-mapped group."
                    type: object
                  name:
                    description: 'Resource name of the Group in the format: groups/{group_id},
                      where group_id is the unique ID assigned to the Group.'
                    type: string
                  parent:
                    description: "The resource name of the entity under which this
                      Group resides in the Cloud Identity resource hierarchy. \n Must
                      be of the form identitysources/{identity_source_id} for external-identity-mapped
                      groups or customers/{customer_id} for Google Groups."
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  updateTime:
                    description: The time when the Group was last updated.
                    type: string
                required:
                - groupKey
                - labels
                - parent
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  createTime:
                    description: The time when the Group was created.
                    type: string
                  description:
                    description: An extended description to help users determine the
                      purpose of a Group. Must not be longer than 4,096 characters.
                    type: string
                  displayName:
                    description: The display name of the Group.
                    type: string
                  groupKey:
                    description: EntityKey of the Group.
                    properties:
                      ID:
                        description: "The ID of the entity. \n For Google-managed
                          entities, the id must be the email address of an existing
                          group or user. \n For external-identity-mapped entities,
                          the id must be a string conforming to the Identity Source's
                          requirements. \n Must be unique within a namespace."
                        type: string
                      namespace:
                        description: "The namespace in which the entity exists. \n
                          If not specified, the EntityKey represents a Google-managed
                          entity such as a Google user or a Google Group. \n If specified,
                          the EntityKey represents an external-identity-mapped group.
                          The namespace must correspond to an identity source created
                          in Admin Console and must be in the form of 'identitysources/{identity_source_id}'."
                        type: string
                    required:
                    - ID
                    type: object
                  id:
                    type: string
                  initialGroupConfig:
                    description: "The initial configuration options for creating a
                      Group. \n See the [API reference](https://cloud.google.com/identity/docs/reference/rest/v1beta1/groups/create#initialgroupconfig)
                      for possible values. Default value: \"EMPTY\" Possible values:
                      [\"INITIAL_GROUP_CONFIG_UNSPECIFIED\", \"WITH_INITIAL_OWNER\",
                      \"EMPTY\"]"
                    type: string
                  labels:
                    additionalProperties:
                      type: string
                    description: "The labels that apply to the Group. \n Must not
                      contain more than one entry. Must contain the entry 'cloudidentity.googleapis.com/groups.discussion_forum':
                      '' if the Group is a Google Group or 'system/groups/external':
                      '' if the Group is an external-identity-mapped group."
                    type: object
                  name:
                    description: 'Resource name of the Group in the format: groups/{group_id},
                      where group_id is the unique ID assigned to the Group.'
                    type: string
                  parent:
                    description: "The resource name of the entity under which this
                      Group resides in the Cloud Identity resource hierarchy. \n Must
                      be of the form identitysources/{identity_source_id} for external-identity-mapped
                      groups or customers/{customer_id} for Google Groups."
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  updateTime:
                    description: The time when the Group was last updated.
                    type: string
                required:
                - groupKey
                - labels
                - parent
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
