apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: google.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: addresses.compute.google.kubeform.com
spec:
  group: compute.google.kubeform.com
  names:
    kind: Address
    listKind: AddressList
    plural: addresses
    singular: address
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              kubeformOutput:
                properties:
                  address:
                    description: The static external IP address represented by this
                      resource. Only IPv4 is supported. An address may only be specified
                      for INTERNAL address types. The IP address must be inside the
                      specified subnetwork, if any.
                    type: string
                  addressType:
                    description: 'The type of address to reserve. Default value: "EXTERNAL"
                      Possible values: ["INTERNAL", "EXTERNAL"]'
                    type: string
                  creationTimestamp:
                    description: Creation timestamp in RFC3339 text format.
                    type: string
                  description:
                    description: An optional description of this resource.
                    type: string
                  id:
                    type: string
                  name:
                    description: Name of the resource. The name must be 1-63 characters
                      long, and comply with RFC1035. Specifically, the name must be
                      1-63 characters long and match the regular expression '[a-z]([-a-z0-9]*[a-z0-9])?'
                      which means the first character must be a lowercase letter,
                      and all following characters must be a dash, lowercase letter,
                      or digit, except the last character, which cannot be a dash.
                    type: string
                  network:
                    description: The URL of the network in which to reserve the address.
                      This field can only be used with INTERNAL type with the VPC_PEERING
                      and IPSEC_INTERCONNECT purposes.
                    type: string
                  networkTier:
                    description: 'The networking tier used for configuring this address.
                      If this field is not specified, it is assumed to be PREMIUM.
                      Possible values: ["PREMIUM", "STANDARD"]'
                    type: string
                  prefixLength:
                    description: The prefix length if the resource represents an IP
                      range.
                    format: int64
                    type: integer
                  project:
                    type: string
                  purpose:
                    description: "The purpose of this resource, which can be one of
                      the following values: \n * GCE_ENDPOINT for addresses that are
                      used by VM instances, alias IP   ranges, internal load balancers,
                      and similar resources. \n * SHARED_LOADBALANCER_VIP for an address
                      that can be used by multiple   internal load balancers. \n *
                      VPC_PEERING for addresses that are reserved for VPC peer networks.
                      \n * IPSEC_INTERCONNECT for addresses created from a private
                      IP range   that are reserved for a VLAN attachment in an IPsec-encrypted
                      Cloud   Interconnect configuration. These addresses are regional
                      resources. \n This should only be set when using an Internal
                      address."
                    type: string
                  region:
                    description: The Region in which the created address should reside.
                      If it is not provided, the provider region is used.
                    type: string
                  selfLink:
                    type: string
                  subnetwork:
                    description: The URL of the subnetwork in which to reserve the
                      address. If an IP address is specified, it must be within the
                      subnetwork's IP range. This field can only be used with INTERNAL
                      type with GCE_ENDPOINT/DNS_RESOLVER purposes.
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  users:
                    description: The URLs of the resources that are using this address.
                    items:
                      type: string
                    type: array
                required:
                - name
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  address:
                    description: The static external IP address represented by this
                      resource. Only IPv4 is supported. An address may only be specified
                      for INTERNAL address types. The IP address must be inside the
                      specified subnetwork, if any.
                    type: string
                  addressType:
                    description: 'The type of address to reserve. Default value: "EXTERNAL"
                      Possible values: ["INTERNAL", "EXTERNAL"]'
                    type: string
                  creationTimestamp:
                    description: Creation timestamp in RFC3339 text format.
                    type: string
                  description:
                    description: An optional description of this resource.
                    type: string
                  id:
                    type: string
                  name:
                    description: Name of the resource. The name must be 1-63 characters
                      long, and comply with RFC1035. Specifically, the name must be
                      1-63 characters long and match the regular expression '[a-z]([-a-z0-9]*[a-z0-9])?'
                      which means the first character must be a lowercase letter,
                      and all following characters must be a dash, lowercase letter,
                      or digit, except the last character, which cannot be a dash.
                    type: string
                  network:
                    description: The URL of the network in which to reserve the address.
                      This field can only be used with INTERNAL type with the VPC_PEERING
                      and IPSEC_INTERCONNECT purposes.
                    type: string
                  networkTier:
                    description: 'The networking tier used for configuring this address.
                      If this field is not specified, it is assumed to be PREMIUM.
                      Possible values: ["PREMIUM", "STANDARD"]'
                    type: string
                  prefixLength:
                    description: The prefix length if the resource represents an IP
                      range.
                    format: int64
                    type: integer
                  project:
                    type: string
                  purpose:
                    description: "The purpose of this resource, which can be one of
                      the following values: \n * GCE_ENDPOINT for addresses that are
                      used by VM instances, alias IP   ranges, internal load balancers,
                      and similar resources. \n * SHARED_LOADBALANCER_VIP for an address
                      that can be used by multiple   internal load balancers. \n *
                      VPC_PEERING for addresses that are reserved for VPC peer networks.
                      \n * IPSEC_INTERCONNECT for addresses created from a private
                      IP range   that are reserved for a VLAN attachment in an IPsec-encrypted
                      Cloud   Interconnect configuration. These addresses are regional
                      resources. \n This should only be set when using an Internal
                      address."
                    type: string
                  region:
                    description: The Region in which the created address should reside.
                      If it is not provided, the provider region is used.
                    type: string
                  selfLink:
                    type: string
                  subnetwork:
                    description: The URL of the subnetwork in which to reserve the
                      address. If an IP address is specified, it must be within the
                      subnetwork's IP range. This field can only be used with INTERNAL
                      type with GCE_ENDPOINT/DNS_RESOLVER purposes.
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  users:
                    description: The URLs of the resources that are using this address.
                    items:
                      type: string
                    type: array
                required:
                - name
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
