apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: google.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: routes.compute.google.kubeform.com
spec:
  group: compute.google.kubeform.com
  names:
    kind: Route
    listKind: RouteList
    plural: routes
    singular: route
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  description:
                    description: An optional description of this resource. Provide
                      this property when you create the resource.
                    type: string
                  destRange:
                    description: The destination range of outgoing packets that this
                      route applies to. Only IPv4 is supported.
                    type: string
                  id:
                    type: string
                  name:
                    description: Name of the resource. Provided by the client when
                      the resource is created. The name must be 1-63 characters long,
                      and comply with RFC1035.  Specifically, the name must be 1-63
                      characters long and match the regular expression '[a-z]([-a-z0-9]*[a-z0-9])?'
                      which means the first character must be a lowercase letter,
                      and all following characters must be a dash, lowercase letter,
                      or digit, except the last character, which cannot be a dash.
                    type: string
                  network:
                    description: The network that this route applies to.
                    type: string
                  nextHopGateway:
                    description: 'URL to a gateway that should handle matching packets.
                      Currently, you can only specify the internet gateway, using
                      a full or partial valid URL: * ''https://www.googleapis.com/compute/v1/projects/project/global/gateways/default-internet-gateway''
                      * ''projects/project/global/gateways/default-internet-gateway''
                      * ''global/gateways/default-internet-gateway'' * The string
                      ''default-internet-gateway''.'
                    type: string
                  nextHopIP:
                    description: Network IP address of an instance that should handle
                      matching packets.
                    type: string
                  nextHopIlb:
                    description: 'The URL to a forwarding rule of type loadBalancingScheme=INTERNAL
                      that should handle matching packets. You can only specify the
                      forwarding rule as a partial or full URL. For example, the following
                      are all valid URLs: https://www.googleapis.com/compute/v1/projects/project/regions/region/forwardingRules/forwardingRule
                      regions/region/forwardingRules/forwardingRule Note that this
                      can only be used when the destinationRange is a public (non-RFC
                      1918) IP CIDR range.'
                    type: string
                  nextHopInstance:
                    description: 'URL to an instance that should handle matching packets.
                      You can specify this as a full or partial URL. For example:
                      * ''https://www.googleapis.com/compute/v1/projects/project/zones/zone/instances/instance''
                      * ''projects/project/zones/zone/instances/instance'' * ''zones/zone/instances/instance''
                      * Just the instance name, with the zone in ''next_hop_instance_zone''.'
                    type: string
                  nextHopInstanceZone:
                    description: The zone of the instance specified in next_hop_instance.
                      Omit if next_hop_instance is specified as a URL.
                    type: string
                  nextHopNetwork:
                    description: URL to a Network that should handle matching packets.
                    type: string
                  nextHopVPNTunnel:
                    description: URL to a VpnTunnel that should handle matching packets.
                    type: string
                  priority:
                    description: "The priority of this route. Priority is used to
                      break ties in cases where there is more than one matching route
                      of equal prefix length. \n In the case of two routes with equal
                      prefix length, the one with the lowest-numbered priority value
                      wins. \n Default value is 1000. Valid range is 0 through 65535."
                    format: int64
                    type: integer
                  project:
                    type: string
                  selfLink:
                    type: string
                  tags:
                    description: A list of instance tags to which this route applies.
                    items:
                      type: string
                    type: array
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                required:
                - destRange
                - name
                - network
                type: object
              state:
                properties:
                  description:
                    description: An optional description of this resource. Provide
                      this property when you create the resource.
                    type: string
                  destRange:
                    description: The destination range of outgoing packets that this
                      route applies to. Only IPv4 is supported.
                    type: string
                  id:
                    type: string
                  name:
                    description: Name of the resource. Provided by the client when
                      the resource is created. The name must be 1-63 characters long,
                      and comply with RFC1035.  Specifically, the name must be 1-63
                      characters long and match the regular expression '[a-z]([-a-z0-9]*[a-z0-9])?'
                      which means the first character must be a lowercase letter,
                      and all following characters must be a dash, lowercase letter,
                      or digit, except the last character, which cannot be a dash.
                    type: string
                  network:
                    description: The network that this route applies to.
                    type: string
                  nextHopGateway:
                    description: 'URL to a gateway that should handle matching packets.
                      Currently, you can only specify the internet gateway, using
                      a full or partial valid URL: * ''https://www.googleapis.com/compute/v1/projects/project/global/gateways/default-internet-gateway''
                      * ''projects/project/global/gateways/default-internet-gateway''
                      * ''global/gateways/default-internet-gateway'' * The string
                      ''default-internet-gateway''.'
                    type: string
                  nextHopIP:
                    description: Network IP address of an instance that should handle
                      matching packets.
                    type: string
                  nextHopIlb:
                    description: 'The URL to a forwarding rule of type loadBalancingScheme=INTERNAL
                      that should handle matching packets. You can only specify the
                      forwarding rule as a partial or full URL. For example, the following
                      are all valid URLs: https://www.googleapis.com/compute/v1/projects/project/regions/region/forwardingRules/forwardingRule
                      regions/region/forwardingRules/forwardingRule Note that this
                      can only be used when the destinationRange is a public (non-RFC
                      1918) IP CIDR range.'
                    type: string
                  nextHopInstance:
                    description: 'URL to an instance that should handle matching packets.
                      You can specify this as a full or partial URL. For example:
                      * ''https://www.googleapis.com/compute/v1/projects/project/zones/zone/instances/instance''
                      * ''projects/project/zones/zone/instances/instance'' * ''zones/zone/instances/instance''
                      * Just the instance name, with the zone in ''next_hop_instance_zone''.'
                    type: string
                  nextHopInstanceZone:
                    description: The zone of the instance specified in next_hop_instance.
                      Omit if next_hop_instance is specified as a URL.
                    type: string
                  nextHopNetwork:
                    description: URL to a Network that should handle matching packets.
                    type: string
                  nextHopVPNTunnel:
                    description: URL to a VpnTunnel that should handle matching packets.
                    type: string
                  priority:
                    description: "The priority of this route. Priority is used to
                      break ties in cases where there is more than one matching route
                      of equal prefix length. \n In the case of two routes with equal
                      prefix length, the one with the lowest-numbered priority value
                      wins. \n Default value is 1000. Valid range is 0 through 65535."
                    format: int64
                    type: integer
                  project:
                    type: string
                  selfLink:
                    type: string
                  tags:
                    description: A list of instance tags to which this route applies.
                    items:
                      type: string
                    type: array
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                required:
                - destRange
                - name
                - network
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
