apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: google.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: packetmirrorings.compute.google.kubeform.com
spec:
  group: compute.google.kubeform.com
  names:
    kind: PacketMirroring
    listKind: PacketMirroringList
    plural: packetmirrorings
    singular: packetmirroring
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              kubeformOutput:
                properties:
                  collectorIlb:
                    description: The Forwarding Rule resource (of type load_balancing_scheme=INTERNAL)
                      that will be used as collector for mirrored traffic. The specified
                      forwarding rule must have is_mirroring_collector set to true.
                    properties:
                      url:
                        description: The URL of the forwarding rule.
                        type: string
                    required:
                    - url
                    type: object
                  description:
                    description: A human-readable description of the rule.
                    type: string
                  filter:
                    description: A filter for mirrored traffic.  If unset, all traffic
                      is mirrored.
                    properties:
                      cidrRanges:
                        description: IP CIDR ranges that apply as a filter on the
                          source (ingress) or destination (egress) IP in the IP header.
                          Only IPv4 is supported.
                        items:
                          type: string
                        type: array
                      direction:
                        description: 'Direction of traffic to mirror. Default value:
                          "BOTH" Possible values: ["INGRESS", "EGRESS", "BOTH"]'
                        type: string
                      ipProtocols:
                        description: 'Protocols that apply as a filter on mirrored
                          traffic. Possible values: ["tcp", "udp", "icmp"]'
                        items:
                          type: string
                        type: array
                    type: object
                  id:
                    type: string
                  mirroredResources:
                    description: A means of specifying which resources to mirror.
                    properties:
                      instances:
                        description: All the listed instances will be mirrored.  Specify
                          at most 50.
                        items:
                          properties:
                            url:
                              description: The URL of the instances where this rule
                                should be active.
                              type: string
                          required:
                          - url
                          type: object
                        type: array
                      subnetworks:
                        description: All instances in one of these subnetworks will
                          be mirrored.
                        items:
                          properties:
                            url:
                              description: The URL of the subnetwork where this rule
                                should be active.
                              type: string
                          required:
                          - url
                          type: object
                        type: array
                      tags:
                        description: All instances with these tags will be mirrored.
                        items:
                          type: string
                        type: array
                    type: object
                  name:
                    description: The name of the packet mirroring rule
                    type: string
                  network:
                    description: Specifies the mirrored VPC network. Only packets
                      in this network will be mirrored. All mirrored VMs should have
                      a NIC in the given network. All mirrored subnetworks should
                      belong to the given network.
                    properties:
                      url:
                        description: The full self_link URL of the network where this
                          rule is active.
                        type: string
                    required:
                    - url
                    type: object
                  priority:
                    description: Since only one rule can be active at a time, priority
                      is used to break ties in the case of two rules that apply to
                      the same instances.
                    format: int64
                    type: integer
                  project:
                    type: string
                  region:
                    description: The Region in which the created address should reside.
                      If it is not provided, the provider region is used.
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                required:
                - collectorIlb
                - mirroredResources
                - name
                - network
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  collectorIlb:
                    description: The Forwarding Rule resource (of type load_balancing_scheme=INTERNAL)
                      that will be used as collector for mirrored traffic. The specified
                      forwarding rule must have is_mirroring_collector set to true.
                    properties:
                      url:
                        description: The URL of the forwarding rule.
                        type: string
                    required:
                    - url
                    type: object
                  description:
                    description: A human-readable description of the rule.
                    type: string
                  filter:
                    description: A filter for mirrored traffic.  If unset, all traffic
                      is mirrored.
                    properties:
                      cidrRanges:
                        description: IP CIDR ranges that apply as a filter on the
                          source (ingress) or destination (egress) IP in the IP header.
                          Only IPv4 is supported.
                        items:
                          type: string
                        type: array
                      direction:
                        description: 'Direction of traffic to mirror. Default value:
                          "BOTH" Possible values: ["INGRESS", "EGRESS", "BOTH"]'
                        type: string
                      ipProtocols:
                        description: 'Protocols that apply as a filter on mirrored
                          traffic. Possible values: ["tcp", "udp", "icmp"]'
                        items:
                          type: string
                        type: array
                    type: object
                  id:
                    type: string
                  mirroredResources:
                    description: A means of specifying which resources to mirror.
                    properties:
                      instances:
                        description: All the listed instances will be mirrored.  Specify
                          at most 50.
                        items:
                          properties:
                            url:
                              description: The URL of the instances where this rule
                                should be active.
                              type: string
                          required:
                          - url
                          type: object
                        type: array
                      subnetworks:
                        description: All instances in one of these subnetworks will
                          be mirrored.
                        items:
                          properties:
                            url:
                              description: The URL of the subnetwork where this rule
                                should be active.
                              type: string
                          required:
                          - url
                          type: object
                        type: array
                      tags:
                        description: All instances with these tags will be mirrored.
                        items:
                          type: string
                        type: array
                    type: object
                  name:
                    description: The name of the packet mirroring rule
                    type: string
                  network:
                    description: Specifies the mirrored VPC network. Only packets
                      in this network will be mirrored. All mirrored VMs should have
                      a NIC in the given network. All mirrored subnetworks should
                      belong to the given network.
                    properties:
                      url:
                        description: The full self_link URL of the network where this
                          rule is active.
                        type: string
                    required:
                    - url
                    type: object
                  priority:
                    description: Since only one rule can be active at a time, priority
                      is used to break ties in the case of two rules that apply to
                      the same instances.
                    format: int64
                    type: integer
                  project:
                    type: string
                  region:
                    description: The Region in which the created address should reside.
                      If it is not provided, the provider region is used.
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                required:
                - collectorIlb
                - mirroredResources
                - name
                - network
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
