apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: google.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: routers.compute.google.kubeform.com
spec:
  group: compute.google.kubeform.com
  names:
    kind: Router
    listKind: RouterList
    plural: routers
    singular: router
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              kubeformOutput:
                properties:
                  bgp:
                    description: BGP information specific to this router.
                    properties:
                      advertiseMode:
                        description: 'User-specified flag to indicate which mode to
                          use for advertisement. Default value: "DEFAULT" Possible
                          values: ["DEFAULT", "CUSTOM"]'
                        type: string
                      advertisedGroups:
                        description: "User-specified list of prefix groups to advertise
                          in custom mode. This field can only be populated if advertiseMode
                          is CUSTOM and is advertised to all peers of the router.
                          These groups will be advertised in addition to any specified
                          prefixes. Leave this field blank to advertise no custom
                          groups. \n This enum field has the one valid value: ALL_SUBNETS"
                        items:
                          type: string
                        type: array
                      advertisedIPRanges:
                        description: User-specified list of individual IP ranges to
                          advertise in custom mode. This field can only be populated
                          if advertiseMode is CUSTOM and is advertised to all peers
                          of the router. These IP ranges will be advertised in addition
                          to any specified groups. Leave this field blank to advertise
                          no custom IP ranges.
                        items:
                          properties:
                            description:
                              description: User-specified description for the IP range.
                              type: string
                            range:
                              description: The IP range to advertise. The value must
                                be a CIDR-formatted string.
                              type: string
                          required:
                          - range
                          type: object
                        type: array
                      asn:
                        description: Local BGP Autonomous System Number (ASN). Must
                          be an RFC6996 private ASN, either 16-bit or 32-bit. The
                          value will be fixed for this router resource. All VPN tunnels
                          that link to this router will have the same local ASN.
                        format: int64
                        type: integer
                    required:
                    - asn
                    type: object
                  creationTimestamp:
                    description: Creation timestamp in RFC3339 text format.
                    type: string
                  description:
                    description: An optional description of this resource.
                    type: string
                  id:
                    type: string
                  name:
                    description: Name of the resource. The name must be 1-63 characters
                      long, and comply with RFC1035. Specifically, the name must be
                      1-63 characters long and match the regular expression '[a-z]([-a-z0-9]*[a-z0-9])?'
                      which means the first character must be a lowercase letter,
                      and all following characters must be a dash, lowercase letter,
                      or digit, except the last character, which cannot be a dash.
                    type: string
                  network:
                    description: A reference to the network to which this router belongs.
                    type: string
                  project:
                    type: string
                  region:
                    description: Region where the router resides.
                    type: string
                  selfLink:
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                required:
                - name
                - network
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  bgp:
                    description: BGP information specific to this router.
                    properties:
                      advertiseMode:
                        description: 'User-specified flag to indicate which mode to
                          use for advertisement. Default value: "DEFAULT" Possible
                          values: ["DEFAULT", "CUSTOM"]'
                        type: string
                      advertisedGroups:
                        description: "User-specified list of prefix groups to advertise
                          in custom mode. This field can only be populated if advertiseMode
                          is CUSTOM and is advertised to all peers of the router.
                          These groups will be advertised in addition to any specified
                          prefixes. Leave this field blank to advertise no custom
                          groups. \n This enum field has the one valid value: ALL_SUBNETS"
                        items:
                          type: string
                        type: array
                      advertisedIPRanges:
                        description: User-specified list of individual IP ranges to
                          advertise in custom mode. This field can only be populated
                          if advertiseMode is CUSTOM and is advertised to all peers
                          of the router. These IP ranges will be advertised in addition
                          to any specified groups. Leave this field blank to advertise
                          no custom IP ranges.
                        items:
                          properties:
                            description:
                              description: User-specified description for the IP range.
                              type: string
                            range:
                              description: The IP range to advertise. The value must
                                be a CIDR-formatted string.
                              type: string
                          required:
                          - range
                          type: object
                        type: array
                      asn:
                        description: Local BGP Autonomous System Number (ASN). Must
                          be an RFC6996 private ASN, either 16-bit or 32-bit. The
                          value will be fixed for this router resource. All VPN tunnels
                          that link to this router will have the same local ASN.
                        format: int64
                        type: integer
                    required:
                    - asn
                    type: object
                  creationTimestamp:
                    description: Creation timestamp in RFC3339 text format.
                    type: string
                  description:
                    description: An optional description of this resource.
                    type: string
                  id:
                    type: string
                  name:
                    description: Name of the resource. The name must be 1-63 characters
                      long, and comply with RFC1035. Specifically, the name must be
                      1-63 characters long and match the regular expression '[a-z]([-a-z0-9]*[a-z0-9])?'
                      which means the first character must be a lowercase letter,
                      and all following characters must be a dash, lowercase letter,
                      or digit, except the last character, which cannot be a dash.
                    type: string
                  network:
                    description: A reference to the network to which this router belongs.
                    type: string
                  project:
                    type: string
                  region:
                    description: Region where the router resides.
                    type: string
                  selfLink:
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                required:
                - name
                - network
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
