apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: google.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: analysisnotes.container.google.kubeform.com
spec:
  group: container.google.kubeform.com
  names:
    kind: AnalysisNote
    listKind: AnalysisNoteList
    plural: analysisnotes
    singular: analysisnote
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              kubeformOutput:
                properties:
                  attestationAuthority:
                    description: Note kind that represents a logical attestation "role"
                      or "authority". For example, an organization might have one
                      AttestationAuthority for "QA" and one for "build". This Note
                      is intended to act strictly as a grouping mechanism for the
                      attached Occurrences (Attestations). This grouping mechanism
                      also provides a security boundary, since IAM ACLs gate the ability
                      for a principle to attach an Occurrence to a given Note. It
                      also provides a single point of lookup to find all attached
                      Attestation Occurrences, even if they don't all live in the
                      same project.
                    properties:
                      hint:
                        description: This submessage provides human-readable hints
                          about the purpose of the AttestationAuthority. Because the
                          name of a Note acts as its resource reference, it is important
                          to disambiguate the canonical name of the Note (which might
                          be a UUID for security purposes) from "readable" names more
                          suitable for debug output. Note that these hints should
                          NOT be used to look up AttestationAuthorities in security
                          sensitive contexts, such as when looking up Attestations
                          to verify.
                        properties:
                          humanReadableName:
                            description: The human readable name of this Attestation
                              Authority, for example "qa".
                            type: string
                        required:
                        - humanReadableName
                        type: object
                    required:
                    - hint
                    type: object
                  createTime:
                    description: The time this note was created.
                    type: string
                  expirationTime:
                    description: Time of expiration for this note. Leave empty if
                      note does not expire.
                    type: string
                  id:
                    type: string
                  kind:
                    description: The type of analysis this note describes
                    type: string
                  longDescription:
                    description: A detailed description of the note
                    type: string
                  name:
                    description: The name of the note.
                    type: string
                  project:
                    type: string
                  relatedNoteNames:
                    description: Names of other notes related to this note.
                    items:
                      type: string
                    type: array
                  relatedURL:
                    description: URLs associated with this note and related metadata.
                    items:
                      properties:
                        label:
                          description: Label to describe usage of the URL
                          type: string
                        url:
                          description: Specific URL associated with the resource.
                          type: string
                      required:
                      - url
                      type: object
                    type: array
                  shortDescription:
                    description: A one sentence description of the note.
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  updateTime:
                    description: The time this note was last updated.
                    type: string
                required:
                - attestationAuthority
                - name
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  attestationAuthority:
                    description: Note kind that represents a logical attestation "role"
                      or "authority". For example, an organization might have one
                      AttestationAuthority for "QA" and one for "build". This Note
                      is intended to act strictly as a grouping mechanism for the
                      attached Occurrences (Attestations). This grouping mechanism
                      also provides a security boundary, since IAM ACLs gate the ability
                      for a principle to attach an Occurrence to a given Note. It
                      also provides a single point of lookup to find all attached
                      Attestation Occurrences, even if they don't all live in the
                      same project.
                    properties:
                      hint:
                        description: This submessage provides human-readable hints
                          about the purpose of the AttestationAuthority. Because the
                          name of a Note acts as its resource reference, it is important
                          to disambiguate the canonical name of the Note (which might
                          be a UUID for security purposes) from "readable" names more
                          suitable for debug output. Note that these hints should
                          NOT be used to look up AttestationAuthorities in security
                          sensitive contexts, such as when looking up Attestations
                          to verify.
                        properties:
                          humanReadableName:
                            description: The human readable name of this Attestation
                              Authority, for example "qa".
                            type: string
                        required:
                        - humanReadableName
                        type: object
                    required:
                    - hint
                    type: object
                  createTime:
                    description: The time this note was created.
                    type: string
                  expirationTime:
                    description: Time of expiration for this note. Leave empty if
                      note does not expire.
                    type: string
                  id:
                    type: string
                  kind:
                    description: The type of analysis this note describes
                    type: string
                  longDescription:
                    description: A detailed description of the note
                    type: string
                  name:
                    description: The name of the note.
                    type: string
                  project:
                    type: string
                  relatedNoteNames:
                    description: Names of other notes related to this note.
                    items:
                      type: string
                    type: array
                  relatedURL:
                    description: URLs associated with this note and related metadata.
                    items:
                      properties:
                        label:
                          description: Label to describe usage of the URL
                          type: string
                        url:
                          description: Specific URL associated with the resource.
                          type: string
                      required:
                      - url
                      type: object
                    type: array
                  shortDescription:
                    description: A one sentence description of the note.
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  updateTime:
                    description: The time this note was last updated.
                    type: string
                required:
                - attestationAuthority
                - name
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
