apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: google.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: jobs.dataflow.google.kubeform.com
spec:
  group: dataflow.google.kubeform.com
  names:
    kind: Job
    listKind: JobList
    plural: jobs
    singular: job
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              kubeformOutput:
                properties:
                  additionalExperiments:
                    description: List of experiments that should be used by the job.
                      An example value is ["enable_stackdriver_agent_metrics"].
                    items:
                      type: string
                    type: array
                  enableStreamingEngine:
                    description: Indicates if the job should use the streaming engine
                      feature.
                    type: boolean
                  id:
                    type: string
                  ipConfiguration:
                    description: The configuration for VM IPs. Options are "WORKER_IP_PUBLIC"
                      or "WORKER_IP_PRIVATE".
                    type: string
                  jobID:
                    description: The unique ID of this job.
                    type: string
                  kmsKeyName:
                    description: 'The name for the Cloud KMS key for the job. Key
                      format is: projects/PROJECT_ID/locations/LOCATION/keyRings/KEY_RING/cryptoKeys/KEY'
                    type: string
                  labels:
                    additionalProperties:
                      type: string
                    description: 'User labels to be specified for the job. Keys and
                      values should follow the restrictions specified in the labeling
                      restrictions page. NOTE: Google-provided Dataflow templates
                      often provide default labels that begin with goog-dataflow-provided.
                      Unless explicitly set in config, these labels will be ignored
                      to prevent diffs on re-apply.'
                    type: object
                  machineType:
                    description: The machine type to use for the job.
                    type: string
                  maxWorkers:
                    description: The number of workers permitted to work on the job.
                      More workers may improve processing speed at additional cost.
                    format: int64
                    type: integer
                  name:
                    description: A unique name for the resource, required by Dataflow.
                    type: string
                  network:
                    description: The network to which VMs will be assigned. If it
                      is not provided, "default" will be used.
                    type: string
                  onDelete:
                    description: One of "drain" or "cancel". Specifies behavior of
                      deletion during terraform destroy.
                    type: string
                  parameters:
                    additionalProperties:
                      type: string
                    description: Key/Value pairs to be passed to the Dataflow job
                      (as used in the template).
                    type: object
                  project:
                    description: The project in which the resource belongs.
                    type: string
                  region:
                    description: The region in which the created job should run.
                    type: string
                  serviceAccountEmail:
                    description: The Service Account email used to create the job.
                    type: string
                  state:
                    description: The current state of the resource, selected from
                      the JobState enum.
                    type: string
                  subnetwork:
                    description: The subnetwork to which VMs will be assigned. Should
                      be of the form "regions/REGION/subnetworks/SUBNETWORK".
                    type: string
                  tempGcsLocation:
                    description: A writeable location on Google Cloud Storage for
                      the Dataflow job to dump its temporary data.
                    type: string
                  templateGcsPath:
                    description: The Google Cloud Storage path to the Dataflow job
                      template.
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  transformNameMapping:
                    additionalProperties:
                      type: string
                    description: Only applicable when updating a pipeline. Map of
                      transform name prefixes of the job to be replaced with the corresponding
                      name prefixes of the new job.
                    type: object
                  type:
                    description: The type of this job, selected from the JobType enum.
                    type: string
                  zone:
                    description: The zone in which the created job should run. If
                      it is not provided, the provider zone is used.
                    type: string
                required:
                - name
                - tempGcsLocation
                - templateGcsPath
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  additionalExperiments:
                    description: List of experiments that should be used by the job.
                      An example value is ["enable_stackdriver_agent_metrics"].
                    items:
                      type: string
                    type: array
                  enableStreamingEngine:
                    description: Indicates if the job should use the streaming engine
                      feature.
                    type: boolean
                  id:
                    type: string
                  ipConfiguration:
                    description: The configuration for VM IPs. Options are "WORKER_IP_PUBLIC"
                      or "WORKER_IP_PRIVATE".
                    type: string
                  jobID:
                    description: The unique ID of this job.
                    type: string
                  kmsKeyName:
                    description: 'The name for the Cloud KMS key for the job. Key
                      format is: projects/PROJECT_ID/locations/LOCATION/keyRings/KEY_RING/cryptoKeys/KEY'
                    type: string
                  labels:
                    additionalProperties:
                      type: string
                    description: 'User labels to be specified for the job. Keys and
                      values should follow the restrictions specified in the labeling
                      restrictions page. NOTE: Google-provided Dataflow templates
                      often provide default labels that begin with goog-dataflow-provided.
                      Unless explicitly set in config, these labels will be ignored
                      to prevent diffs on re-apply.'
                    type: object
                  machineType:
                    description: The machine type to use for the job.
                    type: string
                  maxWorkers:
                    description: The number of workers permitted to work on the job.
                      More workers may improve processing speed at additional cost.
                    format: int64
                    type: integer
                  name:
                    description: A unique name for the resource, required by Dataflow.
                    type: string
                  network:
                    description: The network to which VMs will be assigned. If it
                      is not provided, "default" will be used.
                    type: string
                  onDelete:
                    description: One of "drain" or "cancel". Specifies behavior of
                      deletion during terraform destroy.
                    type: string
                  parameters:
                    additionalProperties:
                      type: string
                    description: Key/Value pairs to be passed to the Dataflow job
                      (as used in the template).
                    type: object
                  project:
                    description: The project in which the resource belongs.
                    type: string
                  region:
                    description: The region in which the created job should run.
                    type: string
                  serviceAccountEmail:
                    description: The Service Account email used to create the job.
                    type: string
                  state:
                    description: The current state of the resource, selected from
                      the JobState enum.
                    type: string
                  subnetwork:
                    description: The subnetwork to which VMs will be assigned. Should
                      be of the form "regions/REGION/subnetworks/SUBNETWORK".
                    type: string
                  tempGcsLocation:
                    description: A writeable location on Google Cloud Storage for
                      the Dataflow job to dump its temporary data.
                    type: string
                  templateGcsPath:
                    description: The Google Cloud Storage path to the Dataflow job
                      template.
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  transformNameMapping:
                    additionalProperties:
                      type: string
                    description: Only applicable when updating a pipeline. Map of
                      transform name prefixes of the job to be replaced with the corresponding
                      name prefixes of the new job.
                    type: object
                  type:
                    description: The type of this job, selected from the JobType enum.
                    type: string
                  zone:
                    description: The zone in which the created job should run. If
                      it is not provided, the provider zone is used.
                    type: string
                required:
                - name
                - tempGcsLocation
                - templateGcsPath
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
