apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: google.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: catalogtags.data.google.kubeform.com
spec:
  group: data.google.kubeform.com
  names:
    kind: CatalogTag
    listKind: CatalogTagList
    plural: catalogtags
    singular: catalogtag
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  column:
                    description: "Resources like Entry can have schemas associated
                      with them. This scope allows users to attach tags to an individual
                      column based on that schema. \n For attaching a tag to a nested
                      column, use '.' to separate the column names. Example: 'outer_column.inner_column'"
                    type: string
                  fields:
                    description: This maps the ID of a tag field to the value of and
                      additional information about that field. Valid field IDs are
                      defined by the tag's template. A tag must have at least 1 field
                      and at most 500 fields.
                    items:
                      properties:
                        boolValue:
                          description: Holds the value for a tag field with boolean
                            type.
                          type: boolean
                        displayName:
                          description: The display name of this field
                          type: string
                        doubleValue:
                          description: Holds the value for a tag field with double
                            type.
                          format: double
                          type: number
                        enumValue:
                          description: The display name of the enum value.
                          type: string
                        fieldName:
                          type: string
                        order:
                          description: The order of this field with respect to other
                            fields in this tag. For example, a higher value can indicate
                            a more important field. The value can be negative. Multiple
                            fields can have the same order, and field orders within
                            a tag do not have to be sequential.
                          format: int64
                          type: integer
                        stringValue:
                          description: Holds the value for a tag field with string
                            type.
                          type: string
                        timestampValue:
                          description: Holds the value for a tag field with timestamp
                            type.
                          type: string
                      required:
                      - fieldName
                      type: object
                    type: array
                  id:
                    type: string
                  name:
                    description: 'The resource name of the tag in URL format. Example:
                      projects/{project_id}/locations/{location}/entrygroups/{entryGroupId}/entries/{entryId}/tags/{tag_id}
                      or projects/{project_id}/locations/{location}/entrygroups/{entryGroupId}/tags/{tag_id}
                      where tag_id is a system-generated identifier. Note that this
                      Tag may not actually be stored in the location in this name.'
                    type: string
                  parent:
                    description: The name of the parent this tag is attached to. This
                      can be the name of an entry or an entry group. If an entry group,
                      the tag will be attached to all entries in that group.
                    type: string
                  template:
                    description: 'The resource name of the tag template that this
                      tag uses. Example: projects/{project_id}/locations/{location}/tagTemplates/{tagTemplateId}
                      This field cannot be modified after creation.'
                    type: string
                  templateDisplayname:
                    description: The display name of the tag template.
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                required:
                - fields
                - template
                type: object
              state:
                properties:
                  column:
                    description: "Resources like Entry can have schemas associated
                      with them. This scope allows users to attach tags to an individual
                      column based on that schema. \n For attaching a tag to a nested
                      column, use '.' to separate the column names. Example: 'outer_column.inner_column'"
                    type: string
                  fields:
                    description: This maps the ID of a tag field to the value of and
                      additional information about that field. Valid field IDs are
                      defined by the tag's template. A tag must have at least 1 field
                      and at most 500 fields.
                    items:
                      properties:
                        boolValue:
                          description: Holds the value for a tag field with boolean
                            type.
                          type: boolean
                        displayName:
                          description: The display name of this field
                          type: string
                        doubleValue:
                          description: Holds the value for a tag field with double
                            type.
                          format: double
                          type: number
                        enumValue:
                          description: The display name of the enum value.
                          type: string
                        fieldName:
                          type: string
                        order:
                          description: The order of this field with respect to other
                            fields in this tag. For example, a higher value can indicate
                            a more important field. The value can be negative. Multiple
                            fields can have the same order, and field orders within
                            a tag do not have to be sequential.
                          format: int64
                          type: integer
                        stringValue:
                          description: Holds the value for a tag field with string
                            type.
                          type: string
                        timestampValue:
                          description: Holds the value for a tag field with timestamp
                            type.
                          type: string
                      required:
                      - fieldName
                      type: object
                    type: array
                  id:
                    type: string
                  name:
                    description: 'The resource name of the tag in URL format. Example:
                      projects/{project_id}/locations/{location}/entrygroups/{entryGroupId}/entries/{entryId}/tags/{tag_id}
                      or projects/{project_id}/locations/{location}/entrygroups/{entryGroupId}/tags/{tag_id}
                      where tag_id is a system-generated identifier. Note that this
                      Tag may not actually be stored in the location in this name.'
                    type: string
                  parent:
                    description: The name of the parent this tag is attached to. This
                      can be the name of an entry or an entry group. If an entry group,
                      the tag will be attached to all entries in that group.
                    type: string
                  template:
                    description: 'The resource name of the tag template that this
                      tag uses. Example: projects/{project_id}/locations/{location}/tagTemplates/{tagTemplateId}
                      This field cannot be modified after creation.'
                    type: string
                  templateDisplayname:
                    description: The display name of the tag template.
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                required:
                - fields
                - template
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
