apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: google.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: cxagents.dialogflow.google.kubeform.com
spec:
  group: dialogflow.google.kubeform.com
  names:
    kind: CxAgent
    listKind: CxAgentList
    plural: cxagents
    singular: cxagent
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  avatarURI:
                    description: The URI of the agent's avatar. Avatars are used throughout
                      the Dialogflow console and in the self-hosted Web Demo integration.
                    type: string
                  defaultLanguageCode:
                    description: The default language of the agent as a language tag.
                      [See Language Support](https://cloud.google.com/dialogflow/cx/docs/reference/language)
                      for a list of the currently supported language codes. This field
                      cannot be updated after creation.
                    type: string
                  description:
                    description: The description of this agent. The maximum length
                      is 500 characters. If exceeded, the request is rejected.
                    type: string
                  displayName:
                    description: The human-readable name of the agent, unique within
                      the location.
                    type: string
                  enableSpellCorrection:
                    description: Indicates if automatic spell correction is enabled
                      in detect intent requests.
                    type: boolean
                  enableStackdriverLogging:
                    description: Determines whether this agent should log conversation
                      queries.
                    type: boolean
                  id:
                    type: string
                  location:
                    description: "The name of the location this agent is located in.
                      \n ~> **Note:** The first time you are deploying an Agent in
                      your project you must configure location settings.  This is
                      a one time step but at the moment you can only [configure location
                      settings](https://cloud.google.com/dialogflow/cx/docs/concept/region#location-settings)
                      via the Dialogflow CX console.  Another options is to use global
                      location so you don't need to manually configure location settings."
                    type: string
                  name:
                    description: The unique identifier of the agent.
                    type: string
                  project:
                    type: string
                  securitySettings:
                    description: 'Name of the SecuritySettings reference for the agent.
                      Format: projects/<Project ID>/locations/<Location ID>/securitySettings/<Security
                      Settings ID>.'
                    type: string
                  speechToTextSettings:
                    description: Settings related to speech recognition.
                    properties:
                      enableSpeechAdaptation:
                        description: Whether to use speech adaptation for speech recognition.
                        type: boolean
                    type: object
                  startFlow:
                    description: 'Name of the start flow in this agent. A start flow
                      will be automatically created when the agent is created, and
                      can only be deleted by deleting the agent. Format: projects/<Project
                      ID>/locations/<Location ID>/agents/<Agent ID>/flows/<Flow ID>.'
                    type: string
                  supportedLanguageCodes:
                    description: The list of all languages supported by this agent
                      (except for the default_language_code).
                    items:
                      type: string
                    type: array
                  timeZone:
                    description: The time zone of this agent from the [time zone database](https://www.iana.org/time-zones),
                      e.g., America/New_York, Europe/Paris.
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                required:
                - defaultLanguageCode
                - displayName
                - location
                - timeZone
                type: object
              state:
                properties:
                  avatarURI:
                    description: The URI of the agent's avatar. Avatars are used throughout
                      the Dialogflow console and in the self-hosted Web Demo integration.
                    type: string
                  defaultLanguageCode:
                    description: The default language of the agent as a language tag.
                      [See Language Support](https://cloud.google.com/dialogflow/cx/docs/reference/language)
                      for a list of the currently supported language codes. This field
                      cannot be updated after creation.
                    type: string
                  description:
                    description: The description of this agent. The maximum length
                      is 500 characters. If exceeded, the request is rejected.
                    type: string
                  displayName:
                    description: The human-readable name of the agent, unique within
                      the location.
                    type: string
                  enableSpellCorrection:
                    description: Indicates if automatic spell correction is enabled
                      in detect intent requests.
                    type: boolean
                  enableStackdriverLogging:
                    description: Determines whether this agent should log conversation
                      queries.
                    type: boolean
                  id:
                    type: string
                  location:
                    description: "The name of the location this agent is located in.
                      \n ~> **Note:** The first time you are deploying an Agent in
                      your project you must configure location settings.  This is
                      a one time step but at the moment you can only [configure location
                      settings](https://cloud.google.com/dialogflow/cx/docs/concept/region#location-settings)
                      via the Dialogflow CX console.  Another options is to use global
                      location so you don't need to manually configure location settings."
                    type: string
                  name:
                    description: The unique identifier of the agent.
                    type: string
                  project:
                    type: string
                  securitySettings:
                    description: 'Name of the SecuritySettings reference for the agent.
                      Format: projects/<Project ID>/locations/<Location ID>/securitySettings/<Security
                      Settings ID>.'
                    type: string
                  speechToTextSettings:
                    description: Settings related to speech recognition.
                    properties:
                      enableSpeechAdaptation:
                        description: Whether to use speech adaptation for speech recognition.
                        type: boolean
                    type: object
                  startFlow:
                    description: 'Name of the start flow in this agent. A start flow
                      will be automatically created when the agent is created, and
                      can only be deleted by deleting the agent. Format: projects/<Project
                      ID>/locations/<Location ID>/agents/<Agent ID>/flows/<Flow ID>.'
                    type: string
                  supportedLanguageCodes:
                    description: The list of all languages supported by this agent
                      (except for the default_language_code).
                    items:
                      type: string
                    type: array
                  timeZone:
                    description: The time zone of this agent from the [time zone database](https://www.iana.org/time-zones),
                      e.g., America/New_York, Europe/Paris.
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                required:
                - defaultLanguageCode
                - displayName
                - location
                - timeZone
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
