apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: google.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: entitytypes.dialogflow.google.kubeform.com
spec:
  group: dialogflow.google.kubeform.com
  names:
    kind: EntityType
    listKind: EntityTypeList
    plural: entitytypes
    singular: entitytype
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  displayName:
                    description: The name of this entity type to be displayed on the
                      console.
                    type: string
                  enableFuzzyExtraction:
                    description: Enables fuzzy entity extraction during classification.
                    type: boolean
                  entities:
                    description: The collection of entity entries associated with
                      the entity type.
                    items:
                      properties:
                        synonyms:
                          description: 'A collection of value synonyms. For example,
                            if the entity type is vegetable, and value is scallions,
                            a synonym could be green onions. For KIND_LIST entity
                            types: * This collection must contain exactly one synonym
                            equal to value.'
                          items:
                            type: string
                          type: array
                        value:
                          description: 'The primary value associated with this entity
                            entry. For example, if the entity type is vegetable, the
                            value could be scallions. For KIND_MAP entity types: *
                            A reference value to be used in place of synonyms. For
                            KIND_LIST entity types: * A string that can contain references
                            to other entity types (with or without aliases).'
                          type: string
                      required:
                      - synonyms
                      - value
                      type: object
                    type: array
                  id:
                    type: string
                  kind:
                    description: 'Indicates the kind of entity type. * KIND_MAP: Map
                      entity types allow mapping of a group of synonyms to a reference
                      value. * KIND_LIST: List entity types contain a set of entries
                      that do not map to reference values. However, list entity types
                      can contain references to other entity types (with or without
                      aliases). * KIND_REGEXP: Regexp entity types allow to specify
                      regular expressions in entries values. Possible values: ["KIND_MAP",
                      "KIND_LIST", "KIND_REGEXP"]'
                    type: string
                  name:
                    description: 'The unique identifier of the entity type. Format:
                      projects/<Project ID>/agent/entityTypes/<Entity type ID>.'
                    type: string
                  project:
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                required:
                - displayName
                - kind
                type: object
              state:
                properties:
                  displayName:
                    description: The name of this entity type to be displayed on the
                      console.
                    type: string
                  enableFuzzyExtraction:
                    description: Enables fuzzy entity extraction during classification.
                    type: boolean
                  entities:
                    description: The collection of entity entries associated with
                      the entity type.
                    items:
                      properties:
                        synonyms:
                          description: 'A collection of value synonyms. For example,
                            if the entity type is vegetable, and value is scallions,
                            a synonym could be green onions. For KIND_LIST entity
                            types: * This collection must contain exactly one synonym
                            equal to value.'
                          items:
                            type: string
                          type: array
                        value:
                          description: 'The primary value associated with this entity
                            entry. For example, if the entity type is vegetable, the
                            value could be scallions. For KIND_MAP entity types: *
                            A reference value to be used in place of synonyms. For
                            KIND_LIST entity types: * A string that can contain references
                            to other entity types (with or without aliases).'
                          type: string
                      required:
                      - synonyms
                      - value
                      type: object
                    type: array
                  id:
                    type: string
                  kind:
                    description: 'Indicates the kind of entity type. * KIND_MAP: Map
                      entity types allow mapping of a group of synonyms to a reference
                      value. * KIND_LIST: List entity types contain a set of entries
                      that do not map to reference values. However, list entity types
                      can contain references to other entity types (with or without
                      aliases). * KIND_REGEXP: Regexp entity types allow to specify
                      regular expressions in entries values. Possible values: ["KIND_MAP",
                      "KIND_LIST", "KIND_REGEXP"]'
                    type: string
                  name:
                    description: 'The unique identifier of the entity type. Format:
                      projects/<Project ID>/agent/entityTypes/<Entity type ID>.'
                    type: string
                  project:
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                required:
                - displayName
                - kind
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
