apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: google.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: services.endpoints.google.kubeform.com
spec:
  group: endpoints.google.kubeform.com
  names:
    kind: Service
    listKind: ServiceList
    plural: services
    singular: service
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              kubeformOutput:
                properties:
                  apis:
                    description: A list of API objects.
                    items:
                      properties:
                        methods:
                          description: A list of Method objects.
                          items:
                            properties:
                              name:
                                description: The simple name of this method as described
                                  in the provided config.
                                type: string
                              requestType:
                                description: The type URL for the request to this
                                  API.
                                type: string
                              responseType:
                                description: The type URL for the response from this
                                  API.
                                type: string
                              syntax:
                                description: SYNTAX_PROTO2 or SYNTAX_PROTO3.
                                type: string
                            type: object
                          type: array
                        name:
                          description: The FQDN of the API as described in the provided
                            config.
                          type: string
                        syntax:
                          description: SYNTAX_PROTO2 or SYNTAX_PROTO3.
                          type: string
                        version:
                          description: A version string for this api. If specified,
                            will have the form major-version.minor-version, e.g. 1.10.
                          type: string
                      type: object
                    type: array
                  configID:
                    description: The autogenerated ID for the configuration that is
                      rolled out as part of the creation of this resource. Must be
                      provided to compute engine instances as a tag.
                    type: string
                  dnsAddress:
                    description: The address at which the service can be found - usually
                      the same as the service name.
                    type: string
                  endpoints:
                    description: A list of Endpoint objects.
                    items:
                      properties:
                        address:
                          description: The FQDN of the endpoint as described in the
                            config.
                          type: string
                        name:
                          description: The simple name of the endpoint as described
                            in the config.
                          type: string
                      type: object
                    type: array
                  grpcConfig:
                    description: The full text of the Service Config YAML file (Example
                      located here). If provided, must also provide protoc_output_base64.
                      open_api config must not be provided.
                    type: string
                  id:
                    type: string
                  openapiConfig:
                    description: The full text of the OpenAPI YAML configuration as
                      described here. Either this, or both of grpc_config and protoc_output_base64
                      must be specified.
                    type: string
                  project:
                    description: The project ID that the service belongs to. If not
                      provided, provider project is used.
                    type: string
                  protocOutputBase64:
                    description: The full contents of the Service Descriptor File
                      generated by protoc. This should be a compiled .pb file, base64-encoded.
                    type: string
                  serviceName:
                    description: The name of the service. Usually of the form $apiname.endpoints.$projectid.cloud.goog.
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                required:
                - serviceName
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  apis:
                    description: A list of API objects.
                    items:
                      properties:
                        methods:
                          description: A list of Method objects.
                          items:
                            properties:
                              name:
                                description: The simple name of this method as described
                                  in the provided config.
                                type: string
                              requestType:
                                description: The type URL for the request to this
                                  API.
                                type: string
                              responseType:
                                description: The type URL for the response from this
                                  API.
                                type: string
                              syntax:
                                description: SYNTAX_PROTO2 or SYNTAX_PROTO3.
                                type: string
                            type: object
                          type: array
                        name:
                          description: The FQDN of the API as described in the provided
                            config.
                          type: string
                        syntax:
                          description: SYNTAX_PROTO2 or SYNTAX_PROTO3.
                          type: string
                        version:
                          description: A version string for this api. If specified,
                            will have the form major-version.minor-version, e.g. 1.10.
                          type: string
                      type: object
                    type: array
                  configID:
                    description: The autogenerated ID for the configuration that is
                      rolled out as part of the creation of this resource. Must be
                      provided to compute engine instances as a tag.
                    type: string
                  dnsAddress:
                    description: The address at which the service can be found - usually
                      the same as the service name.
                    type: string
                  endpoints:
                    description: A list of Endpoint objects.
                    items:
                      properties:
                        address:
                          description: The FQDN of the endpoint as described in the
                            config.
                          type: string
                        name:
                          description: The simple name of the endpoint as described
                            in the config.
                          type: string
                      type: object
                    type: array
                  grpcConfig:
                    description: The full text of the Service Config YAML file (Example
                      located here). If provided, must also provide protoc_output_base64.
                      open_api config must not be provided.
                    type: string
                  id:
                    type: string
                  openapiConfig:
                    description: The full text of the OpenAPI YAML configuration as
                      described here. Either this, or both of grpc_config and protoc_output_base64
                      must be specified.
                    type: string
                  project:
                    description: The project ID that the service belongs to. If not
                      provided, provider project is used.
                    type: string
                  protocOutputBase64:
                    description: The full contents of the Service Descriptor File
                      generated by protoc. This should be a compiled .pb file, base64-encoded.
                    type: string
                  serviceName:
                    description: The name of the service. Usually of the form $apiname.endpoints.$projectid.cloud.goog.
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                required:
                - serviceName
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
