apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: google.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: instances.filestore.google.kubeform.com
spec:
  group: filestore.google.kubeform.com
  names:
    kind: Instance
    listKind: InstanceList
    plural: instances
    singular: instance
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  createTime:
                    description: Creation timestamp in RFC3339 text format.
                    type: string
                  description:
                    description: A description of the instance.
                    type: string
                  etag:
                    description: Server-specified ETag for the instance resource to
                      prevent simultaneous updates from overwriting each other.
                    type: string
                  fileShares:
                    description: File system shares on the instance. For this version,
                      only a single file share is supported.
                    properties:
                      capacityGb:
                        description: File share capacity in GiB. This must be at least
                          1024 GiB for the standard tier, or 2560 GiB for the premium
                          tier.
                        format: int64
                        type: integer
                      name:
                        description: The name of the fileshare (16 characters or less)
                        type: string
                    required:
                    - capacityGb
                    - name
                    type: object
                  id:
                    type: string
                  labels:
                    additionalProperties:
                      type: string
                    description: Resource labels to represent user-provided metadata.
                    type: object
                  name:
                    description: The resource name of the instance.
                    type: string
                  networks:
                    description: VPC networks to which the instance is connected.
                      For this version, only a single network is supported.
                    items:
                      properties:
                        ipAddresses:
                          description: A list of IPv4 or IPv6 addresses.
                          items:
                            type: string
                          type: array
                        modes:
                          description: 'IP versions for which the instance has IP
                            addresses assigned. Possible values: ["ADDRESS_MODE_UNSPECIFIED",
                            "MODE_IPV4", "MODE_IPV6"]'
                          items:
                            type: string
                          type: array
                        network:
                          description: The name of the GCE VPC network to which the
                            instance is connected.
                          type: string
                        reservedIPRange:
                          description: A /29 CIDR block that identifies the range
                            of IP addresses reserved for this instance.
                          type: string
                      required:
                      - modes
                      - network
                      type: object
                    minItems: 1
                    type: array
                  project:
                    type: string
                  tier:
                    description: 'The service tier of the instance. Possible values:
                      ["TIER_UNSPECIFIED", "STANDARD", "PREMIUM", "BASIC_HDD", "BASIC_SSD",
                      "HIGH_SCALE_SSD"]'
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  zone:
                    description: The name of the Filestore zone of the instance.
                    type: string
                required:
                - fileShares
                - name
                - networks
                - tier
                - zone
                type: object
              state:
                properties:
                  createTime:
                    description: Creation timestamp in RFC3339 text format.
                    type: string
                  description:
                    description: A description of the instance.
                    type: string
                  etag:
                    description: Server-specified ETag for the instance resource to
                      prevent simultaneous updates from overwriting each other.
                    type: string
                  fileShares:
                    description: File system shares on the instance. For this version,
                      only a single file share is supported.
                    properties:
                      capacityGb:
                        description: File share capacity in GiB. This must be at least
                          1024 GiB for the standard tier, or 2560 GiB for the premium
                          tier.
                        format: int64
                        type: integer
                      name:
                        description: The name of the fileshare (16 characters or less)
                        type: string
                    required:
                    - capacityGb
                    - name
                    type: object
                  id:
                    type: string
                  labels:
                    additionalProperties:
                      type: string
                    description: Resource labels to represent user-provided metadata.
                    type: object
                  name:
                    description: The resource name of the instance.
                    type: string
                  networks:
                    description: VPC networks to which the instance is connected.
                      For this version, only a single network is supported.
                    items:
                      properties:
                        ipAddresses:
                          description: A list of IPv4 or IPv6 addresses.
                          items:
                            type: string
                          type: array
                        modes:
                          description: 'IP versions for which the instance has IP
                            addresses assigned. Possible values: ["ADDRESS_MODE_UNSPECIFIED",
                            "MODE_IPV4", "MODE_IPV6"]'
                          items:
                            type: string
                          type: array
                        network:
                          description: The name of the GCE VPC network to which the
                            instance is connected.
                          type: string
                        reservedIPRange:
                          description: A /29 CIDR block that identifies the range
                            of IP addresses reserved for this instance.
                          type: string
                      required:
                      - modes
                      - network
                      type: object
                    minItems: 1
                    type: array
                  project:
                    type: string
                  tier:
                    description: 'The service tier of the instance. Possible values:
                      ["TIER_UNSPECIFIED", "STANDARD", "PREMIUM", "BASIC_HDD", "BASIC_SSD",
                      "HIGH_SCALE_SSD"]'
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  zone:
                    description: The name of the Filestore zone of the instance.
                    type: string
                required:
                - fileShares
                - name
                - networks
                - tier
                - zone
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
