apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: google.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: organizationpolicies.folder.google.kubeform.com
spec:
  group: folder.google.kubeform.com
  names:
    kind: OrganizationPolicy
    listKind: OrganizationPolicyList
    plural: organizationpolicies
    singular: organizationpolicy
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  booleanPolicy:
                    description: A boolean policy is a constraint that is either enforced
                      or not.
                    properties:
                      enforced:
                        description: If true, then the Policy is enforced. If false,
                          then any configuration is acceptable.
                        type: boolean
                    required:
                    - enforced
                    type: object
                  constraint:
                    description: The name of the Constraint the Policy is configuring,
                      for example, serviceuser.services.
                    type: string
                  etag:
                    description: The etag of the organization policy. etag is used
                      for optimistic concurrency control as a way to help prevent
                      simultaneous updates of a policy from overwriting each other.
                    type: string
                  folder:
                    description: The resource name of the folder to set the policy
                      for. Its format is folders/{folder_id}.
                    type: string
                  id:
                    type: string
                  listPolicy:
                    description: A policy that can define specific values that are
                      allowed or denied for the given constraint. It can also be used
                      to allow or deny all values.
                    properties:
                      allow:
                        description: One or the other must be set.
                        properties:
                          all:
                            description: The policy allows or denies all values.
                            type: boolean
                          values:
                            description: The policy can define specific values that
                              are allowed or denied.
                            items:
                              type: string
                            type: array
                        type: object
                      deny:
                        description: One or the other must be set.
                        properties:
                          all:
                            description: The policy allows or denies all values.
                            type: boolean
                          values:
                            description: The policy can define specific values that
                              are allowed or denied.
                            items:
                              type: string
                            type: array
                        type: object
                      inheritFromParent:
                        description: If set to true, the values from the effective
                          Policy of the parent resource are inherited, meaning the
                          values set in this Policy are added to the values inherited
                          up the hierarchy.
                        type: boolean
                      suggestedValue:
                        description: The Google Cloud Console will try to default
                          to a configuration that matches the value specified in this
                          field.
                        type: string
                    type: object
                  restorePolicy:
                    description: A restore policy is a constraint to restore the default
                      policy.
                    properties:
                      default:
                        description: May only be set to true. If set, then the default
                          Policy is restored.
                        type: boolean
                    required:
                    - default
                    type: object
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  updateTime:
                    description: 'The timestamp in RFC3339 UTC "Zulu" format, accurate
                      to nanoseconds, representing when the variable was last updated.
                      Example: "2016-10-09T12:33:37.578138407Z".'
                    type: string
                  version:
                    description: Version of the Policy. Default version is 0.
                    format: int64
                    type: integer
                required:
                - constraint
                - folder
                type: object
              state:
                properties:
                  booleanPolicy:
                    description: A boolean policy is a constraint that is either enforced
                      or not.
                    properties:
                      enforced:
                        description: If true, then the Policy is enforced. If false,
                          then any configuration is acceptable.
                        type: boolean
                    required:
                    - enforced
                    type: object
                  constraint:
                    description: The name of the Constraint the Policy is configuring,
                      for example, serviceuser.services.
                    type: string
                  etag:
                    description: The etag of the organization policy. etag is used
                      for optimistic concurrency control as a way to help prevent
                      simultaneous updates of a policy from overwriting each other.
                    type: string
                  folder:
                    description: The resource name of the folder to set the policy
                      for. Its format is folders/{folder_id}.
                    type: string
                  id:
                    type: string
                  listPolicy:
                    description: A policy that can define specific values that are
                      allowed or denied for the given constraint. It can also be used
                      to allow or deny all values.
                    properties:
                      allow:
                        description: One or the other must be set.
                        properties:
                          all:
                            description: The policy allows or denies all values.
                            type: boolean
                          values:
                            description: The policy can define specific values that
                              are allowed or denied.
                            items:
                              type: string
                            type: array
                        type: object
                      deny:
                        description: One or the other must be set.
                        properties:
                          all:
                            description: The policy allows or denies all values.
                            type: boolean
                          values:
                            description: The policy can define specific values that
                              are allowed or denied.
                            items:
                              type: string
                            type: array
                        type: object
                      inheritFromParent:
                        description: If set to true, the values from the effective
                          Policy of the parent resource are inherited, meaning the
                          values set in this Policy are added to the values inherited
                          up the hierarchy.
                        type: boolean
                      suggestedValue:
                        description: The Google Cloud Console will try to default
                          to a configuration that matches the value specified in this
                          field.
                        type: string
                    type: object
                  restorePolicy:
                    description: A restore policy is a constraint to restore the default
                      policy.
                    properties:
                      default:
                        description: May only be set to true. If set, then the default
                          Policy is restored.
                        type: boolean
                    required:
                    - default
                    type: object
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  updateTime:
                    description: 'The timestamp in RFC3339 UTC "Zulu" format, accurate
                      to nanoseconds, representing when the variable was last updated.
                      Example: "2016-10-09T12:33:37.578138407Z".'
                    type: string
                  version:
                    description: Version of the Policy. Default version is 0.
                    format: int64
                    type: integer
                required:
                - constraint
                - folder
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
