apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: google.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: accessapprovalsettings.folder.google.kubeform.com
spec:
  group: folder.google.kubeform.com
  names:
    kind: AccessApprovalSettings
    listKind: AccessApprovalSettingsList
    plural: accessapprovalsettings
    singular: accessapprovalsettings
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  enrolledAncestor:
                    description: If the field is true, that indicates that at least
                      one service is enrolled for Access Approval in one or more ancestors
                      of the Folder.
                    type: boolean
                  enrolledServices:
                    description: "A list of Google Cloud Services for which the given
                      resource has Access Approval enrolled. Access requests for the
                      resource given by name against any of these services contained
                      here will be required to have explicit approval. Enrollment
                      can only be done on an all or nothing basis. \n A maximum of
                      10 enrolled services will be enforced, to be expanded as the
                      set of supported services is expanded."
                    items:
                      properties:
                        cloudProduct:
                          description: "The product for which Access Approval will
                            be enrolled. Allowed values are listed (case-sensitive):
                            \  * all   * App Engine   * BigQuery   * Cloud Bigtable
                            \  * Cloud Key Management Service   * Compute Engine   *
                            Cloud Dataflow   * Cloud Identity and Access Management
                            \  * Cloud Pub/Sub   * Cloud Storage   * Persistent Disk
                            \n Note: These values are supported as input, but considered
                            a legacy format:   * all   * appengine.googleapis.com
                            \  * bigquery.googleapis.com   * bigtable.googleapis.com
                            \  * cloudkms.googleapis.com   * compute.googleapis.com
                            \  * dataflow.googleapis.com   * iam.googleapis.com   *
                            pubsub.googleapis.com   * storage.googleapis.com"
                          type: string
                        enrollmentLevel:
                          description: 'The enrollment level of the service. Default
                            value: "BLOCK_ALL" Possible values: ["BLOCK_ALL"]'
                          type: string
                      required:
                      - cloudProduct
                      type: object
                    type: array
                  folderID:
                    description: ID of the folder of the access approval settings.
                    type: string
                  id:
                    type: string
                  name:
                    description: The resource name of the settings. Format is "folders/{folder_id}/accessApprovalSettings"
                    type: string
                  notificationEmails:
                    description: A list of email addresses to which notifications
                      relating to approval requests should be sent. Notifications
                      relating to a resource will be sent to all emails in the settings
                      of ancestor resources of that resource. A maximum of 50 email
                      addresses are allowed.
                    items:
                      type: string
                    maxItems: 50
                    type: array
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                required:
                - enrolledServices
                - folderID
                type: object
              state:
                properties:
                  enrolledAncestor:
                    description: If the field is true, that indicates that at least
                      one service is enrolled for Access Approval in one or more ancestors
                      of the Folder.
                    type: boolean
                  enrolledServices:
                    description: "A list of Google Cloud Services for which the given
                      resource has Access Approval enrolled. Access requests for the
                      resource given by name against any of these services contained
                      here will be required to have explicit approval. Enrollment
                      can only be done on an all or nothing basis. \n A maximum of
                      10 enrolled services will be enforced, to be expanded as the
                      set of supported services is expanded."
                    items:
                      properties:
                        cloudProduct:
                          description: "The product for which Access Approval will
                            be enrolled. Allowed values are listed (case-sensitive):
                            \  * all   * App Engine   * BigQuery   * Cloud Bigtable
                            \  * Cloud Key Management Service   * Compute Engine   *
                            Cloud Dataflow   * Cloud Identity and Access Management
                            \  * Cloud Pub/Sub   * Cloud Storage   * Persistent Disk
                            \n Note: These values are supported as input, but considered
                            a legacy format:   * all   * appengine.googleapis.com
                            \  * bigquery.googleapis.com   * bigtable.googleapis.com
                            \  * cloudkms.googleapis.com   * compute.googleapis.com
                            \  * dataflow.googleapis.com   * iam.googleapis.com   *
                            pubsub.googleapis.com   * storage.googleapis.com"
                          type: string
                        enrollmentLevel:
                          description: 'The enrollment level of the service. Default
                            value: "BLOCK_ALL" Possible values: ["BLOCK_ALL"]'
                          type: string
                      required:
                      - cloudProduct
                      type: object
                    type: array
                  folderID:
                    description: ID of the folder of the access approval settings.
                    type: string
                  id:
                    type: string
                  name:
                    description: The resource name of the settings. Format is "folders/{folder_id}/accessApprovalSettings"
                    type: string
                  notificationEmails:
                    description: A list of email addresses to which notifications
                      relating to approval requests should be sent. Notifications
                      relating to a resource will be sent to all emails in the settings
                      of ancestor resources of that resource. A maximum of 50 email
                      addresses are allowed.
                    items:
                      type: string
                    maxItems: 50
                    type: array
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                required:
                - enrolledServices
                - folderID
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
