apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: google.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: servicesgameserverclusters.game.google.kubeform.com
spec:
  group: game.google.kubeform.com
  names:
    kind: ServicesGameServerCluster
    listKind: ServicesGameServerClusterList
    plural: servicesgameserverclusters
    singular: servicesgameservercluster
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  clusterID:
                    description: Required. The resource name of the game server cluster
                    type: string
                  connectionInfo:
                    description: Game server cluster connection information. This
                      information is used to manage game server clusters.
                    properties:
                      gkeClusterReference:
                        description: Reference of the GKE cluster where the game servers
                          are installed.
                        properties:
                          cluster:
                            description: "The full or partial name of a GKE cluster,
                              using one of the following forms: \n * 'projects/{project_id}/locations/{location}/clusters/{cluster_id}'
                              * 'locations/{location}/clusters/{cluster_id}' * '{cluster_id}'
                              \n If project and location are not specified, the project
                              and location of the GameServerCluster resource are used
                              to generate the full name of the GKE cluster."
                            type: string
                        required:
                        - cluster
                        type: object
                      namespace:
                        description: Namespace designated on the game server cluster
                          where the game server instances will be created. The namespace
                          existence will be validated during creation.
                        type: string
                    required:
                    - gkeClusterReference
                    - namespace
                    type: object
                  description:
                    description: Human readable description of the cluster.
                    type: string
                  id:
                    type: string
                  labels:
                    additionalProperties:
                      type: string
                    description: The labels associated with this game server cluster.
                      Each label is a key-value pair.
                    type: object
                  location:
                    description: Location of the Cluster.
                    type: string
                  name:
                    description: "The resource id of the game server cluster, eg:
                      \n 'projects/{project_id}/locations/{location}/realms/{realm_id}/gameServerClusters/{cluster_id}'.
                      For example, \n 'projects/my-project/locations/{location}/realms/zanzibar/gameServerClusters/my-onprem-cluster'."
                    type: string
                  project:
                    type: string
                  realmID:
                    description: The realm id of the game server realm.
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                required:
                - clusterID
                - connectionInfo
                - realmID
                type: object
              state:
                properties:
                  clusterID:
                    description: Required. The resource name of the game server cluster
                    type: string
                  connectionInfo:
                    description: Game server cluster connection information. This
                      information is used to manage game server clusters.
                    properties:
                      gkeClusterReference:
                        description: Reference of the GKE cluster where the game servers
                          are installed.
                        properties:
                          cluster:
                            description: "The full or partial name of a GKE cluster,
                              using one of the following forms: \n * 'projects/{project_id}/locations/{location}/clusters/{cluster_id}'
                              * 'locations/{location}/clusters/{cluster_id}' * '{cluster_id}'
                              \n If project and location are not specified, the project
                              and location of the GameServerCluster resource are used
                              to generate the full name of the GKE cluster."
                            type: string
                        required:
                        - cluster
                        type: object
                      namespace:
                        description: Namespace designated on the game server cluster
                          where the game server instances will be created. The namespace
                          existence will be validated during creation.
                        type: string
                    required:
                    - gkeClusterReference
                    - namespace
                    type: object
                  description:
                    description: Human readable description of the cluster.
                    type: string
                  id:
                    type: string
                  labels:
                    additionalProperties:
                      type: string
                    description: The labels associated with this game server cluster.
                      Each label is a key-value pair.
                    type: object
                  location:
                    description: Location of the Cluster.
                    type: string
                  name:
                    description: "The resource id of the game server cluster, eg:
                      \n 'projects/{project_id}/locations/{location}/realms/{realm_id}/gameServerClusters/{cluster_id}'.
                      For example, \n 'projects/my-project/locations/{location}/realms/zanzibar/gameServerClusters/my-onprem-cluster'."
                    type: string
                  project:
                    type: string
                  realmID:
                    description: The realm id of the game server realm.
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                required:
                - clusterID
                - connectionInfo
                - realmID
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
