apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: google.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: servicesgameserverdeploymentrollouts.game.google.kubeform.com
spec:
  group: game.google.kubeform.com
  names:
    kind: ServicesGameServerDeploymentRollout
    listKind: ServicesGameServerDeploymentRolloutList
    plural: servicesgameserverdeploymentrollouts
    singular: servicesgameserverdeploymentrollout
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  defaultGameServerConfig:
                    description: "This field points to the game server config that
                      is applied by default to all realms and clusters. For example,
                      \n 'projects/my-project/locations/global/gameServerDeployments/my-game/configs/my-config'."
                    type: string
                  deploymentID:
                    description: The deployment to rollout the new config to. Only
                      1 rollout must be associated with each deployment.
                    type: string
                  gameServerConfigOverrides:
                    description: The game_server_config_overrides contains the per
                      game server config overrides. The overrides are processed in
                      the order they are listed. As soon as a match is found for a
                      cluster, the rest of the list is not processed.
                    items:
                      properties:
                        configVersion:
                          description: Version of the configuration.
                          type: string
                        realmsSelector:
                          description: Selection by realms.
                          properties:
                            realms:
                              description: List of realms to match against.
                              items:
                                type: string
                              type: array
                          type: object
                      type: object
                    type: array
                  id:
                    type: string
                  name:
                    description: "The resource id of the game server deployment \n
                      eg: 'projects/my-project/locations/global/gameServerDeployments/my-deployment/rollout'."
                    type: string
                  project:
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                required:
                - defaultGameServerConfig
                - deploymentID
                type: object
              state:
                properties:
                  defaultGameServerConfig:
                    description: "This field points to the game server config that
                      is applied by default to all realms and clusters. For example,
                      \n 'projects/my-project/locations/global/gameServerDeployments/my-game/configs/my-config'."
                    type: string
                  deploymentID:
                    description: The deployment to rollout the new config to. Only
                      1 rollout must be associated with each deployment.
                    type: string
                  gameServerConfigOverrides:
                    description: The game_server_config_overrides contains the per
                      game server config overrides. The overrides are processed in
                      the order they are listed. As soon as a match is found for a
                      cluster, the rest of the list is not processed.
                    items:
                      properties:
                        configVersion:
                          description: Version of the configuration.
                          type: string
                        realmsSelector:
                          description: Selection by realms.
                          properties:
                            realms:
                              description: List of realms to match against.
                              items:
                                type: string
                              type: array
                          type: object
                      type: object
                    type: array
                  id:
                    type: string
                  name:
                    description: "The resource id of the game server deployment \n
                      eg: 'projects/my-project/locations/global/gameServerDeployments/my-deployment/rollout'."
                    type: string
                  project:
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                required:
                - defaultGameServerConfig
                - deploymentID
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
