apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: google.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: hubmemberships.gke.google.kubeform.com
spec:
  group: gke.google.kubeform.com
  names:
    kind: HubMembership
    listKind: HubMembershipList
    plural: hubmemberships
    singular: hubmembership
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  authority:
                    description: 'Authority encodes how Google will recognize identities
                      from this Membership. See the workload identity documentation
                      for more details: https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity'
                    properties:
                      issuer:
                        description: 'A JSON Web Token (JWT) issuer URI. ''issuer''
                          must start with ''https://'' and // be a valid with length
                          <2000 characters. For example: ''https://container.googleapis.com/v1/projects/my-project/locations/us-west1/clusters/my-cluster''
                          (must be ''locations'' rather than ''zones''). If the cluster
                          is provisioned with Terraform, this is ''"https://container.googleapis.com/v1/${google_container_cluster.my-cluster.id}"''.'
                        type: string
                    required:
                    - issuer
                    type: object
                  endpoint:
                    description: If this Membership is a Kubernetes API server hosted
                      on GKE, this is a self link to its GCP resource.
                    properties:
                      gkeCluster:
                        description: If this Membership is a Kubernetes API server
                          hosted on GKE, this is a self link to its GCP resource.
                        properties:
                          resourceLink:
                            description: 'Self-link of the GCP resource for the GKE
                              cluster. For example: ''//container.googleapis.com/projects/my-project/zones/us-west1-a/clusters/my-cluster''.
                              It can be at the most 1000 characters in length. If
                              the cluster is provisioned with Terraform, this can
                              be ''"//container.googleapis.com/${google_container_cluster.my-cluster.id}"''
                              or ''google_container_cluster.my-cluster.id''.'
                            type: string
                        required:
                        - resourceLink
                        type: object
                    type: object
                  id:
                    type: string
                  labels:
                    additionalProperties:
                      type: string
                    description: Labels to apply to this membership.
                    type: object
                  membershipID:
                    description: The client-provided identifier of the membership.
                    type: string
                  name:
                    description: The unique identifier of the membership.
                    type: string
                  project:
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                required:
                - membershipID
                type: object
              state:
                properties:
                  authority:
                    description: 'Authority encodes how Google will recognize identities
                      from this Membership. See the workload identity documentation
                      for more details: https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity'
                    properties:
                      issuer:
                        description: 'A JSON Web Token (JWT) issuer URI. ''issuer''
                          must start with ''https://'' and // be a valid with length
                          <2000 characters. For example: ''https://container.googleapis.com/v1/projects/my-project/locations/us-west1/clusters/my-cluster''
                          (must be ''locations'' rather than ''zones''). If the cluster
                          is provisioned with Terraform, this is ''"https://container.googleapis.com/v1/${google_container_cluster.my-cluster.id}"''.'
                        type: string
                    required:
                    - issuer
                    type: object
                  endpoint:
                    description: If this Membership is a Kubernetes API server hosted
                      on GKE, this is a self link to its GCP resource.
                    properties:
                      gkeCluster:
                        description: If this Membership is a Kubernetes API server
                          hosted on GKE, this is a self link to its GCP resource.
                        properties:
                          resourceLink:
                            description: 'Self-link of the GCP resource for the GKE
                              cluster. For example: ''//container.googleapis.com/projects/my-project/zones/us-west1-a/clusters/my-cluster''.
                              It can be at the most 1000 characters in length. If
                              the cluster is provisioned with Terraform, this can
                              be ''"//container.googleapis.com/${google_container_cluster.my-cluster.id}"''
                              or ''google_container_cluster.my-cluster.id''.'
                            type: string
                        required:
                        - resourceLink
                        type: object
                    type: object
                  id:
                    type: string
                  labels:
                    additionalProperties:
                      type: string
                    description: Labels to apply to this membership.
                    type: object
                  membershipID:
                    description: The client-provided identifier of the membership.
                    type: string
                  name:
                    description: The unique identifier of the membership.
                    type: string
                  project:
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                required:
                - membershipID
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
