apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: google.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: projectsinks.logging.google.kubeform.com
spec:
  group: logging.google.kubeform.com
  names:
    kind: ProjectSink
    listKind: ProjectSinkList
    plural: projectsinks
    singular: projectsink
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              kubeformOutput:
                properties:
                  bigqueryOptions:
                    description: Options that affect sinks exporting data to BigQuery.
                    properties:
                      usePartitionedTables:
                        description: Whether to use BigQuery's partition tables. By
                          default, Logging creates dated tables based on the log entries'
                          timestamps, e.g. syslog_20170523. With partitioned tables
                          the date suffix is no longer present and special query syntax
                          has to be used instead. In both cases, tables are sharded
                          based on UTC timezone.
                        type: boolean
                    required:
                    - usePartitionedTables
                    type: object
                  description:
                    description: A description of this sink. The maximum length of
                      the description is 8000 characters.
                    type: string
                  destination:
                    description: 'The destination of the sink (or, in other words,
                      where logs are written to). Can be a Cloud Storage bucket, a
                      PubSub topic, or a BigQuery dataset. Examples: "storage.googleapis.com/[GCS_BUCKET]"
                      "bigquery.googleapis.com/projects/[PROJECT_ID]/datasets/[DATASET]"
                      "pubsub.googleapis.com/projects/[PROJECT_ID]/topics/[TOPIC_ID]"
                      The writer associated with the sink must have access to write
                      to the above resource.'
                    type: string
                  disabled:
                    description: If set to True, then this sink is disabled and it
                      does not export any log entries.
                    type: boolean
                  exclusions:
                    description: Log entries that match any of the exclusion filters
                      will not be exported. If a log entry is matched by both filter
                      and one of exclusion_filters it will not be exported.
                    items:
                      properties:
                        description:
                          description: A description of this exclusion.
                          type: string
                        disabled:
                          description: If set to True, then this exclusion is disabled
                            and it does not exclude any log entries
                          type: boolean
                        filter:
                          description: An advanced logs filter that matches the log
                            entries to be excluded. By using the sample function,
                            you can exclude less than 100% of the matching log entries
                          type: string
                        name:
                          description: A client-assigned identifier, such as "load-balancer-exclusion".
                            Identifiers are limited to 100 characters and can include
                            only letters, digits, underscores, hyphens, and periods.
                            First character has to be alphanumeric.
                          type: string
                      required:
                      - filter
                      - name
                      type: object
                    type: array
                  filter:
                    description: The filter to apply when exporting logs. Only log
                      entries that match the filter are exported.
                    type: string
                  id:
                    type: string
                  name:
                    description: The name of the logging sink.
                    type: string
                  project:
                    description: The ID of the project to create the sink in. If omitted,
                      the project associated with the provider is used.
                    type: string
                  uniqueWriterIdentity:
                    description: Whether or not to create a unique identity associated
                      with this sink. If false (the default), then the writer_identity
                      used is serviceAccount:cloud-logs@system.gserviceaccount.com.
                      If true, then a unique service account is created and used for
                      this sink. If you wish to publish logs across projects, you
                      must set unique_writer_identity to true.
                    type: boolean
                  writerIdentity:
                    description: The identity associated with this sink. This identity
                      must be granted write access to the configured destination.
                    type: string
                required:
                - destination
                - name
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  bigqueryOptions:
                    description: Options that affect sinks exporting data to BigQuery.
                    properties:
                      usePartitionedTables:
                        description: Whether to use BigQuery's partition tables. By
                          default, Logging creates dated tables based on the log entries'
                          timestamps, e.g. syslog_20170523. With partitioned tables
                          the date suffix is no longer present and special query syntax
                          has to be used instead. In both cases, tables are sharded
                          based on UTC timezone.
                        type: boolean
                    required:
                    - usePartitionedTables
                    type: object
                  description:
                    description: A description of this sink. The maximum length of
                      the description is 8000 characters.
                    type: string
                  destination:
                    description: 'The destination of the sink (or, in other words,
                      where logs are written to). Can be a Cloud Storage bucket, a
                      PubSub topic, or a BigQuery dataset. Examples: "storage.googleapis.com/[GCS_BUCKET]"
                      "bigquery.googleapis.com/projects/[PROJECT_ID]/datasets/[DATASET]"
                      "pubsub.googleapis.com/projects/[PROJECT_ID]/topics/[TOPIC_ID]"
                      The writer associated with the sink must have access to write
                      to the above resource.'
                    type: string
                  disabled:
                    description: If set to True, then this sink is disabled and it
                      does not export any log entries.
                    type: boolean
                  exclusions:
                    description: Log entries that match any of the exclusion filters
                      will not be exported. If a log entry is matched by both filter
                      and one of exclusion_filters it will not be exported.
                    items:
                      properties:
                        description:
                          description: A description of this exclusion.
                          type: string
                        disabled:
                          description: If set to True, then this exclusion is disabled
                            and it does not exclude any log entries
                          type: boolean
                        filter:
                          description: An advanced logs filter that matches the log
                            entries to be excluded. By using the sample function,
                            you can exclude less than 100% of the matching log entries
                          type: string
                        name:
                          description: A client-assigned identifier, such as "load-balancer-exclusion".
                            Identifiers are limited to 100 characters and can include
                            only letters, digits, underscores, hyphens, and periods.
                            First character has to be alphanumeric.
                          type: string
                      required:
                      - filter
                      - name
                      type: object
                    type: array
                  filter:
                    description: The filter to apply when exporting logs. Only log
                      entries that match the filter are exported.
                    type: string
                  id:
                    type: string
                  name:
                    description: The name of the logging sink.
                    type: string
                  project:
                    description: The ID of the project to create the sink in. If omitted,
                      the project associated with the provider is used.
                    type: string
                  uniqueWriterIdentity:
                    description: Whether or not to create a unique identity associated
                      with this sink. If false (the default), then the writer_identity
                      used is serviceAccount:cloud-logs@system.gserviceaccount.com.
                      If true, then a unique service account is created and used for
                      this sink. If you wish to publish logs across projects, you
                      must set unique_writer_identity to true.
                    type: boolean
                  writerIdentity:
                    description: The identity associated with this sink. This identity
                      must be granted write access to the configured destination.
                    type: string
                required:
                - destination
                - name
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
