apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: google.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: connectivityhubs.network.google.kubeform.com
spec:
  group: network.google.kubeform.com
  names:
    kind: ConnectivityHub
    listKind: ConnectivityHubList
    plural: connectivityhubs
    singular: connectivityhub
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  createTime:
                    description: Output only. The time the hub was created.
                    type: string
                  description:
                    description: An optional description of the hub.
                    type: string
                  id:
                    type: string
                  labels:
                    additionalProperties:
                      type: string
                    description: Optional labels in key:value format. For more information
                      about labels, see [Requirements for labels](https://cloud.google.com/resource-manager/docs/creating-managing-labels#requirements).
                    type: object
                  name:
                    description: 'Immutable. The name of the hub. Hub names must be
                      unique. They use the following form: `projects/{project_number}/locations/global/hubs/{hub_id}`'
                    type: string
                  project:
                    description: The project for the resource
                    type: string
                  routingVpcs:
                    description: The VPC network associated with this hub's spokes.
                      All of the VPN tunnels, VLAN attachments, and router appliance
                      instances referenced by this hub's spokes must belong to this
                      VPC network. This field is read-only. Network Connectivity Center
                      automatically populates it based on the set of spokes attached
                      to the hub.
                    items:
                      properties:
                        uri:
                          description: The URI of the VPC network.
                          type: string
                      type: object
                    type: array
                  state:
                    description: 'Output only. The current lifecycle state of this
                      hub. Possible values: STATE_UNSPECIFIED, CREATING, ACTIVE, DELETING'
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  uniqueID:
                    description: Output only. The Google-generated UUID for the hub.
                      This value is unique across all hub resources. If a hub is deleted
                      and another with the same name is created, the new hub is assigned
                      a different unique_id.
                    type: string
                  updateTime:
                    description: Output only. The time the hub was last updated.
                    type: string
                required:
                - name
                type: object
              state:
                properties:
                  createTime:
                    description: Output only. The time the hub was created.
                    type: string
                  description:
                    description: An optional description of the hub.
                    type: string
                  id:
                    type: string
                  labels:
                    additionalProperties:
                      type: string
                    description: Optional labels in key:value format. For more information
                      about labels, see [Requirements for labels](https://cloud.google.com/resource-manager/docs/creating-managing-labels#requirements).
                    type: object
                  name:
                    description: 'Immutable. The name of the hub. Hub names must be
                      unique. They use the following form: `projects/{project_number}/locations/global/hubs/{hub_id}`'
                    type: string
                  project:
                    description: The project for the resource
                    type: string
                  routingVpcs:
                    description: The VPC network associated with this hub's spokes.
                      All of the VPN tunnels, VLAN attachments, and router appliance
                      instances referenced by this hub's spokes must belong to this
                      VPC network. This field is read-only. Network Connectivity Center
                      automatically populates it based on the set of spokes attached
                      to the hub.
                    items:
                      properties:
                        uri:
                          description: The URI of the VPC network.
                          type: string
                      type: object
                    type: array
                  state:
                    description: 'Output only. The current lifecycle state of this
                      hub. Possible values: STATE_UNSPECIFIED, CREATING, ACTIVE, DELETING'
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  uniqueID:
                    description: Output only. The Google-generated UUID for the hub.
                      This value is unique across all hub resources. If a hub is deleted
                      and another with the same name is created, the new hub is assigned
                      a different unique_id.
                    type: string
                  updateTime:
                    description: Output only. The time the hub was last updated.
                    type: string
                required:
                - name
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
