apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: google.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: bucketobjects.storage.google.kubeform.com
spec:
  group: storage.google.kubeform.com
  names:
    kind: BucketObject
    listKind: BucketObjectList
    plural: bucketobjects
    singular: bucketobject
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  bucket:
                    description: The name of the containing bucket.
                    type: string
                  cacheControl:
                    description: Cache-Control directive to specify caching behavior
                      of object data. If omitted and object is accessible to all anonymous
                      users, the default will be public, max-age=3600
                    type: string
                  contentDisposition:
                    description: Content-Disposition of the object data.
                    type: string
                  contentEncoding:
                    description: Content-Encoding of the object data.
                    type: string
                  contentLanguage:
                    description: Content-Language of the object data.
                    type: string
                  contentType:
                    description: Content-Type of the object data. Defaults to "application/octet-stream"
                      or "text/plain; charset=utf-8".
                    type: string
                  crc32c:
                    description: Base 64 CRC32 hash of the uploaded data.
                    type: string
                  detectMd5hash:
                    type: string
                  id:
                    type: string
                  kmsKeyName:
                    description: Resource name of the Cloud KMS key that will be used
                      to encrypt the object. Overrides the object metadata's kmsKeyName
                      value, if any.
                    type: string
                  md5hash:
                    description: Base 64 MD5 hash of the uploaded data.
                    type: string
                  mediaLink:
                    description: A url reference to download this object.
                    type: string
                  metadata:
                    additionalProperties:
                      type: string
                    description: User-provided metadata, in key/value pairs.
                    type: object
                  name:
                    description: The name of the object. If you're interpolating the
                      name of this object, see output_name instead.
                    type: string
                  outputName:
                    description: The name of the object. Use this field in interpolations
                      with google_storage_object_acl to recreate google_storage_object_acl
                      resources when your google_storage_bucket_object is recreated.
                    type: string
                  selfLink:
                    description: A url reference to this object.
                    type: string
                  source:
                    description: A path to the data you want to upload. Must be defined
                      if content is not.
                    type: string
                  storageClass:
                    description: 'The StorageClass of the new bucket object. Supported
                      values include: MULTI_REGIONAL, REGIONAL, NEARLINE, COLDLINE,
                      ARCHIVE. If not provided, this defaults to the bucket''s default
                      storage class or to a standard class.'
                    type: string
                required:
                - bucket
                - name
                type: object
              secretRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              state:
                properties:
                  bucket:
                    description: The name of the containing bucket.
                    type: string
                  cacheControl:
                    description: Cache-Control directive to specify caching behavior
                      of object data. If omitted and object is accessible to all anonymous
                      users, the default will be public, max-age=3600
                    type: string
                  contentDisposition:
                    description: Content-Disposition of the object data.
                    type: string
                  contentEncoding:
                    description: Content-Encoding of the object data.
                    type: string
                  contentLanguage:
                    description: Content-Language of the object data.
                    type: string
                  contentType:
                    description: Content-Type of the object data. Defaults to "application/octet-stream"
                      or "text/plain; charset=utf-8".
                    type: string
                  crc32c:
                    description: Base 64 CRC32 hash of the uploaded data.
                    type: string
                  detectMd5hash:
                    type: string
                  id:
                    type: string
                  kmsKeyName:
                    description: Resource name of the Cloud KMS key that will be used
                      to encrypt the object. Overrides the object metadata's kmsKeyName
                      value, if any.
                    type: string
                  md5hash:
                    description: Base 64 MD5 hash of the uploaded data.
                    type: string
                  mediaLink:
                    description: A url reference to download this object.
                    type: string
                  metadata:
                    additionalProperties:
                      type: string
                    description: User-provided metadata, in key/value pairs.
                    type: object
                  name:
                    description: The name of the object. If you're interpolating the
                      name of this object, see output_name instead.
                    type: string
                  outputName:
                    description: The name of the object. Use this field in interpolations
                      with google_storage_object_acl to recreate google_storage_object_acl
                      resources when your google_storage_bucket_object is recreated.
                    type: string
                  selfLink:
                    description: A url reference to this object.
                    type: string
                  source:
                    description: A path to the data you want to upload. Must be defined
                      if content is not.
                    type: string
                  storageClass:
                    description: 'The StorageClass of the new bucket object. Supported
                      values include: MULTI_REGIONAL, REGIONAL, NEARLINE, COLDLINE,
                      ARCHIVE. If not provided, this defaults to the bucket''s default
                      storage class or to a standard class.'
                    type: string
                required:
                - bucket
                - name
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
