apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: google.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: notifications.storage.google.kubeform.com
spec:
  group: storage.google.kubeform.com
  names:
    kind: Notification
    listKind: NotificationList
    plural: notifications
    singular: notification
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  bucket:
                    description: The name of the bucket.
                    type: string
                  customAttributes:
                    additionalProperties:
                      type: string
                    description: ' A set of key/value attribute pairs to attach to
                      each Cloud Pub/Sub message published for this notification subscription'
                    type: object
                  eventTypes:
                    description: 'List of event type filters for this notification
                      config. If not specified, Cloud Storage will send notifications
                      for all event types. The valid types are: "OBJECT_FINALIZE",
                      "OBJECT_METADATA_UPDATE", "OBJECT_DELETE", "OBJECT_ARCHIVE"'
                    items:
                      type: string
                    type: array
                  id:
                    type: string
                  notificationID:
                    description: The ID of the created notification.
                    type: string
                  objectNamePrefix:
                    description: Specifies a prefix path filter for this notification
                      config. Cloud Storage will only send notifications for objects
                      in this bucket whose names begin with the specified prefix.
                    type: string
                  payloadFormat:
                    description: The desired content of the Payload. One of "JSON_API_V1"
                      or "NONE".
                    type: string
                  selfLink:
                    description: The URI of the created resource.
                    type: string
                  topic:
                    description: The Cloud Pub/Sub topic to which this subscription
                      publishes. Expects either the  topic name, assumed to belong
                      to the default GCP provider project, or the project-level name,  i.e.
                      projects/my-gcp-project/topics/my-topic or my-topic. If the
                      project is not set in the provider, you will need to use the
                      project-level name.
                    type: string
                required:
                - bucket
                - payloadFormat
                - topic
                type: object
              state:
                properties:
                  bucket:
                    description: The name of the bucket.
                    type: string
                  customAttributes:
                    additionalProperties:
                      type: string
                    description: ' A set of key/value attribute pairs to attach to
                      each Cloud Pub/Sub message published for this notification subscription'
                    type: object
                  eventTypes:
                    description: 'List of event type filters for this notification
                      config. If not specified, Cloud Storage will send notifications
                      for all event types. The valid types are: "OBJECT_FINALIZE",
                      "OBJECT_METADATA_UPDATE", "OBJECT_DELETE", "OBJECT_ARCHIVE"'
                    items:
                      type: string
                    type: array
                  id:
                    type: string
                  notificationID:
                    description: The ID of the created notification.
                    type: string
                  objectNamePrefix:
                    description: Specifies a prefix path filter for this notification
                      config. Cloud Storage will only send notifications for objects
                      in this bucket whose names begin with the specified prefix.
                    type: string
                  payloadFormat:
                    description: The desired content of the Payload. One of "JSON_API_V1"
                      or "NONE".
                    type: string
                  selfLink:
                    description: The URI of the created resource.
                    type: string
                  topic:
                    description: The Cloud Pub/Sub topic to which this subscription
                      publishes. Expects either the  topic name, assumed to belong
                      to the default GCP provider project, or the project-level name,  i.e.
                      projects/my-gcp-project/topics/my-topic or my-topic. If the
                      project is not set in the provider, you will need to use the
                      project-level name.
                    type: string
                required:
                - bucket
                - payloadFormat
                - topic
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
