/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubeform.dev/provider-google-api/apis/identity/v1alpha1"
)

// FakePlatformInboundSamlConfigs implements PlatformInboundSamlConfigInterface
type FakePlatformInboundSamlConfigs struct {
	Fake *FakeIdentityV1alpha1
	ns   string
}

var platforminboundsamlconfigsResource = schema.GroupVersionResource{Group: "identity.google.kubeform.com", Version: "v1alpha1", Resource: "platforminboundsamlconfigs"}

var platforminboundsamlconfigsKind = schema.GroupVersionKind{Group: "identity.google.kubeform.com", Version: "v1alpha1", Kind: "PlatformInboundSamlConfig"}

// Get takes name of the platformInboundSamlConfig, and returns the corresponding platformInboundSamlConfig object, and an error if there is any.
func (c *FakePlatformInboundSamlConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PlatformInboundSamlConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(platforminboundsamlconfigsResource, c.ns, name), &v1alpha1.PlatformInboundSamlConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PlatformInboundSamlConfig), err
}

// List takes label and field selectors, and returns the list of PlatformInboundSamlConfigs that match those selectors.
func (c *FakePlatformInboundSamlConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PlatformInboundSamlConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(platforminboundsamlconfigsResource, platforminboundsamlconfigsKind, c.ns, opts), &v1alpha1.PlatformInboundSamlConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PlatformInboundSamlConfigList{ListMeta: obj.(*v1alpha1.PlatformInboundSamlConfigList).ListMeta}
	for _, item := range obj.(*v1alpha1.PlatformInboundSamlConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested platformInboundSamlConfigs.
func (c *FakePlatformInboundSamlConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(platforminboundsamlconfigsResource, c.ns, opts))

}

// Create takes the representation of a platformInboundSamlConfig and creates it.  Returns the server's representation of the platformInboundSamlConfig, and an error, if there is any.
func (c *FakePlatformInboundSamlConfigs) Create(ctx context.Context, platformInboundSamlConfig *v1alpha1.PlatformInboundSamlConfig, opts v1.CreateOptions) (result *v1alpha1.PlatformInboundSamlConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(platforminboundsamlconfigsResource, c.ns, platformInboundSamlConfig), &v1alpha1.PlatformInboundSamlConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PlatformInboundSamlConfig), err
}

// Update takes the representation of a platformInboundSamlConfig and updates it. Returns the server's representation of the platformInboundSamlConfig, and an error, if there is any.
func (c *FakePlatformInboundSamlConfigs) Update(ctx context.Context, platformInboundSamlConfig *v1alpha1.PlatformInboundSamlConfig, opts v1.UpdateOptions) (result *v1alpha1.PlatformInboundSamlConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(platforminboundsamlconfigsResource, c.ns, platformInboundSamlConfig), &v1alpha1.PlatformInboundSamlConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PlatformInboundSamlConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePlatformInboundSamlConfigs) UpdateStatus(ctx context.Context, platformInboundSamlConfig *v1alpha1.PlatformInboundSamlConfig, opts v1.UpdateOptions) (*v1alpha1.PlatformInboundSamlConfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(platforminboundsamlconfigsResource, "status", c.ns, platformInboundSamlConfig), &v1alpha1.PlatformInboundSamlConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PlatformInboundSamlConfig), err
}

// Delete takes name of the platformInboundSamlConfig and deletes it. Returns an error if one occurs.
func (c *FakePlatformInboundSamlConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(platforminboundsamlconfigsResource, c.ns, name), &v1alpha1.PlatformInboundSamlConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePlatformInboundSamlConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(platforminboundsamlconfigsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PlatformInboundSamlConfigList{})
	return err
}

// Patch applies the patch and returns the patched platformInboundSamlConfig.
func (c *FakePlatformInboundSamlConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PlatformInboundSamlConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(platforminboundsamlconfigsResource, c.ns, name, pt, data, subresources...), &v1alpha1.PlatformInboundSamlConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PlatformInboundSamlConfig), err
}
