/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubeform.dev/provider-google-api/apis/identity/v1alpha1"
)

// FakePlatformTenantDefaultSupportedIdpConfigs implements PlatformTenantDefaultSupportedIdpConfigInterface
type FakePlatformTenantDefaultSupportedIdpConfigs struct {
	Fake *FakeIdentityV1alpha1
	ns   string
}

var platformtenantdefaultsupportedidpconfigsResource = schema.GroupVersionResource{Group: "identity.google.kubeform.com", Version: "v1alpha1", Resource: "platformtenantdefaultsupportedidpconfigs"}

var platformtenantdefaultsupportedidpconfigsKind = schema.GroupVersionKind{Group: "identity.google.kubeform.com", Version: "v1alpha1", Kind: "PlatformTenantDefaultSupportedIdpConfig"}

// Get takes name of the platformTenantDefaultSupportedIdpConfig, and returns the corresponding platformTenantDefaultSupportedIdpConfig object, and an error if there is any.
func (c *FakePlatformTenantDefaultSupportedIdpConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PlatformTenantDefaultSupportedIdpConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(platformtenantdefaultsupportedidpconfigsResource, c.ns, name), &v1alpha1.PlatformTenantDefaultSupportedIdpConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PlatformTenantDefaultSupportedIdpConfig), err
}

// List takes label and field selectors, and returns the list of PlatformTenantDefaultSupportedIdpConfigs that match those selectors.
func (c *FakePlatformTenantDefaultSupportedIdpConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PlatformTenantDefaultSupportedIdpConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(platformtenantdefaultsupportedidpconfigsResource, platformtenantdefaultsupportedidpconfigsKind, c.ns, opts), &v1alpha1.PlatformTenantDefaultSupportedIdpConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PlatformTenantDefaultSupportedIdpConfigList{ListMeta: obj.(*v1alpha1.PlatformTenantDefaultSupportedIdpConfigList).ListMeta}
	for _, item := range obj.(*v1alpha1.PlatformTenantDefaultSupportedIdpConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested platformTenantDefaultSupportedIdpConfigs.
func (c *FakePlatformTenantDefaultSupportedIdpConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(platformtenantdefaultsupportedidpconfigsResource, c.ns, opts))

}

// Create takes the representation of a platformTenantDefaultSupportedIdpConfig and creates it.  Returns the server's representation of the platformTenantDefaultSupportedIdpConfig, and an error, if there is any.
func (c *FakePlatformTenantDefaultSupportedIdpConfigs) Create(ctx context.Context, platformTenantDefaultSupportedIdpConfig *v1alpha1.PlatformTenantDefaultSupportedIdpConfig, opts v1.CreateOptions) (result *v1alpha1.PlatformTenantDefaultSupportedIdpConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(platformtenantdefaultsupportedidpconfigsResource, c.ns, platformTenantDefaultSupportedIdpConfig), &v1alpha1.PlatformTenantDefaultSupportedIdpConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PlatformTenantDefaultSupportedIdpConfig), err
}

// Update takes the representation of a platformTenantDefaultSupportedIdpConfig and updates it. Returns the server's representation of the platformTenantDefaultSupportedIdpConfig, and an error, if there is any.
func (c *FakePlatformTenantDefaultSupportedIdpConfigs) Update(ctx context.Context, platformTenantDefaultSupportedIdpConfig *v1alpha1.PlatformTenantDefaultSupportedIdpConfig, opts v1.UpdateOptions) (result *v1alpha1.PlatformTenantDefaultSupportedIdpConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(platformtenantdefaultsupportedidpconfigsResource, c.ns, platformTenantDefaultSupportedIdpConfig), &v1alpha1.PlatformTenantDefaultSupportedIdpConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PlatformTenantDefaultSupportedIdpConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePlatformTenantDefaultSupportedIdpConfigs) UpdateStatus(ctx context.Context, platformTenantDefaultSupportedIdpConfig *v1alpha1.PlatformTenantDefaultSupportedIdpConfig, opts v1.UpdateOptions) (*v1alpha1.PlatformTenantDefaultSupportedIdpConfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(platformtenantdefaultsupportedidpconfigsResource, "status", c.ns, platformTenantDefaultSupportedIdpConfig), &v1alpha1.PlatformTenantDefaultSupportedIdpConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PlatformTenantDefaultSupportedIdpConfig), err
}

// Delete takes name of the platformTenantDefaultSupportedIdpConfig and deletes it. Returns an error if one occurs.
func (c *FakePlatformTenantDefaultSupportedIdpConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(platformtenantdefaultsupportedidpconfigsResource, c.ns, name), &v1alpha1.PlatformTenantDefaultSupportedIdpConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePlatformTenantDefaultSupportedIdpConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(platformtenantdefaultsupportedidpconfigsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PlatformTenantDefaultSupportedIdpConfigList{})
	return err
}

// Patch applies the patch and returns the patched platformTenantDefaultSupportedIdpConfig.
func (c *FakePlatformTenantDefaultSupportedIdpConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PlatformTenantDefaultSupportedIdpConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(platformtenantdefaultsupportedidpconfigsResource, c.ns, name, pt, data, subresources...), &v1alpha1.PlatformTenantDefaultSupportedIdpConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PlatformTenantDefaultSupportedIdpConfig), err
}
