/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-google-api/apis/apigee/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEnvironmentIamPolicies implements EnvironmentIamPolicyInterface
type FakeEnvironmentIamPolicies struct {
	Fake *FakeApigeeV1alpha1
	ns   string
}

var environmentiampoliciesResource = schema.GroupVersionResource{Group: "apigee.google.kubeform.com", Version: "v1alpha1", Resource: "environmentiampolicies"}

var environmentiampoliciesKind = schema.GroupVersionKind{Group: "apigee.google.kubeform.com", Version: "v1alpha1", Kind: "EnvironmentIamPolicy"}

// Get takes name of the environmentIamPolicy, and returns the corresponding environmentIamPolicy object, and an error if there is any.
func (c *FakeEnvironmentIamPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.EnvironmentIamPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(environmentiampoliciesResource, c.ns, name), &v1alpha1.EnvironmentIamPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EnvironmentIamPolicy), err
}

// List takes label and field selectors, and returns the list of EnvironmentIamPolicies that match those selectors.
func (c *FakeEnvironmentIamPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.EnvironmentIamPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(environmentiampoliciesResource, environmentiampoliciesKind, c.ns, opts), &v1alpha1.EnvironmentIamPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.EnvironmentIamPolicyList{ListMeta: obj.(*v1alpha1.EnvironmentIamPolicyList).ListMeta}
	for _, item := range obj.(*v1alpha1.EnvironmentIamPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested environmentIamPolicies.
func (c *FakeEnvironmentIamPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(environmentiampoliciesResource, c.ns, opts))

}

// Create takes the representation of a environmentIamPolicy and creates it.  Returns the server's representation of the environmentIamPolicy, and an error, if there is any.
func (c *FakeEnvironmentIamPolicies) Create(ctx context.Context, environmentIamPolicy *v1alpha1.EnvironmentIamPolicy, opts v1.CreateOptions) (result *v1alpha1.EnvironmentIamPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(environmentiampoliciesResource, c.ns, environmentIamPolicy), &v1alpha1.EnvironmentIamPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EnvironmentIamPolicy), err
}

// Update takes the representation of a environmentIamPolicy and updates it. Returns the server's representation of the environmentIamPolicy, and an error, if there is any.
func (c *FakeEnvironmentIamPolicies) Update(ctx context.Context, environmentIamPolicy *v1alpha1.EnvironmentIamPolicy, opts v1.UpdateOptions) (result *v1alpha1.EnvironmentIamPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(environmentiampoliciesResource, c.ns, environmentIamPolicy), &v1alpha1.EnvironmentIamPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EnvironmentIamPolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeEnvironmentIamPolicies) UpdateStatus(ctx context.Context, environmentIamPolicy *v1alpha1.EnvironmentIamPolicy, opts v1.UpdateOptions) (*v1alpha1.EnvironmentIamPolicy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(environmentiampoliciesResource, "status", c.ns, environmentIamPolicy), &v1alpha1.EnvironmentIamPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EnvironmentIamPolicy), err
}

// Delete takes name of the environmentIamPolicy and deletes it. Returns an error if one occurs.
func (c *FakeEnvironmentIamPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(environmentiampoliciesResource, c.ns, name), &v1alpha1.EnvironmentIamPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEnvironmentIamPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(environmentiampoliciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.EnvironmentIamPolicyList{})
	return err
}

// Patch applies the patch and returns the patched environmentIamPolicy.
func (c *FakeEnvironmentIamPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.EnvironmentIamPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(environmentiampoliciesResource, c.ns, name, pt, data, subresources...), &v1alpha1.EnvironmentIamPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EnvironmentIamPolicy), err
}
