/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-google-api/apis/privateca/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCaPoolIamMembers implements CaPoolIamMemberInterface
type FakeCaPoolIamMembers struct {
	Fake *FakePrivatecaV1alpha1
	ns   string
}

var capooliammembersResource = schema.GroupVersionResource{Group: "privateca.google.kubeform.com", Version: "v1alpha1", Resource: "capooliammembers"}

var capooliammembersKind = schema.GroupVersionKind{Group: "privateca.google.kubeform.com", Version: "v1alpha1", Kind: "CaPoolIamMember"}

// Get takes name of the caPoolIamMember, and returns the corresponding caPoolIamMember object, and an error if there is any.
func (c *FakeCaPoolIamMembers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CaPoolIamMember, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(capooliammembersResource, c.ns, name), &v1alpha1.CaPoolIamMember{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CaPoolIamMember), err
}

// List takes label and field selectors, and returns the list of CaPoolIamMembers that match those selectors.
func (c *FakeCaPoolIamMembers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CaPoolIamMemberList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(capooliammembersResource, capooliammembersKind, c.ns, opts), &v1alpha1.CaPoolIamMemberList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CaPoolIamMemberList{ListMeta: obj.(*v1alpha1.CaPoolIamMemberList).ListMeta}
	for _, item := range obj.(*v1alpha1.CaPoolIamMemberList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested caPoolIamMembers.
func (c *FakeCaPoolIamMembers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(capooliammembersResource, c.ns, opts))

}

// Create takes the representation of a caPoolIamMember and creates it.  Returns the server's representation of the caPoolIamMember, and an error, if there is any.
func (c *FakeCaPoolIamMembers) Create(ctx context.Context, caPoolIamMember *v1alpha1.CaPoolIamMember, opts v1.CreateOptions) (result *v1alpha1.CaPoolIamMember, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(capooliammembersResource, c.ns, caPoolIamMember), &v1alpha1.CaPoolIamMember{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CaPoolIamMember), err
}

// Update takes the representation of a caPoolIamMember and updates it. Returns the server's representation of the caPoolIamMember, and an error, if there is any.
func (c *FakeCaPoolIamMembers) Update(ctx context.Context, caPoolIamMember *v1alpha1.CaPoolIamMember, opts v1.UpdateOptions) (result *v1alpha1.CaPoolIamMember, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(capooliammembersResource, c.ns, caPoolIamMember), &v1alpha1.CaPoolIamMember{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CaPoolIamMember), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCaPoolIamMembers) UpdateStatus(ctx context.Context, caPoolIamMember *v1alpha1.CaPoolIamMember, opts v1.UpdateOptions) (*v1alpha1.CaPoolIamMember, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(capooliammembersResource, "status", c.ns, caPoolIamMember), &v1alpha1.CaPoolIamMember{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CaPoolIamMember), err
}

// Delete takes name of the caPoolIamMember and deletes it. Returns an error if one occurs.
func (c *FakeCaPoolIamMembers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(capooliammembersResource, c.ns, name), &v1alpha1.CaPoolIamMember{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCaPoolIamMembers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(capooliammembersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CaPoolIamMemberList{})
	return err
}

// Patch applies the patch and returns the patched caPoolIamMember.
func (c *FakeCaPoolIamMembers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CaPoolIamMember, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(capooliammembersResource, c.ns, name, pt, data, subresources...), &v1alpha1.CaPoolIamMember{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CaPoolIamMember), err
}
