/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubeform.dev/provider-google-api/apis/network/v1alpha1"
)

// FakeManagementConnectivityTests implements ManagementConnectivityTestInterface
type FakeManagementConnectivityTests struct {
	Fake *FakeNetworkV1alpha1
	ns   string
}

var managementconnectivitytestsResource = schema.GroupVersionResource{Group: "network.google.kubeform.com", Version: "v1alpha1", Resource: "managementconnectivitytests"}

var managementconnectivitytestsKind = schema.GroupVersionKind{Group: "network.google.kubeform.com", Version: "v1alpha1", Kind: "ManagementConnectivityTest"}

// Get takes name of the managementConnectivityTest, and returns the corresponding managementConnectivityTest object, and an error if there is any.
func (c *FakeManagementConnectivityTests) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ManagementConnectivityTest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(managementconnectivitytestsResource, c.ns, name), &v1alpha1.ManagementConnectivityTest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagementConnectivityTest), err
}

// List takes label and field selectors, and returns the list of ManagementConnectivityTests that match those selectors.
func (c *FakeManagementConnectivityTests) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ManagementConnectivityTestList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(managementconnectivitytestsResource, managementconnectivitytestsKind, c.ns, opts), &v1alpha1.ManagementConnectivityTestList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ManagementConnectivityTestList{ListMeta: obj.(*v1alpha1.ManagementConnectivityTestList).ListMeta}
	for _, item := range obj.(*v1alpha1.ManagementConnectivityTestList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested managementConnectivityTests.
func (c *FakeManagementConnectivityTests) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(managementconnectivitytestsResource, c.ns, opts))

}

// Create takes the representation of a managementConnectivityTest and creates it.  Returns the server's representation of the managementConnectivityTest, and an error, if there is any.
func (c *FakeManagementConnectivityTests) Create(ctx context.Context, managementConnectivityTest *v1alpha1.ManagementConnectivityTest, opts v1.CreateOptions) (result *v1alpha1.ManagementConnectivityTest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(managementconnectivitytestsResource, c.ns, managementConnectivityTest), &v1alpha1.ManagementConnectivityTest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagementConnectivityTest), err
}

// Update takes the representation of a managementConnectivityTest and updates it. Returns the server's representation of the managementConnectivityTest, and an error, if there is any.
func (c *FakeManagementConnectivityTests) Update(ctx context.Context, managementConnectivityTest *v1alpha1.ManagementConnectivityTest, opts v1.UpdateOptions) (result *v1alpha1.ManagementConnectivityTest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(managementconnectivitytestsResource, c.ns, managementConnectivityTest), &v1alpha1.ManagementConnectivityTest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagementConnectivityTest), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeManagementConnectivityTests) UpdateStatus(ctx context.Context, managementConnectivityTest *v1alpha1.ManagementConnectivityTest, opts v1.UpdateOptions) (*v1alpha1.ManagementConnectivityTest, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(managementconnectivitytestsResource, "status", c.ns, managementConnectivityTest), &v1alpha1.ManagementConnectivityTest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagementConnectivityTest), err
}

// Delete takes name of the managementConnectivityTest and deletes it. Returns an error if one occurs.
func (c *FakeManagementConnectivityTests) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(managementconnectivitytestsResource, c.ns, name), &v1alpha1.ManagementConnectivityTest{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeManagementConnectivityTests) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(managementconnectivitytestsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ManagementConnectivityTestList{})
	return err
}

// Patch applies the patch and returns the patched managementConnectivityTest.
func (c *FakeManagementConnectivityTests) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ManagementConnectivityTest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(managementconnectivitytestsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ManagementConnectivityTest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagementConnectivityTest), err
}
