/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubeform.dev/provider-google-api/apis/storage/v1alpha1"
)

// FakeHmacKeys implements HmacKeyInterface
type FakeHmacKeys struct {
	Fake *FakeStorageV1alpha1
	ns   string
}

var hmackeysResource = schema.GroupVersionResource{Group: "storage.google.kubeform.com", Version: "v1alpha1", Resource: "hmackeys"}

var hmackeysKind = schema.GroupVersionKind{Group: "storage.google.kubeform.com", Version: "v1alpha1", Kind: "HmacKey"}

// Get takes name of the hmacKey, and returns the corresponding hmacKey object, and an error if there is any.
func (c *FakeHmacKeys) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.HmacKey, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(hmackeysResource, c.ns, name), &v1alpha1.HmacKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HmacKey), err
}

// List takes label and field selectors, and returns the list of HmacKeys that match those selectors.
func (c *FakeHmacKeys) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.HmacKeyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(hmackeysResource, hmackeysKind, c.ns, opts), &v1alpha1.HmacKeyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.HmacKeyList{ListMeta: obj.(*v1alpha1.HmacKeyList).ListMeta}
	for _, item := range obj.(*v1alpha1.HmacKeyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested hmacKeys.
func (c *FakeHmacKeys) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(hmackeysResource, c.ns, opts))

}

// Create takes the representation of a hmacKey and creates it.  Returns the server's representation of the hmacKey, and an error, if there is any.
func (c *FakeHmacKeys) Create(ctx context.Context, hmacKey *v1alpha1.HmacKey, opts v1.CreateOptions) (result *v1alpha1.HmacKey, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(hmackeysResource, c.ns, hmacKey), &v1alpha1.HmacKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HmacKey), err
}

// Update takes the representation of a hmacKey and updates it. Returns the server's representation of the hmacKey, and an error, if there is any.
func (c *FakeHmacKeys) Update(ctx context.Context, hmacKey *v1alpha1.HmacKey, opts v1.UpdateOptions) (result *v1alpha1.HmacKey, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(hmackeysResource, c.ns, hmacKey), &v1alpha1.HmacKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HmacKey), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeHmacKeys) UpdateStatus(ctx context.Context, hmacKey *v1alpha1.HmacKey, opts v1.UpdateOptions) (*v1alpha1.HmacKey, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(hmackeysResource, "status", c.ns, hmacKey), &v1alpha1.HmacKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HmacKey), err
}

// Delete takes name of the hmacKey and deletes it. Returns an error if one occurs.
func (c *FakeHmacKeys) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(hmackeysResource, c.ns, name), &v1alpha1.HmacKey{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHmacKeys) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(hmackeysResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.HmacKeyList{})
	return err
}

// Patch applies the patch and returns the patched hmacKey.
func (c *FakeHmacKeys) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HmacKey, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(hmackeysResource, c.ns, name, pt, data, subresources...), &v1alpha1.HmacKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HmacKey), err
}
