/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "kubeform.dev/provider-google-api/apis/healthcare/v1alpha1"
)

// Hl7V2StoreIamMemberLister helps list Hl7V2StoreIamMembers.
// All objects returned here must be treated as read-only.
type Hl7V2StoreIamMemberLister interface {
	// List lists all Hl7V2StoreIamMembers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.Hl7V2StoreIamMember, err error)
	// Hl7V2StoreIamMembers returns an object that can list and get Hl7V2StoreIamMembers.
	Hl7V2StoreIamMembers(namespace string) Hl7V2StoreIamMemberNamespaceLister
	Hl7V2StoreIamMemberListerExpansion
}

// hl7V2StoreIamMemberLister implements the Hl7V2StoreIamMemberLister interface.
type hl7V2StoreIamMemberLister struct {
	indexer cache.Indexer
}

// NewHl7V2StoreIamMemberLister returns a new Hl7V2StoreIamMemberLister.
func NewHl7V2StoreIamMemberLister(indexer cache.Indexer) Hl7V2StoreIamMemberLister {
	return &hl7V2StoreIamMemberLister{indexer: indexer}
}

// List lists all Hl7V2StoreIamMembers in the indexer.
func (s *hl7V2StoreIamMemberLister) List(selector labels.Selector) (ret []*v1alpha1.Hl7V2StoreIamMember, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.Hl7V2StoreIamMember))
	})
	return ret, err
}

// Hl7V2StoreIamMembers returns an object that can list and get Hl7V2StoreIamMembers.
func (s *hl7V2StoreIamMemberLister) Hl7V2StoreIamMembers(namespace string) Hl7V2StoreIamMemberNamespaceLister {
	return hl7V2StoreIamMemberNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// Hl7V2StoreIamMemberNamespaceLister helps list and get Hl7V2StoreIamMembers.
// All objects returned here must be treated as read-only.
type Hl7V2StoreIamMemberNamespaceLister interface {
	// List lists all Hl7V2StoreIamMembers in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.Hl7V2StoreIamMember, err error)
	// Get retrieves the Hl7V2StoreIamMember from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.Hl7V2StoreIamMember, error)
	Hl7V2StoreIamMemberNamespaceListerExpansion
}

// hl7V2StoreIamMemberNamespaceLister implements the Hl7V2StoreIamMemberNamespaceLister
// interface.
type hl7V2StoreIamMemberNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all Hl7V2StoreIamMembers in the indexer for a given namespace.
func (s hl7V2StoreIamMemberNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.Hl7V2StoreIamMember, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.Hl7V2StoreIamMember))
	})
	return ret, err
}

// Get retrieves the Hl7V2StoreIamMember from the indexer for a given namespace and name.
func (s hl7V2StoreIamMemberNamespaceLister) Get(name string) (*v1alpha1.Hl7V2StoreIamMember, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("hl7v2storeiammember"), name)
	}
	return obj.(*v1alpha1.Hl7V2StoreIamMember), nil
}
